'use client';
import {FormEvent,useEffect,useMemo,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabase';

type Game={id:string;title:string;status:string;current_round:number;turn_open:boolean;turn_ends_at:string|null};
type Member={user_id:string;full_name:string;kind:'student'|'teacher'|'observer';role_title:string|null;team:string|null;score:number};
type Metric={id:string;metric_key:string;label:string;value:number;previous_value:number|null;unit:string|null};
type EventItem={id:string;category:string;severity:string;title:string;body:string;round_no:number;published_at:string};
type ActionItem={id:string;author_id:string;action_type:string;title:string;body:string;budget:number;status:string;submitted_at:string};
type Channel={id:string;name:string;kind:string};
type Message={id:string;channel_id:string;author_id:string;kind:string;text:string|null;storage_path:string|null;created_at:string;url?:string|null};

export default function GameClient({gameId}:{gameId:string}){
 const router=useRouter();const [game,setGame]=useState<Game|null>(null),[me,setMe]=useState<Member|null>(null),[metrics,setMetrics]=useState<Metric[]>([]),[events,setEvents]=useState<EventItem[]>([]),[actions,setActions]=useState<ActionItem[]>([]),[members,setMembers]=useState<Member[]>([]),[channels,setChannels]=useState<Channel[]>([]),[channelId,setChannelId]=useState(''),[messages,setMessages]=useState<Message[]>([]),[view,setView]=useState<'state'|'actions'|'teacher'>('state'),[error,setError]=useState('');
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[actionType,setActionType]=useState('Проект управленческого решения'),[budget,setBudget]=useState(0),[chatText,setChatText]=useState(''),[eventTitle,setEventTitle]=useState(''),[eventBody,setEventBody]=useState('');
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]);
 const names=useMemo(()=>Object.fromEntries(members.map(x=>[x.user_id,x.full_name])),[members]);const teacher=me?.kind==='teacher';

 async function load(){
  const u=(await supabase.auth.getUser()).data.user;if(!u){router.replace('/');return}
  const [g,m,mt,ev,ac,mb,ch]=await Promise.all([
   supabase.from('games').select('*').eq('id',gameId).single(),
   supabase.from('game_members').select('*').eq('game_id',gameId).eq('user_id',u.id).single(),
   supabase.from('state_metrics').select('*').eq('game_id',gameId).order('label'),
   supabase.from('game_events').select('*').eq('game_id',gameId).order('published_at',{ascending:false}),
   supabase.from('player_actions').select('*').eq('game_id',gameId).order('submitted_at',{ascending:false}),
   supabase.from('game_members').select('*').eq('game_id',gameId).order('full_name'),
   supabase.from('chat_channels').select('*').eq('game_id',gameId).order('name')
  ]);
  if(g.error||m.error){setError(g.error?.message||m.error?.message||'Нет доступа');return}
  setGame(g.data as Game);setMe(m.data as Member);setMetrics((mt.data||[]) as Metric[]);setEvents((ev.data||[]) as EventItem[]);setActions((ac.data||[]) as ActionItem[]);setMembers((mb.data||[]) as Member[]);setChannels((ch.data||[]) as Channel[]);if(ch.data?.[0])setChannelId(ch.data[0].id);
 }
 async function reload(){await load()}
 useEffect(()=>{void load();const c=supabase.channel('gossim:'+gameId).on('postgres_changes',{event:'*',schema:'public',table:'games',filter:'id=eq.'+gameId},()=>void reload()).on('postgres_changes',{event:'*',schema:'public',table:'state_metrics',filter:'game_id=eq.'+gameId},()=>void reload()).on('postgres_changes',{event:'*',schema:'public',table:'game_events',filter:'game_id=eq.'+gameId},()=>void reload()).on('postgres_changes',{event:'*',schema:'public',table:'player_actions',filter:'game_id=eq.'+gameId},()=>void reload()).on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages',filter:'game_id=eq.'+gameId},()=>channelId&&void loadMessages(channelId)).subscribe();return()=>{void supabase.removeChannel(c)}},[gameId]);
 useEffect(()=>{if(channelId)void loadMessages(channelId)},[channelId]);
 async function loadMessages(cid:string){const r=await supabase.from('chat_messages').select('*').eq('channel_id',cid).order('created_at').limit(100);const rows=await Promise.all(((r.data||[]) as Message[]).map(async m=>{if(!m.storage_path)return m;const x=await supabase.storage.from('game-media').createSignedUrl(m.storage_path,3600);return {...m,url:x.data?.signedUrl||null}}));setMessages(rows)}
 async function submit(e:FormEvent){e.preventDefault();if(!me||!game)return;const r=await supabase.from('player_actions').insert({game_id:gameId,round_no:game.current_round,author_id:me.user_id,action_type:actionType,title,body,budget,status:'submitted'});if(r.error)setError(r.error.message);else{setTitle('');setBody('');setBudget(0);void reload()}}
 async function send(){if(!me||!channelId||!chatText.trim())return;const text=chatText.trim();setChatText('');const r=await supabase.from('chat_messages').insert({game_id:gameId,channel_id:channelId,author_id:me.user_id,kind:'text',text});if(r.error)setError(r.error.message);else void loadMessages(channelId)}
 async function record(kind:'audio'|'video'){if(recorder.current?.state==='recording')return recorder.current.stop();if(!me||!channelId)return;try{const st=await navigator.mediaDevices.getUserMedia(kind==='audio'?{audio:true}:{audio:true,video:true});stream.current=st;chunks.current=[];const rr=new MediaRecorder(st);recorder.current=rr;rr.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);rr.onstop=async()=>{const blob=new Blob(chunks.current,{type:rr.mimeType});const path=`${gameId}/${channelId}/${me.user_id}/${crypto.randomUUID()}.webm`;const up=await supabase.storage.from('game-media').upload(path,blob,{contentType:rr.mimeType});if(!up.error)await supabase.from('chat_messages').insert({game_id:gameId,channel_id:channelId,author_id:me.user_id,kind,storage_path:path,mime_type:rr.mimeType});st.getTracks().forEach(t=>t.stop());recorder.current=null;void loadMessages(channelId)};rr.start()}catch(e){setError(e instanceof Error?e.message:'Нет доступа к медиа')}}
 async function setTurn(open:boolean){const r=await supabase.from('games').update({turn_open:open,status:open?'running':'paused',turn_ends_at:open?new Date(Date.now()+720000).toISOString():null}).eq('id',gameId);if(r.error)setError(r.error.message)}
 async function nextRound(){if(!game)return;const r=await supabase.from('games').update({current_round:game.current_round+1,turn_open:true,status:'running',turn_ends_at:new Date(Date.now()+720000).toISOString()}).eq('id',gameId);if(r.error)setError(r.error.message)}
 async function publish(){if(!game||!me||!eventTitle.trim()||!eventBody.trim())return;const r=await supabase.from('game_events').insert({game_id:gameId,round_no:game.current_round,category:'teacher',severity:'info',title:eventTitle,body:eventBody,created_by:me.user_id});if(r.error)setError(r.error.message);else{setEventTitle('');setEventBody('')}}
 async function judge(id:string,status:'accepted'|'rejected'){const r=await supabase.from('player_actions').update({status,reviewed_by:me?.user_id,reviewed_at:new Date().toISOString()}).eq('id',id);if(r.error)setError(r.error.message)}
 if(!game||!me)return <main className="loginPage"><div>{error||'Подключение к игре…'}</div></main>;
 return <div className="gamePage"><header className="gameTop"><div className="brand">GOS//SIM</div><div><b>{game.title}</b> · раунд {game.current_round} · {game.turn_open?'ход открыт':'пауза'}</div><button className="ghost" onClick={()=>supabase.auth.signOut().then(()=>router.replace('/'))}>Выйти</button></header>
 <div className="gameGrid"><aside className="side"><button className="secondary" onClick={()=>setView('state')}>Государство</button><button className="secondary" onClick={()=>setView('actions')}>Мои действия</button>{teacher&&<button className="primary" onClick={()=>setView('teacher')}>Преподаватель</button>}</aside>
 <main className="main">{error&&<div className="errorBox">{error}</div>}
 {view==='state'&&<><h1>Ситуационный центр</h1><p className="muted">Ваша роль: {me.role_title||me.kind}</p><div className="cards">{metrics.map(m=><div className="card metric" key={m.id}><span>{m.label}</span><strong>{m.value}{m.unit||''}</strong></div>)}</div><section className="card feed"><h2>События государства</h2>{events.map(e=><article className="event" key={e.id}><b>{e.title}</b><p className="muted">{e.body}</p></article>)}</section></>}
 {view==='actions'&&<><h1>Решения</h1><form className="card formGrid" onSubmit={submit}><select value={actionType} onChange={e=>setActionType(e.target.value)}><option>Проект управленческого решения</option><option>Публичное заявление</option><option>Запрос ресурса</option></select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Название" required/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Обоснование" required/><input type="number" value={budget} onChange={e=>setBudget(+e.target.value)} placeholder="Бюджет"/><button className="primary">Отправить</button></form><div className="card feed">{actions.filter(a=>teacher||a.author_id===me.user_id).map(a=><div className="action" key={a.id}><b>{a.title}</b><p className="muted">{a.body}</p><span className="pill">{a.status}</span></div>)}</div></>}
 {view==='teacher'&&teacher&&<><h1>Режиссёрская</h1><div className="teacherGrid"><section className="card"><h2>Раунд</h2><div className="toolbar"><button className="primary" onClick={()=>void nextRound()}>Следующий раунд</button><button className="secondary" onClick={()=>void setTurn(!game.turn_open)}>{game.turn_open?'Закрыть ход':'Открыть ход'}</button></div></section><section className="card formGrid"><h2>Новое событие</h2><input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Заголовок"/><textarea value={eventBody} onChange={e=>setEventBody(e.target.value)} placeholder="Описание"/><button className="primary" onClick={()=>void publish()}>Опубликовать</button></section><section className="card"><h2>Участники</h2>{members.map(m=><div className="action" key={m.user_id}><b>{m.full_name}</b><p className="muted">{m.role_title||m.kind}</p></div>)}</section><section className="card"><h2>Очередь решений</h2>{actions.filter(a=>a.status==='submitted').map(a=><div className="action" key={a.id}><b>{a.title}</b><p className="muted">{names[a.author_id]||a.author_id}</p><div className="toolbar"><button className="primary" onClick={()=>void judge(a.id,'accepted')}>Принять</button><button className="secondary" onClick={()=>void judge(a.id,'rejected')}>Отклонить</button></div></div>)}</section></div></>}
 </main><aside className="chat"><div className="chatHead"><b>Коммуникации</b><select value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="messages">{messages.map(m=><div className="msg" key={m.id}><small>{names[m.author_id]||'Система'}</small>{m.text&&<p>{m.text}</p>}{m.kind==='audio'&&m.url&&<audio controls src={m.url}/>} {m.kind==='video'&&m.url&&<video controls playsInline src={m.url}/>}</div>)}</div><div className="chatCompose"><textarea value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="Сообщение"/><div className="toolbar"><button className="ghost" onClick={()=>void record('audio')}>🎙</button><button className="ghost" onClick={()=>void record('video')}>◉</button><button className="primary" onClick={()=>void send()}>Отправить</button></div></div></aside></div></div>
}
