'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ChartNoAxesCombined,Coins,FileText,Landmark,List,Map as MapIcon,RefreshCw,Save,Search} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import type {ReturnTypeRepublic} from './viewTypes';
import catalog from '@/data/taxes-2026.json';
import mapData from '@/data/region-paths.json';
import {fiscalForecast,fiscalTotal,fiscalEnvironment,type FiscalContext,type FiscalRegion,type FiscalRate} from './fiscalMath';
import {moneyMillions,scenarioMoney,quantity} from '@/lib/formatQuantity';
import FiscalMacroPanel from './FiscalMacroPanel';
import {userError} from '@/lib/userError';
import StyledSelect from '../ui/StyledSelect';
type Proposal={id:string;tax_key:string;region_code:string;new_rate:number;status:string;document_id:string|null;author_id:string};
type Change={id:number;region_code:string|null;note:string;source_type:string;created_at:string};
type LegalPlan={id:string;title:string;budget_year:number;source_note:string|null;revenue:number;expenditure:number;balance:number;debt_end:number;financing:number;legal_status:'draft'|'ready'|'published';document_id:string|null;registry_no:string|null;document_status:string|null;allocations:{program_id:string;title:string;ministry:string;amount:number}[]};
type ApprovedProgram={id:string;title:string;ministry:string;total_budget:number;vote_id:string|null};
type Case={id:string;title:string;comic_scene:{region_code?:string};status:string;assigned?:boolean};
function mapViewport(mode:string,code:string){if(mode==='all')return '0 0 1040 600';if(mode==='west')return '15 145 420 435';const p=mapData.paths.find(p=>p.code===code);if(!p)return '0 0 1040 600';const pairs=[...p.path.matchAll(/[ML](-?[\d.]+),(-?[\d.]+)/g)].map(x=>[Number(x[1]),Number(x[2])]);if(!pairs.length)return '0 0 1040 600';const xs=pairs.map(x=>x[0]),ys=pairs.map(x=>x[1]),w=Math.max(45,Math.max(...xs)-Math.min(...xs)+24),h=Math.max(45,Math.max(...ys)-Math.min(...ys)+24);return [Math.min(...xs)-12,Math.min(...ys)-12,w,h].join(' ')}
const money=(n:number|null)=>n===null?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(n);
const profileLabel:Record<string,string>={metropolis:'Городская экономика',resources:'Добывающий сектор',agriculture:'Агропромышленный сектор',northern:'Высокая стоимость инфраструктуры',tourism:'Туризм и услуги',industrial:'Промышленность и услуги'};
export default function BudgetView({g,readOnly=false,onOpenDocument,onOpenEvents,onOpenStage}:{g:ReturnTypeRepublic;readOnly?:boolean;onOpenDocument:(id:string)=>void;onOpenEvents:()=>void;onOpenStage?:(stageNo:number)=>void}){
 const [regions,setRegions]=useState<FiscalRegion[]>([]),[rates,setRates]=useState<FiscalRate[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[ledger,setLedger]=useState<Change[]>([]);
 const [context,setContext]=useState<FiscalContext|null>(null);
 const [plans,setPlans]=useState<LegalPlan[]>([]),[programs,setPrograms]=useState<ApprovedProgram[]>([]);
 const [selected,setSelected]=useState('54'),[mode,setMode]=useState<'map'|'table'>('map'),[mapZoom,setMapZoom]=useState('all'),[search,setSearch]=useState(''),[sort,setSort]=useState('name'),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[canPropose,setCanPropose]=useState(false),[notice,setNotice]=useState('');
 const [taxKey,setTaxKey]=useState('corporate_property'),[rate,setRate]=useState('2.2'),[parameters,setParameters]=useState<Record<string,string>>({}),[cases,setCases]=useState<Case[]>([]),[act,setAct]=useState('');
 const region=regions.find(r=>r.region_code===selected),forecast=region?fiscalForecast(region,rates,undefined,context):null;
 const total=useMemo(()=>fiscalTotal(regions,rates,context),[regions,rates,context]);
 const tax=catalog.taxes.find(t=>t.key===taxKey)!;
 async function load(){
  if(!g.game)return;const [r,c,p,m]=await Promise.all([supabase.rpc('get_fiscal_budget',{p_game_id:g.game.id}),supabase.rpc('list_regional_cases',{p_game_id:g.game.id}),supabase.rpc('get_fiscal_legal_plans',{p_game_id:g.game.id}),supabase.rpc('get_fiscal_context',{p_game_id:g.game.id})]);
  if(!m.error&&m.data)setContext(m.data);else if(m.error)g.setError(userError(m.error));
  if(!p.error&&p.data){setPlans(p.data.plans||[]);setPrograms(p.data.programs||[])}
  if(!c.error)setCases((c.data||[]) as Case[]);
  if(r.error){g.setError(userError(r.error));return}
  if(r.data&&typeof r.data==='object'){setRegions(r.data.regions||[]);setRates(r.data.rates||[]);setProposals(r.data.proposals||[]);setLedger(r.data.ledger||[]);setCanPropose(!!r.data.can_propose);}setReady(true);
 }
 useEffect(()=>{void load();if(!g.game)return;const id=setInterval(()=>void load(),20000);return()=>clearInterval(id)},[g.game?.id,g.me?.user_id]);
 useEffect(()=>{if(!g.game)return;let pending:ReturnType<typeof setTimeout>|undefined;const update=()=>{clearTimeout(pending);pending=setTimeout(()=>void load(),160)};let channel=supabase.channel('fiscal-live:'+g.game.id);for(const table of ['game_fiscal_policy','game_fiscal_regions','game_fiscal_rates','fiscal_rate_proposals','fiscal_change_ledger','state_metrics','budget_scenarios','budget_program_allocations'])channel=channel.on('postgres_changes',{event:'*',schema:'public',table,filter:'game_id=eq.'+g.game.id},update);channel.subscribe();return()=>{clearTimeout(pending);void supabase.removeChannel(channel)}},[g.game?.id,g.me?.user_id]);
 useEffect(()=>{if(!region)return;setParameters(Object.fromEntries(['enterprises','employees_per_firm','monthly_wage','profit_per_firm','consumption_per_firm','expenditure','transfer_in','debt','compliance'].map(k=>[k,String(region[k as keyof FiscalRegion])])));},[region?.region_code,region?.enterprises,region?.expenditure,region?.monthly_wage]);
 useEffect(()=>{const scope=tax.level==='federal'?'00':selected;setRate(String(rates.find(r=>r.tax_key===taxKey&&r.region_code===scope)?.rate??tax.default_rate??''));},[taxKey,selected,rates]);
 async function propose(){
  if(!g.game||readOnly||busy||!Number.isFinite(Number(rate)))return;
  setBusy(true);const r=await supabase.rpc('propose_fiscal_rate',{p_game_id:g.game.id,p_region:selected,p_tax:taxKey,p_rate:Number(rate)});setBusy(false);
  if(r.error)g.setError(userError(r.error));else{setNotice('Предложение записано. Действующая ставка изменится после опубликования и проверки соответствующего акта.');await load()}
 }
 async function saveParameters(){
  if(!g.game||readOnly||!g.teacher||busy)return;
  const values=Object.fromEntries(Object.entries(parameters).map(([k,v])=>[k,Number(v)]));if(Object.values(values).some(v=>!Number.isFinite(v))){setNotice('Заполните числовые параметры.');return}
  setBusy(true);const r=await supabase.rpc('set_fiscal_parameters',{p_game_id:g.game.id,p_region:selected,p_values:values});setBusy(false);
  if(r.error)g.setError(userError(r.error));else{setNotice('Параметры сценария сохранены для всей группы.');await load()}
 }
 async function apply(id:string){
  if(readOnly||busy||!g.teacher)return;setBusy(true);const r=await supabase.rpc('apply_fiscal_rate_proposal',{p_proposal:id,p_document:act||null});setBusy(false);
  if(r.error)g.setError(userError(r.error));else{setNotice('Ставка учебного прогноза изменена по опубликованному документу.');await load()}
 }
 async function practice(c:Case){
  if(readOnly||busy)return;if(c.assigned){onOpenEvents();return}setBusy(true);const r=await supabase.rpc('start_regional_case',{p_case_id:c.id});setBusy(false);if(r.error)g.setError(userError(r.error));else onOpenEvents();
 }
 const filtered=regions.filter(r=>r.name.toLocaleLowerCase('ru').includes(search.trim().toLocaleLowerCase('ru'))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'ru'):sort==='enterprises'?b.enterprises-a.enterprises:fiscalForecast(b,rates,undefined,context).balance-fiscalForecast(a,rates,undefined,context).balance);
 const preview=region&&Number.isFinite(Number(rate))?fiscalForecast(region,rates,{tax:taxKey,rate:Number(rate)},context):null;
 const regionCases=cases.filter(c=>c.comic_scene?.region_code===selected);
 return <div className="budgetPage">
 <header className="budgetHero"><div><small>ФЕДЕРАЦИЯ · РЕГИОНЫ · МУНИЦИПАЛИТЕТЫ</small><h1>Бюджет</h1><p>Сравните доходы и обязательства, предложите налоговую меру и проведите её через НПА. После принятия увидите, как изменился общий бюджет.</p></div><button type="button" className="secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={18}/> Обновить данные</button></header>
 <div className="budgetScenarioNote"><b>Учебный бюджет · млн рублей</b><span>Числа модели не являются бюджетами реальных регионов. Параметры задаёт преподаватель; нормы зачисления доходов сокращены для игры. Реальные наблюдения показаны отдельно с источником и годом.</span></div>
 {!ready?<p role="status">Загружаем общую бюджетную модель…</p>:<>
 <section className="budgetStudentPath" aria-label="Что делать студенту"><h2>Ваш следующий шаг</h2><ol><li><b>Выберите регион</b><span>Посмотрите доходы, расходы и правовую задачу на карте ниже.</span></li><li><b>Сравните варианты</b><span>Измените ставку в калькуляторе. Прогноз доступен каждому.</span></li><li><b>Оформите решение</b><span>Исполнительная власть направляет предложение; участники принимают соответствующий НПА.</span></li><li><b>Проверьте результат</b><span>После опубликования акта обновятся суммы и журнал изменений.</span></li></ol></section>
 <div className="budgetKpis budgetLevelCards">{[
 {label:'Федеральный бюджет',revenue:total.federal,low:total.federalLow,high:total.federalHigh,expense:context?context.policy.federal_expenditure*fiscalEnvironment(context).cost+total.transfers:null,note:'Федеральные поступления; расходы включают региональные трансферты.'},
 {label:'Региональные бюджеты',revenue:total.revenue,low:total.revenueLow,high:total.revenueHigh,expense:total.expenditure,note:'Сумма по 89 регионам, включая полученные трансферты.'},
 {label:'Местные бюджеты',revenue:total.municipal,low:total.municipalLow,high:total.municipalHigh,expense:context?context.policy.municipal_expenditure*fiscalEnvironment(context).cost:null,note:'Местные поступления и обязательства муниципалитетов.'}
 ].map(({label,revenue,low,high,expense,note})=>{const spread=fiscalEnvironment(context).uncertainty;return <article key={label}><h2>{label}</h2><dl><div><dt>Планируемые доходы</dt><dd>{moneyMillions(revenue)}</dd><small>От {moneyMillions(low)} до {moneyMillions(high)}</small></div><div><dt>Планируемые расходы</dt><dd>{moneyMillions(expense)}</dd>{expense!==null&&<small>От {moneyMillions(expense*(1-spread))} до {moneyMillions(expense*(1+spread))}</small>}</div><div><dt>Баланс</dt><dd>{expense===null?'Загрузка плана расходов…':moneyMillions(revenue-expense)}</dd></div></dl><span>{note}</span></article>})}</div>
 <FiscalMacroPanel g={g} context={context} readOnly={readOnly} onSaved={load}/>
 <p className="budgetEnterpriseCount">В налоговой модели: <b>{quantity(total.enterprises,'предприятий')}</b>. Изменения событий учитываются в расчёте.</p>
 <details className="surface budgetMethod"><summary><ChartNoAxesCombined size={18}/> Как решения меняют бюджет</summary><div><p>Налоговая база зависит от предприятий, занятости, зарплаты, прибыли и деловой активности. Доход по выбранной базе = база × ставка × собираемость. Транспортный налог считается по мощности, а не в процентах.</p><p>Расходы = обязательства × коэффициент стоимости. Дефицит увеличивает расчётную потребность в финансировании: долг следующего периода = исходный долг + max(0; расходы − доходы). Это сценарий, заимствование требует отдельного решения.</p><p>Повышение ставки немедленно меняет поступления. В прогнозе следующего периода рост налоговой нагрузки может снижать активность предприятий. Эластичность — учебное допущение, не экономический прогноз. Исходы региональных кейсов меняют предприятия, расходы или коэффициенты только один раз и сохраняют источник в журнале.</p><p>Тип налога не определяет единственный бюджет-получатель. В учебной схеме прибыль делится 32% / 68%, базовый НДФЛ 85% / 15%; остальные выбранные потоки распределяются по уровню. В действующем праве применяются точные нормативы БК РФ, в том числе специальные нормы по категориям доходов.</p></div></details>
 <section className="surface budgetLegalPlans"><header><div><small>ПРОГРАММЫ · СЦЕНАРИЙ · ЗАКОН О БЮДЖЕТЕ</small><h2>Федеральный бюджет и государственные программы</h2></div>{onOpenStage&&<button type="button" className="secondary" onClick={()=>onOpenStage(13)}><ArrowRight size={18}/> Разработать бюджет</button>}</header><p>Расчёты поступают из бюджетной лаборатории этапа 13. Фиксация сценария ещё не вводит бюджет в действие: проект проходит процедуру НПА. Утверждение программы само по себе не означает выделение или расходование средств.</p><p className="budgetPlanUnits">Единицы указаны в источнике каждого сценария. Эти суммы не складываются с региональным прогнозом в миллионах рублей; финансирование программы уже входит в общую сумму расходов сценария.</p>
 {plans.length?<div className="budgetPlanGrid">{plans.map(p=><article key={p.id}><header><div><small>{p.budget_year} ГОД</small><h3>{p.title}</h3></div><span className={'budgetPlanStatus '+p.legal_status}>{({draft:'Рабочий расчёт',ready:'Сценарий зафиксирован',published:'Закон опубликован'})[p.legal_status]}</span></header><dl>{[['Доходы',p.revenue],['Расходы',p.expenditure],['Баланс',p.balance],['Долг на конец',p.debt_end],['Иное финансирование',p.financing]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{scenarioMoney(Number(value),p.source_note)}</dd></div>)}</dl><p>Источник и единицы: {p.source_note||'Не указаны — дополните обоснование сценария перед рассмотрением.'}</p>{p.document_id&&<button type="button" className="secondary" onClick={()=>onOpenDocument(p.document_id!)}><FileText size={18}/><span>{p.registry_no} · {p.document_status}</span></button>}<details><summary>Финансирование программ · {p.allocations.length}</summary>{p.allocations.length?p.allocations.map(a=><div className="budgetPlanAllocation" key={a.program_id}><span><b>{a.title}</b><small>{a.ministry}</small></span><strong>{scenarioMoney(a.amount,p.source_note)}</strong></div>):<p>Распределение на утверждённые программы пока не предусмотрено.</p>}</details></article>)}</div>:<p>Сценариев пока нет. В этапе 13 сопоставьте доходы, обязательства и источники покрытия дефицита, затем сформируйте проект закона.</p>}
 <details className="budgetApprovedPrograms"><summary>Утверждённые программы · {programs.length}</summary>{programs.length?programs.map(p=><div className="budgetPlanAllocation" key={p.id}><span><b>{p.title}</b><small>{p.ministry} · Объём по паспорту: {scenarioMoney(p.total_budget)}</small></span>{onOpenStage&&<button type="button" className="secondary" onClick={()=>onOpenStage(11)}>Рассмотрение</button>}</div>):<p>Программы появятся здесь после решения Правительства в этапе 11.</p>}</details></section>
 <details className="surface budgetTaxGuide"><summary><Landmark size={18}/> Справочник налогов и специальных режимов <span>Раскрыть</span></summary><div className="budgetTaxGuideBody"><p>Федеральные, региональные и местные налоги. По состоянию на 1 октября 2026 года.</p>
 <div className="budgetTaxLevels">{[['federal','Федеральные'],['regional','Региональные'],['municipal','Местные']].map(([level,label])=><section key={level}><h3>{label}</h3>{catalog.taxes.filter(t=>t.level===level).map(t=><details key={t.key}><summary>{t.label}</summary><p>{t.explanation}</p><p>Глава {t.chapter} НК РФ. <a href={t.source_url} target="_blank" rel="noreferrer">Разъяснения ФНС ↗</a></p></details>)}</section>)}</div>
 <details className="budgetSpecialRegimes"><summary>Специальные налоговые режимы</summary><ul>{catalog.special_regimes.map(r=><li key={r.label}>{r.label} · {r.chapter}</li>)}</ul><p>{catalog.note}</p></details>
 </div></details>
 <section className="surface budgetRegions"><header><div><small>89 РЕГИОНАЛЬНЫХ СЦЕНАРИЕВ</small><h2>Бюджетная карта</h2></div><nav aria-label="Вид регионов"><button type="button" aria-pressed={mode==='map'} onClick={()=>setMode('map')}><MapIcon size={18}/> Карта</button><button type="button" aria-pressed={mode==='table'} onClick={()=>setMode('table')}><List size={18}/> Таблица</button></nav></header>
 <div className="budgetRegionToolbar"><label><Search size={18}/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Найти регион" aria-label="Поиск региона"/></label><StyledSelect label="Регион" value={selected} onChange={setSelected} options={regions.map(r=>({value:r.region_code,label:r.name}))}/><StyledSelect label="Порядок" value={sort} onChange={setSort} options={[{value:'name',label:'По названию'},{value:'enterprises',label:'По предприятиям'},{value:'balance',label:'По балансу'}]}/></div>
 <div className="budgetRegionSplit"><div className="budgetMapPanel">
 {mode==='map'?<><nav className="budgetMapZoom" aria-label="Масштаб карты">{[['all','Вся страна'],['west','Европейская часть'],['selected','Выбранный регион']].map(([key,label])=><button type="button" key={key} aria-pressed={mapZoom===key} onClick={()=>setMapZoom(key)}>{label}</button>)}<button type="button" onClick={()=>{setSelected('91');setMapZoom('selected')}}>Крым</button><button type="button" onClick={()=>{setSelected('92');setMapZoom('selected')}}>Севастополь</button></nav><svg className="budgetMap" viewBox={mapViewport(mapZoom,selected)} role="group" aria-label="Регионы: выберите область на карте">{mapData.paths.map(p=>{const r=regions.find(x=>x.region_code===p.code);if(!r)return null;const f=fiscalForecast(r,rates,undefined,context);return <path key={p.code} d={p.path} tabIndex={0} role="button" aria-label={r.name+', баланс '+money(f.balance)+' млн рублей'} aria-pressed={selected===p.code} fill={selected===p.code?'#c2438a':f.balance>=0?'#75c6ac':'#b8c9e8'} stroke={selected===p.code?'#822759':'#fff'} strokeWidth={selected===p.code?2:1} onClick={()=>setSelected(p.code)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(p.code)}}}><title>{r.name}</title></path>})}</svg><div className="budgetMapLegend"><span><i style={{background:'#75c6ac'}}/> Профицит</span><span><i style={{background:'#b8c9e8'}}/> Дефицит</span><span><i style={{background:'#c2438a'}}/> Выбранный регион</span></div><p className="budgetMapSource">Карта региональных бюджетов · 89 субъектов, включая Республику Крым и Севастополь. Подробные значения доступны также в таблице. Геометрия: <a href="https://www.geoboundaries.org/" target="_blank" rel="noreferrer">geoBoundaries / OpenStreetMap, ODbL 1.0 ↗</a></p></>:<div className="budgetTableWrap"><table><thead><tr><th>Регион</th><th>Предприятия, шт.</th><th>Доходы, млн ₽</th><th>Расходы, млн ₽</th><th>Баланс, млн ₽</th></tr></thead><tbody>{filtered.map(r=>{const f=fiscalForecast(r,rates,undefined,context);return <tr key={r.region_code} className={r.region_code===selected?'selected':''}><th><button type="button" onClick={()=>setSelected(r.region_code)}>{r.name}</button></th><td>{money(r.enterprises)}</td><td>{money(f.revenue)}</td><td>{money(f.expenditure)}</td><td>{money(f.balance)}</td></tr>})}</tbody></table></div>}
 </div>
 {region&&forecast&&<aside className="budgetRegionDetail"><header><Landmark size={24}/><div><small>{profileLabel[region.profile]} · учебный профиль</small><h3>{region.name}</h3></div></header>
 <dl>{[['Доходы',forecast.revenue],['Расходы',forecast.expenditure],['Баланс',forecast.balance],['Трансферты',region.transfer_in],['Расчётный долг',forecast.debt],['Рабочие места',forecast.employees]].map(([label,v])=><div key={String(label)}><dt>{label}</dt><dd>{money(Number(v))}{label==='Рабочие места'?' мест':' млн ₽'}</dd></div>)}</dl>
 <details><summary>Реальная региональная статистика · 2025</summary><p>Налоговые поступления по данным ФНС. Это часть доходов, не весь бюджет региона. Местные суммы уже входят в консолидированные.</p>{Object.entries(region.observations||{}).map(([key,v])=><p key={key}>{({tax_receipts_total:'Поступления ФНС, всего',tax_receipts_federal:'Из них в федеральный бюджет',tax_receipts_consolidated:'В консолидированный бюджет субъекта',tax_receipts_local:'Из него в местные бюджеты',usn_receipts:'Поступления по УСН'} as Record<string,string>)[key]||key}: <b>{v===null?'Нет сопоставимого наблюдения':money(v)+' млн ₽'}</b></p>)}<a href={region.source_url} target="_blank" rel="noreferrer">ФНС, форма 1-НМ · {region.source_year} ↗</a></details>
 <details className="budgetTaxLines"><summary>Из чего складываются налоговые доходы</summary><div className="budgetTableWrap"><table><thead><tr><th>Налог</th><th>База</th><th>Ставка</th><th>Поступления</th></tr></thead><tbody>{forecast.lines.map(t=><tr key={t.key}><th>{t.label}</th><td>{t.base===null?'Не задана':quantity(t.base,t.base_key==='horsepower'?'л. с.':'млн ₽')}</td><td>{t.rate===null?'Специальная формула':money(t.rate)+' '+t.unit}</td><td>{t.amount===null?'Нужна отдельная база':money(t.amount)+' млн ₽'}</td></tr>)}</tbody></table></div><p>Суммарный прогноз включает только строки с заданной базой. Остальные платежи изучаются в справочнике и кейсах.</p></details><h4>Региональные правовые задачи</h4>{regionCases.length?regionCases.slice(0,8).map(c=><button type="button" className="budgetCaseLink" key={c.id} disabled={readOnly||busy||g.me?.kind!=='student'||(!c.assigned&&c.status!=='ready')} onClick={()=>void practice(c)}><FileText size={17}/><span>{c.title}{c.status==='resolved'?' · Решено':c.status==='voting'?' · Голосуют':''}</span><ArrowRight size={17}/></button>):<p>Задачи региона появятся после обновления банка.</p>}
 </aside>}
 </div></section>
 {region&&forecast&&<section className="surface budgetRateLab"><header><div><small>НАЛОГОВАЯ ПОЛИТИКА</small><h2>Ставка и её последствия</h2></div><Coins size={24}/></header>
 <div className="budgetRateFields"><StyledSelect label="Налог и база" value={taxKey} onChange={setTaxKey} options={catalog.taxes.filter(t=>t.default_rate!==null).map(t=>({value:t.key,label:t.label}))}/><label>Предлагаемая ставка, {tax.unit}<input type="number" step=".1" min={tax.min_rate??0} max={tax.max_rate??100} value={rate} onChange={e=>setRate(e.target.value)}/></label><button type="button" className="primary" disabled={busy||readOnly||!canPropose||!rate} onClick={()=>void propose()}>Направить предложение</button></div>
 <p>{tax.explanation}</p><div className="budgetPreviewComparison"><div><span>Текущие доходы региона</span><b>{money(forecast.revenue)} млн ₽</b></div><div><span>Если ставка будет принята</span><b>{money(preview?.revenue??null)} млн ₽</b></div><div><span>Активность следующего периода</span><b>{preview?money(preview.nextActivity*100)+'%':'—'}</b></div></div>
 <p>Расчёт предложения виден всем. Исполнительная власть подготавливает изменение; правовую форму и принятие проверяют участники процедуры. Прогноз не меняет действующий бюджет.</p>
 {proposals.filter(p=>p.region_code===selected||p.region_code==='00').slice(0,12).map(p=><article className="budgetProposal" key={p.id}><div><b>{catalog.taxes.find(t=>t.key===p.tax_key)?.label}: {quantity(p.new_rate,catalog.taxes.find(t=>t.key===p.tax_key)?.unit||'%')}</b><span>{p.status==='applied'?'Введена актом':'Ожидает принятия акта'}</span></div>{p.document_id&&<button type="button" onClick={()=>onOpenDocument(p.document_id!)}>Проект НПА</button>}{g.teacher&&p.status==='pending'&&!readOnly&&<button type="button" disabled={busy} onClick={()=>void apply(p.id)}>Проверить и применить</button>}</article>)}
 {g.teacher&&!readOnly&&<StyledSelect label="Опубликованный акт для подтверждения меры" value={act} onChange={setAct} options={[{value:'',label:'Использовать связанный акт'},...g.formalDocuments.filter(d=>d.status_code==='published').map(d=>({value:d.id,label:d.registry_no+' · '+d.title}))]}/>}
 </section>}
 {g.teacher&&region&&!readOnly&&<details className="surface budgetParameters"><summary>Параметры экономического сценария · преподаватель</summary><p>Только эти параметры определяют экономическую и финансовую основу; студенты изменяют налоговую политику через предложения.</p><div>{Object.entries(parameters).map(([key,v])=><label key={key}>{({enterprises:'Предприятия, шт.',employees_per_firm:'Работников на предприятие',monthly_wage:'Зарплата, ₽/месяц',profit_per_firm:'Прибыль на предприятие, млн ₽',consumption_per_firm:'Облагаемая добавленная стоимость, млн ₽',expenditure:'Обязательства, млн ₽',transfer_in:'Трансферты, млн ₽',debt:'Исходный долг, млн ₽',compliance:'Собираемость, 0–1'} as Record<string,string>)[key]}<input type="number" step="any" min="0" value={v} onChange={e=>setParameters(old=>({...old,[key]:e.target.value}))}/></label>)}</div><button type="button" className="primary" disabled={busy} onClick={()=>void saveParameters()}><Save size={18}/> Сохранить параметры</button></details>}
 <section className="surface budgetChangeLog"><h2>Движение бюджета</h2>{ledger.length?ledger.map(x=><article key={x.id}><time>{new Date(x.created_at).toLocaleString('ru-RU')}</time><div><b>{x.note}</b><span>{regions.find(r=>r.region_code===x.region_code)?.name||'Федеральный уровень'}</span></div></article>):<p>Налоговые меры, изменения сценария и исходы кейсов будут записаны здесь с источником.</p>}</section>
 </>}
 {notice&&<p className="budgetNotice" role="status">{notice}</p>}
 </div>;
}
