'use client';
import {useState} from 'react';
import {Check,Plus,Trash2} from 'lucide-react';
import baseline from '@/data/federal-budget-2026.json';
import {moneyMillions} from '@/lib/formatQuantity';
import {programMoney} from './stateProgramModel';
import StyledSelect from '../ui/StyledSelect';
import {budgetDisplay,budgetMoney,transferLabels,type BudgetCalculation,type BudgetDraft,type BudgetExpenseItem,type BudgetTransfer} from './federalBudgetMath';
import styles from './FederalBudgetSimulator.module.css';
export type BudgetProgramExpense={indicator_name:string;justification:string;amount:string;budget_year:number;component_title:string};
export type SignedBudgetProgram={id:string;title:string;ministry:string;total_budget:number|string;program_status:string;signed_at:string;indicators?:string;expense_breakdown?:BudgetProgramExpense[];years:{year:number;amount:number|string;status:'planned'|'approved'|'rejected'}[]};
const num=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
const millions=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:8}).format(n);
const expenseSections=baseline.expense_lines.filter(l=>l.key!=='13');
export default function BudgetExpenses({draft,calculation:c,requests,programs,readOnly,canPrepare,onEdit,onOpenDocument,onOpenPrograms}:{draft:BudgetDraft;calculation:BudgetCalculation;requests:BudgetTransfer[];programs:SignedBudgetProgram[];readOnly:boolean;canPrepare:boolean;onEdit:(change:Partial<BudgetDraft>)=>void;onOpenDocument:(id:string)=>void;onOpenPrograms?:()=>void}){
 const [title,setTitle]=useState(''),[indicator,setIndicator]=useState(''),[justification,setJustification]=useState(''),[amount,setAmount]=useState(''),[section,setSection]=useState('04'),[error,setError]=useState('');
 const [programSections,setProgramSections]=useState<Record<string,string>>({});
 const items=draft.expense_items??[],canWrite=canPrepare&&!readOnly;
 function addItem(){
  const raw=amount.trim().replace(',','.');
  if(title.trim().length<3||indicator.trim().length<3||justification.trim().length<10||!/^\d+(\.\d{1,2})?$/.test(raw)||Number(raw)<=0||Number(raw)>1e12){setError('Укажите мероприятие, показатель результата, обоснование и положительную сумму в рублях (не более двух знаков после запятой).');return;}
  const item:BudgetExpenseItem={id:crypto.randomUUID(),section_key:section,title:title.trim(),indicator:indicator.trim(),justification:justification.trim(),amount:Math.round(Number(raw)*100)/1e8,budget_year:2026};
  onEdit({expense_items:[...items,item]});setTitle('');setIndicator('');setJustification('');setAmount('');setError('');
 }
 function addProgram(p:SignedBudgetProgram,annual:SignedBudgetProgram['years'][number]){
  const chosen=programSections[p.id];if(!chosen)return;
  onEdit({expense_items:[...items,{id:crypto.randomUUID(),section_key:chosen,title:p.title,indicator:(p.indicators||'Результаты и показатели утверждённой государственной программы').slice(0,500),justification:'Финансирование на '+annual.year+' год по подписанной Председателем Правительства и принятой Правительством государственной программе. Ответственный исполнитель: '+p.ministry,amount:budgetMoney(Number(annual.amount)/1e6),program_id:p.id,budget_year:annual.year}]});
 }
 return <div className={styles.panel}>
  <h3>3. Утвердите расходы проекта</h3>
  <p>Базовые обязательства уже входят в исходный план. Новые мероприятия, годовые ассигнования госпрограмм и выбранные региональные заявки добавляются к нему отдельными строками. Система складывает их один раз.</p>
  <p className={styles.scrollHint}>Прокрутите таблицу вправо, чтобы увидеть составляющие и итог каждого раздела.</p><div className={styles.tableWrap} tabIndex={0} aria-label="Таблица расходов: можно прокручивать по горизонтали"><table className={styles.dataTable}>
   <caption>Расходы по разделам · суммы в рублях, миллиардах и триллионах</caption><thead><tr><th scope="col">Раздел и назначение</th><th scope="col">Базовые обязательства</th><th scope="col">Программы и мероприятия</th><th scope="col">Трансферты / проценты</th><th scope="col">Всего</th></tr></thead>
   <tbody>{c.expense_lines.map(l=><tr key={l.key} data-budget-expense={l.key}><th scope="row"><b>{l.key}. {l.label}</b><small>{baseline.expense_lines.find(x=>x.key===l.key)?.explanation}</small></th><td className={styles.numeric}>{budgetDisplay(l.base_amount??l.baseline)}{Boolean(l.base_reallocation_amount)&&<small>Поправки II чтения: {(l.base_reallocation_amount??0)>0?'+':''}{num((l.base_reallocation_amount??0)*1e6)} ₽</small>}</td><td className={styles.numeric}>{budgetDisplay(l.items_amount??0)}</td><td className={styles.numeric}>{budgetDisplay((l.transfer_amount??0)+(l.interest_amount??0))}</td><td className={styles.numeric}><strong>{budgetDisplay(l.amount)}</strong></td></tr>)}</tbody>
   <tfoot><tr><th scope="row" colSpan={4}>Разница округления исходного плана</th><td className={styles.numeric}>{budgetDisplay(baseline.expense_rounding)}</td></tr><tr><th scope="row" colSpan={4}>Всего расходов</th><td className={styles.numeric} data-budget-expense-total={c.expenditure}>{budgetDisplay(c.expenditure)}</td></tr></tfoot>
  </table></div>
  <details className={styles.requestForm}><summary>Изменить объём базовых обязательств</summary><p>Изменение применяется к базовому плану выбранного раздела. Суммы госпрограмм и заявок не масштабируются этим процентом. Проценты по долгу рассчитываются на шаге «Баланс».</p><div className={styles.fields}>{baseline.expense_lines.map(l=><label key={l.key}>Изменение расходов: {l.label}, %<input type="number" min={-80} max={200} step={1} value={draft.spending_changes[l.key]??0} disabled={readOnly} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))onEdit({spending_changes:{...draft.spending_changes,[l.key]:e.target.valueAsNumber}});}}/></label>)}</div></details>
  <section className={styles.expenseSection} aria-label="Государственные программы в расходах"><div className={styles.sectionHead}><div><h4>Государственные программы · 2026</h4><p>Подпись Председателя Правительства добавляет программу в планирование. Для включения ассигнований в проект требуется решение Правительства.</p></div>{onOpenPrograms&&<button type="button" className="secondary" onClick={onOpenPrograms}>Открыть программы</button>}</div>
   {programs.length===0?<p>Подписанных госпрограмм пока нет.</p>:programs.map(p=>{
    const annual=p.years.find(y=>y.year===2026),included=items.some(i=>i.program_id===p.id&&i.budget_year===2026);
    return <article key={p.id} className={styles.programRow}><div><b>{p.title}</b><small>{p.ministry}</small><p>{annual?programMoney(annual.amount)+' ₽ на 2026 год':'На 2026 год финансирование не предусмотрено'}</p><small>{included?'Включена в расходы проекта':annual?.status==='approved'?'Программа принята · выберите раздел расходов':annual?.status==='rejected'?'Программа отклонена Правительством':'Ожидает решения Правительства'}</small>{!!p.expense_breakdown?.length&&<details><summary>Расходы и показатели подписанной программы</summary>{p.indicators&&<p>{p.indicators}</p>}<div className={styles.tableWrap} tabIndex={0}><table className={styles.dataTable}><caption>Расходы госпрограммы на 2026 год · ₽</caption><thead><tr><th scope="col">Элемент программы</th><th scope="col">Что финансируется</th><th scope="col">Обоснование</th><th scope="col">Сумма, ₽</th></tr></thead><tbody>{p.expense_breakdown.map((e,i)=><tr key={i}><th scope="row">{e.component_title}</th><td>{e.indicator_name}</td><td>{e.justification}</td><td className={styles.numeric}>{programMoney(e.amount)}</td></tr>)}</tbody></table></div></details>}</div>{annual?.status==='approved'&&Number(annual.amount)>0&&!included&&<div className={styles.programActions}><StyledSelect label={'Раздел расходов: '+p.title} value={programSections[p.id]??''} onChange={value=>setProgramSections(v=>({...v,[p.id]:value}))} options={[{value:'',label:'Выберите раздел'},...expenseSections.filter(l=>l.key!=='14').map(l=>({value:l.key,label:l.label}))]} disabled={!canWrite}/><button type="button" className="secondary" disabled={!canWrite||!programSections[p.id]} onClick={()=>addProgram(p,annual)}><Plus size={17}/> Включить программу</button></div>}</article>;
   })}
  </section>
  <section className={styles.expenseSection} aria-label="Подробные мероприятия расходов"><h4>Новые мероприятия и включённые программы</h4><p>У каждого расхода должны быть назначение, измеримый результат и обоснование. Суммы ниже вводятся в рублях и автоматически переводятся в расчёт бюджета.</p>
   {items.length>0&&<div className={styles.tableWrap} tabIndex={0} aria-label="Таблица мероприятий расходов"><table className={styles.dataTable}><caption>Дополнительные расходы · ₽</caption><thead><tr><th scope="col">Мероприятие / раздел</th><th scope="col">Показатель результата</th><th scope="col">Обоснование</th><th scope="col">Сумма, ₽</th><th scope="col">Действие</th></tr></thead><tbody>{items.map(i=><tr key={i.id} data-budget-expense-item={i.id}><th scope="row"><b>{i.title}</b><small>{i.section_key}. {baseline.expense_lines.find(l=>l.key===i.section_key)?.label}</small></th><td>{i.indicator}</td><td>{i.justification}</td><td className={styles.numeric}>{num(i.amount*1e6)}</td><td><button type="button" className="secondary" aria-label={'Удалить расход: '+i.title} disabled={!canWrite} onClick={()=>onEdit({expense_items:items.filter(x=>x.id!==i.id)})}><Trash2 size={17}/></button></td></tr>)}</tbody><tfoot><tr><th scope="row" colSpan={3}>Всего дополнительных мероприятий</th><td className={styles.numeric}>{num(items.reduce((sum,i)=>sum+i.amount,0)*1e6)}</td><td/></tr></tfoot></table></div>}
   <details className={styles.requestForm}><summary><Plus size={18}/> Добавить расходное мероприятие</summary><div className={styles.fields}><label>Название мероприятия<input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)} disabled={!canWrite}/></label><StyledSelect label="Раздел нового расхода" value={section} onChange={setSection} options={expenseSections.map(l=>({value:l.key,label:l.label}))} disabled={!canWrite}/><label>Показатель и ожидаемый результат<input value={indicator} maxLength={500} onChange={e=>setIndicator(e.target.value)} placeholder="Например: введено 120 новых школьных мест" disabled={!canWrite}/></label><label>Сумма нового расхода, ₽<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="15000000,00" disabled={!canWrite}/></label></div><label>Обоснование нового расхода<textarea rows={3} value={justification} maxLength={4000} onChange={e=>setJustification(e.target.value)} disabled={!canWrite}/></label><button type="button" className="secondary" onClick={addItem} disabled={!canWrite||items.length>=100}><Plus size={17}/> Добавить в расходы</button>{error&&<p role="alert" className={styles.inlineError}>{error}</p>}</details>
  </section>
  <section className={styles.expenseSection} aria-label="Рассмотрение региональных заявок"><h4>Региональные заявки на финансирование</h4><p>Проверьте основание и ожидаемый результат, затем включите выбранные заявки в проект. Целевые трансферты входят в отраслевой раздел, дотации — в раздел 14. Бюджетный кредит увеличивает потребность в финансировании и учитывается отдельно от расходов.</p><div className={styles.requests}>{requests.length?requests.map(r=>{
   const included=draft.transfer_ids.includes(r.id);
   return <article key={r.id} data-budget-request={r.id}><header><span><b>{r.region_name}</b><small>{transferLabels[r.kind]} · {r.status==='granted'?'Уже предоставлено':r.status==='rejected'?'Отклонено':included?'Включено в проект':'Ожидает решения по расходам'}</small></span><strong>{moneyMillions(r.amount)}</strong></header><p><b>Основание:</b> {r.event_title||'Ранее поданная региональная заявка'}</p><p>{r.purpose}</p>{r.expected_result&&<p><b>Ожидаемый результат:</b> {r.expected_result}</p>}{r.kind==='subsidy'&&<p>Софинансирование региона: {moneyMillions(r.cofinancing)}</p>}<div className={styles.actions}>{r.status!=='granted'&&r.status!=='rejected'&&<button type="button" className={included?'primary':'secondary'} disabled={!canWrite} aria-pressed={included} onClick={()=>onEdit({transfer_ids:included?draft.transfer_ids.filter(id=>id!==r.id):[...draft.transfer_ids,r.id]})}>{included?<Check size={18}/>:<Plus size={18}/>} {included?'Исключить из расходов':'Включить в расходы'}</button>}{r.document_id&&<button type="button" className="secondary" onClick={()=>onOpenDocument(r.document_id!)}>Открыть закон</button>}</div></article>;
  }):<p>Подготовьте заявку на шаге «Регионы»: выберите событие и обоснуйте потребность в средствах.</p>}</div></section>
 </div>;
}
