'use client';
import {Calculator,FileText,Vote} from 'lucide-react';
import type {FormalDocument} from './types';
import {billions,transferLabels,type BudgetCalculation} from './federalBudgetMath';
import styles from './BudgetDocumentAnnex.module.css';
import {programMoney} from './stateProgramModel';
type AmendmentAnnex={id:string;title:string;party_name:string;reason:string;amount:number;from_section:string;to_section:string;applied_revision:number;vote_id:string;yes:number;no:number;abstain:number};
const num=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
export default function BudgetDocumentAnnex({document,onOpenBudget,onOpenVotes}:{document:FormalDocument;onOpenBudget?:()=>void;onOpenVotes?:(id:string)=>void}){
 const c=document.metadata?.budget_snapshot as BudgetCalculation|undefined;
 if(!document.metadata?.budget_simulator_plan_id||!c||!Array.isArray(c.income_lines)||!Array.isArray(c.expense_lines))return null;
 const amendments=Array.isArray(document.metadata.budget_amendments)?document.metadata.budget_amendments as AmendmentAnnex[]:[];
 return <section className={styles.annex} aria-label="Расчётные приложения к бюджету"><header><div><FileText size={19}/><b>Числовые приложения к проекту</b></div>{onOpenBudget&&<button type="button" className="secondary" onClick={onOpenBudget}><Calculator size={18}/> Открыть расчёт бюджета</button>}</header><p>Приложения закрепляют расчёт, с которым рассматривается этот проект ФЗ. Здесь видны его доходные базы, расходы и региональные заявки. Изменение пояснений не меняет суммы: новую редакцию готовят через раздел «Бюджет».</p>
  <dl>{[['Доходы',c.revenue],['Расходы',c.expenditure],['Дефицит',c.deficit],['Источники финансирования',c.financing]].map(([label,n])=><div key={String(label)}><dt>{String(label)}</dt><dd>{billions(Number(n))}</dd></div>)}</dl>
  {!!c.income_details?.length&&<details><summary>Приложение 1. Ставки, базы и статьи доходов</summary><div className={styles.tableWrap} tabIndex={0}><table className={styles.table}><caption>Денежные базы и доходы · млн ₽</caption><thead><tr><th scope="col">Статья</th><th scope="col">Ставка</th><th scope="col">База</th><th scope="col">Собираемость / доля ФБ</th><th scope="col">Доход</th></tr></thead><tbody>{c.income_details.map(l=><tr key={l.key}><th scope="row">{l.label}<small>{l.model_rate?'Учебный коэффициент':'Действующая игровая ставка'}</small></th><td className={styles.numeric}>{num(l.rate)}{l.rate_unit==='rubles'?' ₽ / ед.':'%'}</td><td className={styles.numeric}>{num(l.base)}<small>{l.base_unit==='units'?'Условных единиц':'млн ₽'}</small></td><td className={styles.numeric}>{num(l.collection*100)}% / {num(l.federal_share*100)}%</td><td className={styles.numeric}>{num(l.amount)}</td></tr>)}</tbody></table></div></details>}
  <details><summary>Приложение 2. Доходы по группам и расходы по разделам</summary>{[['Доходы',c.income_lines],['Расходы',c.expense_lines]].map(([title,rows])=><div key={String(title)}><h4>{String(title)}</h4><ul>{(rows as BudgetCalculation['income_lines']).map(l=><li key={l.key}><span>{l.label}</span><b>{billions(l.amount)}</b></li>)}</ul></div>)}<p>Разница округления доходов: +0,2 млрд ₽; расходов: −0,1 млрд ₽. Доходные последствия событий: {num(c.revenue_adjustment??0)} млн ₽; они учтены в итоговой сумме. Проценты по долгу входят в расходы, основной долг — в финансирование.</p></details>
  {!!c.expense_items?.length&&<details><summary>Приложение 3. Государственные программы и мероприятия</summary><div className={styles.tableWrap} tabIndex={0}><table className={styles.table}><caption>Подробные ассигнования · ₽</caption><thead><tr><th scope="col">Мероприятие / раздел</th><th scope="col">Показатель результата</th><th scope="col">Обоснование</th><th scope="col">Сумма, ₽</th></tr></thead><tbody>{c.expense_items.map(i=><tr key={i.id}><th scope="row">{i.title}<small>Раздел {i.section_key} · {i.budget_year||2026} год</small></th><td>{i.indicator}</td><td>{i.justification}</td><td className={styles.numeric}>{num(i.amount*1e6)}</td></tr>)}</tbody></table></div>{c.program_expenses?.map(p=><div key={p.program_id}><h4>{p.title}: расходы подписанной госпрограммы</h4><p>{p.indicators}</p><div className={styles.tableWrap} tabIndex={0}><table className={styles.table}><caption>Подписанная смета госпрограммы на 2026 год · ₽</caption><thead><tr><th scope="col">Элемент программы</th><th scope="col">Что финансируется</th><th scope="col">Обоснование</th><th scope="col">Сумма, ₽</th></tr></thead><tbody>{p.expense_breakdown.map((e,i)=><tr key={i}><th scope="row">{e.component_title}</th><td>{e.indicator_name}</td><td>{e.justification}</td><td className={styles.numeric}>{programMoney(e.amount)}</td></tr>)}</tbody></table></div></div>)}</details>}
  {!!c.transfer_requests?.length&&<details><summary>Приложение 4. Утверждаемые региональные заявки</summary>{c.transfer_requests.map(r=><article key={r.id} className={styles.transfer}><b>{r.region_name} · {transferLabels[r.kind]}</b><p><b>Основание:</b> {r.event_title||'Региональная заявка'}</p><p>{r.purpose}</p>{r.expected_result&&<p><b>Результат:</b> {r.expected_result}</p>}<p>Из федерального бюджета: <b>{num(r.amount*1e6)} ₽</b> · Софинансирование региона: <b>{num(r.cofinancing*1e6)} ₽</b> · Раздел {r.section_key}</p></article>)}<p>Включение в приложение утверждает план. Исполнение происходит после опубликования закона; повторного перечисления ранее предоставленной заявки нет.</p></details>}
  {amendments.length>0&&<details className={styles.amendments}><summary>История предложений к расчёту · {amendments.length} шт.</summary><p>Здесь сохранены предложения, включённые при подготовке расчёта. Второе чтение и голосование за поправки к проекту проводятся отдельно на заседании ГД.</p>{amendments.map(a=><article key={a.id}><small>{a.party_name} · Включена в редакцию {a.applied_revision}</small><h4>{a.title}</h4><p>{a.reason}</p><b>{c.expense_lines.find(l=>l.key===a.from_section)?.label||a.from_section} → {c.expense_lines.find(l=>l.key===a.to_section)?.label||a.to_section} · {billions(a.amount)}</b><p>За: {a.yes??0} мандатов · Против: {a.no??0} · Воздержались: {a.abstain??0}</p>{onOpenVotes&&a.vote_id&&<button type="button" className="secondary" onClick={()=>onOpenVotes(a.vote_id)}><Vote size={18}/> Результат предварительного голосования</button>}</article>)}</details>}
 </section>;
}
