'use client';
import {useRef,useState} from 'react';
import {Map as MapIcon,List,Play,Send} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {userError} from '@/lib/userError';
import {moneyMillions} from '@/lib/formatQuantity';
import mapData from '@/data/region-paths.json';
import baseline from '@/data/federal-budget-2026.json';
import StyledSelect from '../ui/StyledSelect';
import {fiscalForecast,type FiscalContext,type FiscalRate,type FiscalRegion} from './fiscalMath';
import {transferLabels,type BudgetDraft,type BudgetTransfer} from './federalBudgetMath';
import styles from './FederalBudgetSimulator.module.css';
export type BudgetRegionalEvent={id:string;title:string;situation:string;status:string;region_code:string;assigned:boolean;budget_request:{section_key:string;kind:BudgetTransfer['kind'];amount:number;cofinancing:number;expected_result:string;justification?:string;indicator?:{name:string;baseline:number;target:number;unit:string};estimate?:{name:string;amount:number}[]}};
const num=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
const rubles=(s:string)=>{const clean=s.trim().replace(',','.');return /^\d+(\.\d{1,2})?$/.test(clean)?Math.round(Number(clean)*100)/1e8:NaN;};
function viewport(code:string,zoom:boolean){
 if(!zoom)return '0 0 1040 600';const path=mapData.paths.find(p=>p.code===code);if(!path)return '0 0 1040 600';
 const points=[...path.path.matchAll(/[ML](-?[\d.]+),(-?[\d.]+)/g)].map(m=>[Number(m[1]),Number(m[2])]);if(!points.length)return '0 0 1040 600';
 const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return [Math.min(...xs)-12,Math.min(...ys)-12,Math.max(45,Math.max(...xs)-Math.min(...xs)+24),Math.max(45,Math.max(...ys)-Math.min(...ys)+24)].join(' ');
}
export default function BudgetRegionWorkspace({gameId,regions,rates,context,events,requests,draft,readOnly,canRequest,onSaved,onOpenEvents,onOpenExpenses,onReturnCredit}:{gameId:string;regions:FiscalRegion[];rates:FiscalRate[];context:FiscalContext|null;events:BudgetRegionalEvent[];requests:BudgetTransfer[];draft:BudgetDraft;readOnly:boolean;canRequest:boolean;onSaved:()=>Promise<void>;onOpenEvents:()=>void;onOpenExpenses:()=>void;onReturnCredit:(id:string)=>Promise<void>}){
 const [selected,setSelected]=useState('54'),[mode,setMode]=useState<'map'|'table'>('map'),[zoom,setZoom]=useState(false),[search,setSearch]=useState(''),[chosenId,setChosenId]=useState('');
 const [kind,setKind]=useState<BudgetTransfer['kind']>('subsidy'),[amount,setAmount]=useState(''),[cofinancing,setCofinancing]=useState(''),[purpose,setPurpose]=useState(''),[result,setResult]=useState(''),[section,setSection]=useState('04'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const form=useRef<HTMLElement>(null),firstInput=useRef<HTMLInputElement>(null);
 const region=regions.find(r=>r.region_code===selected)??regions[0],code=region?.region_code??selected,forecast=region?fiscalForecast(region,rates,undefined,context):null;
 const regionalRequests=requests.filter(r=>r.region_code===code),regionalEvents=events.filter(e=>e.region_code===code),chosen=events.find(e=>e.id===chosenId);
 const filtered=regions.filter(r=>r.name.toLocaleLowerCase('ru').includes(search.trim().toLocaleLowerCase('ru')));
 function chooseRegion(value:string){setSelected(value);setChosenId('');setError('');setNotice('');}
 function prepare(e:BudgetRegionalEvent){
  setChosenId(e.id);setKind(e.budget_request.kind);setAmount(String(e.budget_request.amount*1e6));setCofinancing(String(e.budget_request.cofinancing*1e6));setSection(e.budget_request.section_key);setPurpose(e.budget_request.justification||e.situation);setResult(e.budget_request.expected_result);setError('');setNotice('');
  requestAnimationFrame(()=>{form.current?.scrollIntoView({behavior:'smooth',block:'start'});firstInput.current?.focus({preventScroll:true});});
 }
 async function start(e:BudgetRegionalEvent){
  if(readOnly||!canRequest||busy)return;setBusy(true);setError('');
  try{const r=await supabase.rpc('start_regional_case',{p_case_id:e.id});if(r.error){setError(userError(r.error));return;}await onSaved();setNotice('Событие начато. Теперь можно подготовить обоснованную заявку региона.');}catch(e){setError(userError(e));}finally{setBusy(false);}
 }
 async function submit(){
  if(readOnly||!canRequest||busy||!chosen)return;
  const requested=rubles(amount),own=kind==='subsidy'?rubles(cofinancing):0;
  if(!Number.isFinite(requested)||requested<=0||requested>1e6||!Number.isFinite(own)||own<0||(kind==='subsidy'&&own<=0)||purpose.trim().length<30||result.trim().length<10){setError('Проверьте сумму в рублях, софинансирование, обоснование (от 30 символов) и ожидаемый результат (от 10 символов).');return;}
  setBusy(true);setError('');
  try{const r=await supabase.rpc('create_budget_event_transfer_request',{p_game_id:gameId,p_event_case_id:chosen.id,p_region:chosen.region_code,p_kind:kind,p_amount:requested,p_cofinancing:own,p_purpose:purpose.trim(),p_section:kind==='grant'?'14':section,p_expected_result:result.trim()});if(r.error){setError(userError(r.error));return;}setChosenId('');await onSaved();setNotice('Заявка сохранена. На шаге «Расходы» её можно включить в проект бюджета.');}catch(e){setError(userError(e));}finally{setBusy(false);}
 }
 return <div className={styles.panel}>
  <h3>2. Проверьте регионы и их заявки</h3><p>Выберите регион на карте или в таблице. Посмотрите его собственные доходы и события, требующие средств. Заявки рассматриваются на следующем шаге — в расходах федерального бюджета.</p>
  <div className={styles.regionToolbar}><label>Поиск региона<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Название региона"/></label><StyledSelect label="Регион" value={code} onChange={chooseRegion} options={filtered.map(r=>({value:r.region_code,label:r.name}))} wrap/><div className={styles.actions}><button type="button" className="secondary" aria-pressed={mode==='map'} onClick={()=>setMode('map')}><MapIcon size={18}/> Карта</button><button type="button" className="secondary" aria-pressed={mode==='table'} onClick={()=>setMode('table')}><List size={18}/> Таблица</button></div></div>
  {mode==='map'?<div className={styles.regionMap}><div className={styles.actions}><button type="button" className="secondary" aria-pressed={!zoom} onClick={()=>setZoom(false)}>Вся страна</button><button type="button" className="secondary" aria-pressed={zoom} onClick={()=>setZoom(true)}>Выбранный регион</button></div><svg viewBox={viewport(code,zoom)} role="group" aria-label="Бюджетная карта регионов">{mapData.paths.filter(p=>filtered.some(r=>r.region_code===p.code)).map(p=>{
   const r=regions.find(r=>r.region_code===p.code)!;const f=fiscalForecast(r,rates,undefined,context),pending=requests.filter(x=>x.region_code===p.code&&x.status==='requested').length;
   return <path key={p.code} d={p.path} role="button" tabIndex={0} aria-pressed={code===p.code} aria-label={r.name+': доходы '+moneyMillions(f.revenue)+', ожидающих заявок '+pending} fill={code===p.code?'#6558cf':pending?'#edc478':f.balance<0?'#c0cee8':'#75c6ac'} stroke="#fff" strokeWidth={code===p.code?2:1} onClick={e=>{chooseRegion(p.code);if(e.detail>0)e.currentTarget.blur();}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseRegion(p.code);}}}><title>{r.name} · Доходы {moneyMillions(f.revenue)} · Заявки {pending}</title></path>;
  })}</svg><div className={styles.mapLegend}><span><i style={{background:'#edc478'}}/> Есть заявки</span><span><i style={{background:'#c0cee8'}}/> Дефицит</span><span><i style={{background:'#75c6ac'}}/> Профицит</span><span><i style={{background:'#6558cf'}}/> Выбранный регион</span></div></div>:<div className={styles.tableWrap} tabIndex={0} aria-label="Таблица бюджетов регионов"><table className={styles.dataTable}><caption>Доходы, расходы и заявки регионов · млн ₽</caption><thead><tr><th scope="col">Регион</th><th scope="col">Собственные доходы</th><th scope="col">Полученные трансферты</th><th scope="col">Расходы</th><th scope="col">Заявки на рассмотрении</th></tr></thead><tbody>{filtered.map(r=>{const f=fiscalForecast(r,rates,undefined,context),pending=requests.filter(x=>x.region_code===r.region_code&&x.status==='requested');return <tr key={r.region_code}><th scope="row"><button type="button" className="secondary" aria-pressed={code===r.region_code} onClick={()=>chooseRegion(r.region_code)}>{r.name}</button></th><td className={styles.numeric}>{num(f.regionalTax)}</td><td className={styles.numeric}>{num(r.transfer_in)}</td><td className={styles.numeric}>{num(f.expenditure)}</td><td className={styles.numeric}>{pending.length} · {num(pending.reduce((sum,r)=>sum+r.amount,0))}</td></tr>;})}</tbody></table></div>}
  {region&&forecast&&<section className={styles.selectedRegion} aria-label="Бюджет выбранного региона"><h4>{region.name}</h4><div className={styles.comparison}><div><small>Собственные налоговые доходы</small><b>{moneyMillions(forecast.regionalTax)}</b></div><div><small>Расходы региона</small><b>{moneyMillions(forecast.expenditure)}</b></div><div><small>Полученные трансферты</small><b>{moneyMillions(region.transfer_in)}</b></div><div><small>Баланс с полученными трансфертами</small><b>{moneyMillions(forecast.balance)}</b></div></div><details className={styles.requestForm}><summary>Расчёт собственных доходов региона</summary><div className={styles.tableWrap} tabIndex={0} aria-label="Налоговые доходы выбранного региона"><table className={styles.dataTable}><caption>Налоговая база и зачисление в регион · млн ₽</caption><thead><tr><th scope="col">Налог</th><th scope="col">Ставка</th><th scope="col">База</th><th scope="col">Собираемость / доля региона</th><th scope="col">Доход региона</th></tr></thead><tbody>{forecast.lines.filter(l=>l.regional!==null&&(l.level==='regional'||l.key==='income'||l.key==='profit')).map(l=><tr key={l.key}><th scope="row">{l.label}</th><td className={styles.numeric}>{l.rate===null?'—':num(l.rate)+(l.key==='transport'?' ₽ / л. с.':'%')}</td><td className={styles.numeric}>{l.base===null?'—':num(l.base)}<small>{l.key==='transport'?'Лошадиных сил':'млн ₽'}</small></td><td className={styles.numeric}>{num(region.compliance*100)}% / {l.amount?num((l.regional??0)/l.amount*100):l.key==='income'?'85':l.key==='profit'?'68':'100'}%</td><td className={styles.numeric}>{num(l.regional??0)}</td></tr>)}</tbody><tfoot><tr><th colSpan={4} scope="row">Всего собственных налоговых доходов</th><td className={styles.numeric}>{num(forecast.regionalTax)}</td></tr></tfoot></table></div></details><p className={styles.rounding}>Региональные суммы — игровые сценарии. Региональные доходы не прибавляются повторно к федеральному бюджету. Новая заявка до опубликования закона не увеличивает полученные трансферты.</p></section>}
  <section className={styles.expenseSection} aria-label="Региональные события"><h4>События региона и основания расходов</h4><div className={styles.eventList}>{regionalEvents.length?regionalEvents.map(e=>{
   const submitted=requests.find(r=>r.event_case_id===e.id),active=e.assigned||e.status==='assigned'||e.status==='resolved';
   return <article key={e.id} data-budget-regional-event={e.id}><header><b>{e.title}</b><small>{submitted?'Заявка подана':active?'Событие начато':'Доступно для начала'}</small></header><p>{e.situation}</p><p><b>Запрос из федерального бюджета:</b> {moneyMillions(e.budget_request.amount)}. <b>Вклад региона:</b> {moneyMillions(e.budget_request.cofinancing)}.</p><p><b>Результат:</b> {e.budget_request.expected_result}</p><div className={styles.actions}>{!submitted&&(active?<button type="button" className="secondary" disabled={readOnly||!canRequest||busy} onClick={()=>prepare(e)}><Send size={18}/> Подготовить заявку</button>:<button type="button" className="secondary" disabled={readOnly||!canRequest||busy} onClick={()=>void start(e)}><Play size={18}/> Начать событие</button>)}{active&&<button type="button" className="secondary" onClick={onOpenEvents}>Открыть в событиях</button>}</div></article>;
  }):<p>Для этого региона пока нет событий с запросом средств. Выберите другой регион: каталог охватывает стройки, инфраструктуру, экономику и кризисы.</p>}</div></section>
  {chosen&&<section className={styles.requestForm} ref={form} aria-label="Заявка по региональному событию"><h4>Заявка: {chosen.title}</h4><p>Основание — начатое событие. Проверьте смету и сформулируйте проверяемый результат.</p>{chosen.budget_request.estimate?.length&&<div className={styles.tableWrap}><table className={styles.dataTable}><caption>Исходная смета события · ₽</caption><thead><tr><th scope="col">Работа / объект</th><th scope="col">Сумма, ₽</th></tr></thead><tbody>{chosen.budget_request.estimate.map((line,i)=><tr key={i}><th scope="row">{line.name}</th><td className={styles.numeric}>{num(line.amount*1e6)}</td></tr>)}</tbody><tfoot><tr><th scope="row">Всего</th><td className={styles.numeric}>{num(chosen.budget_request.estimate.reduce((sum,l)=>sum+l.amount,0)*1e6)}</td></tr></tfoot></table></div>}<div className={styles.fields}><label>Запрашиваемая сумма, ₽<input ref={firstInput} inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} disabled={readOnly||busy}/></label><StyledSelect label="Вид трансферта" value={kind} onChange={v=>setKind(v as BudgetTransfer['kind'])} options={Object.entries(transferLabels).map(([value,label])=>({value,label}))} disabled={readOnly||busy}/>{kind==='subsidy'&&<label>Софинансирование региона, ₽<input inputMode="decimal" value={cofinancing} onChange={e=>setCofinancing(e.target.value)} disabled={readOnly||busy}/></label>}{kind!=='grant'&&kind!=='budget_credit'&&<StyledSelect label="Раздел регионального расхода" value={section} onChange={setSection} options={baseline.expense_lines.filter(l=>l.key!=='13'&&l.key!=='14').map(l=>({value:l.key,label:l.label}))} disabled={readOnly||busy}/>}</div><label>Обоснование заявки<textarea rows={4} value={purpose} maxLength={10000} onChange={e=>setPurpose(e.target.value)} disabled={readOnly||busy}/></label><label>Ожидаемый результат заявки<textarea rows={2} value={result} maxLength={4000} onChange={e=>setResult(e.target.value)} disabled={readOnly||busy}/></label><div className={styles.actions}><button type="button" className="primary" onClick={()=>void submit()} disabled={readOnly||!canRequest||busy}><Send size={18}/> Направить заявку в расходы</button><button type="button" className="secondary" onClick={()=>setChosenId('')} disabled={busy}>Отменить</button></div></section>}
  <section className={styles.expenseSection}><h4>Заявки выбранного региона</h4>{regionalRequests.length?regionalRequests.map(r=><article key={r.id} className={styles.programRow}><div><b>{r.event_title||r.purpose}</b><small>{transferLabels[r.kind]} · {moneyMillions(r.amount)}</small><p>{r.status==='granted'?'Предоставлено по опубликованному закону':r.status==='rejected'?'Отклонено':draft.transfer_ids.includes(r.id)?'Выбрано в расходах проекта; ожидает принятия закона':'Ожидает рассмотрения на шаге «Расходы»'}</p></div>{r.kind==='budget_credit'&&r.status==='granted'&&<button type="button" className="secondary" disabled={readOnly||!canRequest||busy||!!r.repaid_at} onClick={()=>void onReturnCredit(r.id)}>{r.repaid_at?'Кредит возвращён':'Вернуть бюджетный кредит'}</button>}</article>):<p>Заявок этого региона пока нет.</p>}<button type="button" className="secondary" onClick={onOpenExpenses}>Перейти к рассмотрению расходов</button></section>
  {!canRequest&&<p className={styles.rounding}>Заявки оформляют уполномоченные представители регионов, Правительство и преподаватель. Остальным участникам доступны расчёты и рассмотрение.</p>}{error&&<p role="alert" className={styles.inlineError}>{error}</p>}{notice&&<p role="status" className={styles.inlineNotice}>{notice}</p>}
 </div>;
}
