'use client';
import {Calculator,FileText,Vote} from 'lucide-react';
import type {FormalDocument} from './types';
import type {BudgetCalculation} from './federalBudgetMath';
import {billions} from './federalBudgetMath';
import styles from './BudgetDocumentAnnex.module.css';
type AmendmentAnnex={id:string;title:string;party_name:string;reason:string;amount:number;from_section:string;to_section:string;applied_revision:number;vote_id:string;yes:number;no:number;abstain:number};
export default function BudgetDocumentAnnex({document,onOpenBudget,onOpenVotes}:{document:FormalDocument;onOpenBudget?:()=>void;onOpenVotes?:(id:string)=>void}){
 const c=document.metadata?.budget_snapshot as BudgetCalculation|undefined;
 if(!document.metadata?.budget_simulator_plan_id||!c||!Array.isArray(c.income_lines)||!Array.isArray(c.expense_lines))return null;
 const amendments=Array.isArray(document.metadata.budget_amendments)?document.metadata.budget_amendments as AmendmentAnnex[]:[];
 return <section className={styles.annex} aria-label="Расчетные приложения к бюджету"><header><div><FileText size={19}/><b>Числовые приложения к проекту</b></div>{onOpenBudget&&<button type="button" className="secondary" onClick={onOpenBudget}><Calculator size={18}/> Бюджетный калькулятор</button>}</header><p>Эти суммы сформированы из общего расчета и связаны с принятием бюджета. Пояснения можно редактировать здесь; изменение сумм оформляйте новой редакцией через калькулятор.</p><dl>{[['Доходы',c.revenue],['Расходы',c.expenditure],['Дефицит',c.deficit],['Источники финансирования',c.financing]].map(([label,n])=><div key={String(label)}><dt>{String(label)}</dt><dd>{billions(Number(n))}</dd></div>)}</dl><details><summary>Доходы и расходы по разделам</summary>{[['Доходы',c.income_lines],['Расходы',c.expense_lines]].map(([title,rows])=><div key={String(title)}><h4>{String(title)}</h4><ul>{(rows as BudgetCalculation['income_lines']).map(l=><li key={l.key}><span>{l.label}</span><b>{billions(l.amount)}</b></li>)}</ul></div>)}<p>Разница округления доходов: +0,2 млрд ₽; расходов: −0,1 млрд ₽. Долговые проценты входят в расходы, основной долг — в финансирование.</p></details>{amendments.length>0&&<details className={styles.amendments}><summary>История поправок к расчету · {amendments.length} шт.</summary><p>Здесь сохранены предложения, включенные при подготовке расчета. Итоговые суммы закреплены в числовых приложениях выше.</p>{amendments.map(a=><article key={a.id}><small>{a.party_name} · включена в редакцию {a.applied_revision}</small><h4>{a.title}</h4><p>{a.reason}</p><b>{c.expense_lines.find(l=>l.key===a.from_section)?.label||a.from_section} → {c.expense_lines.find(l=>l.key===a.to_section)?.label||a.to_section} · {billions(a.amount)}</b><p>За: {a.yes??0} мандатов · Против: {a.no??0} · Воздержались: {a.abstain??0}</p>{onOpenVotes&&a.vote_id&&<button type="button" className="secondary" onClick={()=>onOpenVotes(a.vote_id)}><Vote size={18}/> Результат предварительного голосования</button>}</article>)}</details>}</section>;
}
