'use client';
import baseline from '@/data/federal-budget-2026.json';
import type {BudgetCalculation,BudgetDraft,SimulatorState} from './federalBudgetMath';
import styles from './FederalBudgetSimulator.module.css';
const number=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
export default function BudgetIncomeTable({calculation:c,draft,state,readOnly,onEdit}:{calculation:BudgetCalculation;draft:BudgetDraft;state:SimulatorState;readOnly:boolean;onEdit:(change:Partial<BudgetDraft>)=>void}){
 return <div className={styles.panel}>
  <h3>1. Рассчитайте доходы</h3>
  <p>Для каждой статьи показаны ставка, текущая база и поступление в федеральный бюджет. База пересчитывается после игровых событий и принятых решений. Налоговая ставка берётся из действующего в игре налогового акта.</p>
  <div className={styles.formula}>Доход = Ставка × База × Собираемость × Доля федерального бюджета</div>
  <p className={styles.explanation}>Детализация исходного плана — учебная. «Учебная ставка» означает усреднённый коэффициент расчёта; для акцизов, сборов и специальных ставок он не заменяет налоговый справочник. Для неналоговых платежей 100% означает зачисление прогнозируемых выплат.</p>
  <p className={styles.scrollHint}>Прокрутите таблицу вправо, чтобы увидеть ставки, базы и суммы.</p><div className={styles.tableWrap} tabIndex={0} aria-label="Таблица доходов: можно прокручивать по горизонтали"><table className={styles.dataTable}>
   <caption>Доходы по статьям · денежные базы и доходы в млн ₽</caption>
   <thead><tr><th scope="col">Статья дохода</th><th scope="col">Ставка</th><th scope="col">Текущая база</th><th scope="col">Собираемость / доля ФБ</th><th scope="col">Доход</th></tr></thead>
   <tbody>{(c.income_details||[]).map(l=><tr key={l.key} data-budget-income-detail={l.key}><th scope="row"><b>{l.label}</b><small>{l.base_label}</small><details><summary>Что меняет базу</summary><p>{l.driver_note}. Коэффициент активности сейчас: {number(c.activity)}. Корректировка прогноза этой группы: {number(draft.income_changes[l.group_key]??0)}%.</p></details></th><td className={styles.numeric}><b>{number(l.rate)}{l.rate_unit==='rubles'?' ₽ / ед.':'%'}</b><small>{l.model_rate?'Учебная ставка':'Действующая в игре'}</small></td><td className={styles.numeric} title={String(l.base)} data-budget-base={l.base}><b>{number(l.base)}</b><small>{l.base_unit==='units'?'Условных единиц':'млн ₽'}</small></td><td className={styles.numeric}>{number(l.collection*100)}% / {number(l.federal_share*100)}%</td><td className={styles.numeric} data-budget-article-amount={l.amount}><strong>{number(l.amount)}</strong></td></tr>)}</tbody>
   <tfoot><tr><th scope="row" colSpan={4}>Разница округления исходного плана</th><td className={styles.numeric}>{number(baseline.income_rounding)}</td></tr><tr><th scope="row" colSpan={4}>Отдельные доходные последствия событий</th><td className={styles.numeric}>{number(state.revenue_adjustment)}</td></tr><tr><th scope="row" colSpan={4}>Всего доходов, млн ₽</th><td className={styles.numeric} data-budget-revenue-total={c.revenue}>{number(c.revenue)}</td></tr></tfoot>
  </table></div>
  <p className={styles.rounding}>Процентные ставки делятся на 100; рублёвые ставки сборов — на 1 000 000 для перевода результата в млн ₽. Отображаемые числа округлены, расчёт использует полные значения. Страховые взносы и заёмные средства в эти доходы не входят.</p>
  <details className={styles.requestForm}><summary>Обоснованные изменения прогнозной базы</summary><p>События уже учтены автоматически. Эти поля используйте для дополнительных прогнозных допущений: изменение относится только к выбранной группе. Укажите основание на шаге «Проект ФЗ».</p><div className={styles.fields}>{baseline.income_lines.map(l=><label key={l.key}>Изменение базы: {l.label}, %<input type="number" min={-80} max={200} step={.5} value={draft.income_changes[l.key]??0} disabled={readOnly} onChange={e=>{const value=e.target.valueAsNumber;if(Number.isFinite(value))onEdit({income_changes:{...draft.income_changes,[l.key]:value}});}}/>{!!draft.revenue_adjustments[l.key]&&<small>Ранее сохранённая отдельная поправка: {number(draft.revenue_adjustments[l.key])} млн ₽</small>}</label>)}</div></details>
 </div>;
}
