import type {ReturnTypeRepublic} from './viewTypes';

export default function DashboardView({g,onNavigate}:{g:ReturnTypeRepublic;onNavigate:(v:'actions')=>void}){
 const {game,me,metrics,events,members,parties,votes,actions,crises,currentStage,averageVsn,setChatOpen,chatOpen}=g;
 if(!game||!me)return null;
 return <><section className="dashHero"><div><small>НАЦИОНАЛЬНЫЙ СИТУАЦИОННЫЙ ЦЕНТР</small><h1>{currentStage?.title||'Республика Политология'}</h1><p>{currentStage?.summary||'Многопользовательская симуляция государственного и политико-административного управления.'}</p><div className="heroButtons"><button className="primary" disabled={!game.turn_open} onClick={()=>onNavigate('actions')}>Инициировать решение</button><button className="secondary" onClick={()=>setChatOpen(!chatOpen)}>{chatOpen?'Скрыть связь':'Открыть связь'}</button></div></div><div className="heroData"><div><span>Участники</span><b>{members.length}</b></div><div><span>Партии</span><b>{parties.length}</b></div><div><span>Открытые голосования</span><b>{votes.filter(v=>v.status==='open').length}</b></div><div><span>Мой ВСН</span><b>{averageVsn?averageVsn.toFixed(1):'—'}</b></div></div></section>
 <section className="metricDeck">{metrics.map(m=><article key={m.id}><span>{m.label}</span><strong>{m.value}{m.unit||''}</strong><div><i style={{width:`${Math.min(100,Math.max(5,Number(m.value)))}%`}}/></div></article>)}</section>
 <section className="dashGrid"><article className="surface"><div className="surfaceHead"><div><small>ОПЕРАТИВНАЯ ЛЕНТА</small><h2>События государства</h2></div><b>{events.length}</b></div><div className="eventStream">{events.length===0?<div className="emptyState">Событий пока нет.</div>:events.map(e=><div className={`streamItem ${e.severity}`} key={e.id}><div className="streamMeta"><time>{new Date(e.published_at).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time><span>{e.category}</span></div><h3>{e.title}</h3><p>{e.body}</p></div>)}</div></article>
 <article className="surface"><div className="surfaceHead"><div><small>МОЯ ПОЗИЦИЯ</small><h2>Игровой профиль</h2></div></div><div className="profileStats"><div><span>Роль</span><b>{me.role_title||me.kind}</b></div><div><span>Фракция</span><b>{me.team||'—'}</b></div><div><span>Решений</span><b>{actions.filter(a=>a.author_id===me.user_id).length}</b></div><div><span>Этап</span><b>{currentStage?.stage_no||game.current_round}/16</b></div></div>{crises[0]&&<div className="alertCard"><small>ПОСЛЕДНИЙ КРИЗИС</small><b>{crises[0].crisis_type}</b><p>{crises[0].description}</p></div>}</article></section></>
}