'use client';
import {useEffect,useState} from 'react';
import {Send,Signature} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import StyledSelect from '../ui/StyledSelect';
import DisclosureSummary from '../ui/DisclosureSummary';
import {ownerLabel} from './formalInstitutions';
import type {FormalDocument,Member} from './types';

export type DocumentAccess={can_edit:boolean;can_manage:boolean;can_sign:boolean;can_copy:boolean;vote_required:boolean;open_vote:boolean;next_owner:string|null;next_action:string|null};
const destinations=['president','gd','gd_staff','gd_council','committee','sf','government','ministry','municipality','teacher'];

export function DocumentTools({document:d,access,members,readOnly,onRefresh}:{document:FormalDocument;access:DocumentAccess|null;members:Member[];readOnly:boolean;onRefresh:()=>Promise<void>}){
 const [destination,setDestination]=useState('person'),[recipient,setRecipient]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{setMessage('');setError('');setDestination('person');setRecipient('');setNote('')},[d.id]);
 async function send(){if(busy)return;if(destination==='person'&&!recipient){setError('Выберите участника, которому нужно показать документ.');return}setBusy(true);setError('');setMessage('');const r=await supabase.rpc('send_formal_document',{p_document_id:d.id,p_destination:destination,p_recipient_id:recipient||null,p_note:note,p_move:false});if(r.error)setError(r.error.message);else{setMessage('Документ отправлен для ознакомления. Получателей: '+r.data+'. Стадия и официальный маршрут не изменились.');setRecipient('');setNote('');await onRefresh()}setBusy(false)}
 async function sign(){if(busy)return;setBusy(true);setError('');setMessage('');const r=await supabase.rpc('sign_formal_document',{p_document_id:d.id,p_note:note||null});if(r.error)setError(r.error.message);else{setMessage('Редакция подписана.');await onRefresh()}setBusy(false)}
 return <section className="documentTools" aria-label="Инструменты документа"><div className="documentToolsBar">{!readOnly&&access?.can_sign&&<button type="button" className="primary" disabled={busy} onClick={()=>void sign()}><Signature size={18}/> {busy?'Подписание…':'Подписать редакцию'}</button>}{access?.open_vote&&<span className="documentToolNotice">Текст зафиксирован до завершения голосования.</span>}</div>
 {!readOnly&&access?.can_copy&&<details className="projectDisclosure documentDelivery"><DisclosureSummary icon={Send} title="Отправить для ознакомления" description="Получатель увидит документ во входящих, но официальная процедура не изменится"/><div className="civicDisclosureBody documentDeliveryForm"><div className="documentCopyExplainer"><b>Только для ознакомления</b><span>Отправьте документ участнику или органу, чтобы он мог его прочитать и учесть в работе. Это не согласование, не утверждение и не официальный переход. Официальные действия выполняются в блоке управления процедурой справа от документа.</span></div><StyledSelect label="Кому показать документ" value={destination} onChange={v=>{setDestination(v);setRecipient('')}} options={[{value:'person',label:'Конкретному участнику'},...destinations.map(k=>({value:k,label:ownerLabel(k)}))]}/><StyledSelect label={destination==='person'?'Получатель':'Конкретный получатель (необязательно)'} value={recipient} onChange={setRecipient} options={[{value:'',label:destination==='person'?'Выберите участника':'Всем назначенным участникам органа'},...members.filter(m=>m.kind!=='observer').map(m=>({value:m.user_id,label:m.full_name+' · '+(m.role_title||'Участник')}))]}/><label className="documentDeliveryNote">Комментарий получателю<textarea rows={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Например: ознакомьтесь с проектом перед заседанием"/></label><p>Документ появится во входящих выбранного адресата как информационная копия. Ответственный орган, текущая стадия и официальный маршрут останутся прежними.</p><button type="button" className="primary" disabled={busy} onClick={()=>void send()}><Send size={18}/> {busy?'Отправляю…':'Отправить для ознакомления'}</button></div></details>}
 {error&&<p className="error documentToolError" role="alert">{error}</p>}{message&&<p className="documentToolSuccess" role="status">{message}</p>}</section>;
}

export function DocumentInbox({gameId,userId,members,documents,onOpen}:{gameId?:string;userId?:string;members:Member[];documents:FormalDocument[];onOpen:(id:string)=>void}){
 const [items,setItems]=useState<{id:string;document_id:string;sender_id:string;note:string|null;created_at:string}[]>([]),[error,setError]=useState('');
 useEffect(()=>{if(!gameId||!userId)return;let active=true;async function load(){const r=await supabase.from('formal_document_deliveries').select('id,document_id,sender_id,note,created_at').eq('game_id',gameId!).eq('recipient_id',userId!).order('created_at',{ascending:false}).limit(30);if(active){if(r.error)setError(r.error.message);else{setItems(r.data||[]);setError('')}}}void load();const timer=setInterval(()=>void load(),20000);return()=>{active=false;clearInterval(timer)}},[gameId,userId,documents]);
 if(!items.length&&!error)return null;
 return <details className="projectDisclosure documentInbox"><DisclosureSummary icon={Send} title={'Входящие документы · '+items.length} description="Документы, присланные вам для ознакомления"/><div className="civicDisclosureBody">{error&&<p className="error" role="alert">{error}</p>}{items.map(x=><button className="documentInboxRow" key={x.id} onClick={()=>onOpen(x.document_id)}><b>{documents.find(d=>d.id===x.document_id)?.title||'Документ'}</b><small>{members.find(m=>m.user_id===x.sender_id)?.full_name||'Участник'} · {new Date(x.created_at).toLocaleString('ru-RU')}</small>{x.note&&<span>{x.note}</span>}</button>)}</div></details>;
}
