'use client';
import {useEffect,useMemo,useRef,useState,type InputHTMLAttributes} from 'react';
import {ArrowRight,Calculator,ChartNoAxesCombined,Check,ChevronDown,Coins,FileText,Landmark,Plus,RefreshCw,Save,Send,Wallet,Clock} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {userError} from '@/lib/userError';
import baseline from '@/data/federal-budget-2026.json';
import type {ReturnTypeRepublic} from './viewTypes';
import type {FiscalContext,FiscalRate,FiscalRegion} from './fiscalMath';
import {billions,calculateFederalBudget,coverFundingGap,financingRate,fundingAnnualInterest,FINANCING_SOURCES,newBudgetDraft,transferLabels,type BudgetDraft,type BudgetTransfer,type FundingKey,type SimulatorState} from './federalBudgetMath';
import StyledSelect from '../ui/StyledSelect';
import styles from './FederalBudgetSimulator.module.css';
type Plan={id:string;title:string;draft:BudgetDraft;revision:number;status:'draft'|'document'|'published';document_id:string|null;registry_no:string|null;updated_at:string;calculation:{revenue:number;expenditure:number;funding_gap:number}};
type Contract={id:string;source_key:FundingKey;principal:number;annual_rate:number;maturity_month:number;status:string};
type Entry={id:number;note:string;amount:number|null;created_at:string;kind:string;source_key:string};
type Props={g:ReturnTypeRepublic;context:FiscalContext|null;regions:FiscalRegion[];rates:FiscalRate[];readOnly:boolean;onOpenDocument:(id:string)=>void;onOpenEvents:()=>void;onSaved:()=>Promise<void>};
const pct=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n)+' %';
function AmountInput({value,onValue,...props}:{value:number;onValue:(n:number)=>void}&Omit<InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'>){
 const [text,setText]=useState(String(value));const focused=useRef(false);
 useEffect(()=>{if(!focused.current)setText(String(value));},[value]);
 return <input {...props} type="number" value={text} onFocus={()=>{focused.current=true;}} onChange={e=>{const v=e.target.value;setText(v);if(v.trim()&&Number.isFinite(Number(v)))onValue(Number(v));}} onBlur={()=>{focused.current=false;setText(String(value));}}/>;
}
export default function FederalBudgetSimulator({g,context,regions,rates,readOnly,onOpenDocument,onOpenEvents,onSaved}:Props){
 const [state,setState]=useState<SimulatorState|null>(null),[plans,setPlans]=useState<Plan[]>([]),[requests,setRequests]=useState<BudgetTransfer[]>([]),[contracts,setContracts]=useState<Contract[]>([]),[ledger,setLedger]=useState<Entry[]>([]),[canPrepare,setCanPrepare]=useState(false),[canRequest,setCanRequest]=useState(false);
 const [draft,setDraft]=useState<BudgetDraft>(newBudgetDraft),[selectedId,setSelectedId]=useState(''),[revision,setRevision]=useState(0),[dirty,setDirty]=useState(false),[tab,setTab]=useState('expense'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[eventCount,setEventCount]=useState(0);
 const [tax,setTax]=useState('vat'),[taxBase,setTaxBase]=useState('100'),[taxRate,setTaxRate]=useState('22'),[taxCompliance,setTaxCompliance]=useState('100');
 const [regionCode,setRegionCode]=useState('54'),[transferKind,setTransferKind]=useState<BudgetTransfer['kind']>('subsidy'),[transferAmount,setTransferAmount]=useState('1'),[cofin,setCofin]=useState('0.2'),[purpose,setPurpose]=useState(''),[section,setSection]=useState('04');
 const initialized=useRef('');const scope=useRef('');scope.current=(g.game?.id||'')+':'+(g.me?.user_id||'');
 const selected=plans.find(p=>p.id===selectedId);
 const calc=useMemo(()=>state?calculateFederalBudget(draft,state,context,regions,rates,requests):null,[draft,state,context,regions,rates,requests]);
 async function load(){
  if(!g.game)return;const requestedScope=scope.current;
  try{const r=await supabase.rpc('get_budget_simulator',{p_game_id:g.game.id});if(requestedScope!==scope.current)return;if(r.error){setError(userError(r.error));return;}
   const d=r.data;if(!d?.state){setError('Бюджетный симулятор не вернул общие данные. Обновите раздел.');return;}
   setState(d.state);setPlans(d.plans||[]);setRequests(d.requests||[]);setContracts(d.contracts||[]);setLedger(d.ledger||[]);setCanPrepare(!!d.can_prepare);setCanRequest(!!d.can_request);setEventCount(d.event_count||0);setError('');
   if(initialized.current!==g.game.id){initialized.current=g.game.id;const last=(d.plans||[]).find((p:Plan)=>p.status==='draft');if(last){setDraft(last.draft);setSelectedId(last.id);setRevision(last.revision);}else if(d.plans?.[0]){setDraft(d.plans[0].draft);setSelectedId(d.plans[0].id);setRevision(d.plans[0].revision);}else{setDraft(newBudgetDraft());setSelectedId('');setRevision(0);}setDirty(false);void onSaved();}
  }catch(e){if(requestedScope===scope.current)setError(userError(e));}
 }
 useEffect(()=>{initialized.current='';void load();if(!g.game)return;const id=setInterval(()=>void load(),15000);return()=>clearInterval(id);},[g.game?.id,g.me?.user_id]);
 useEffect(()=>{if(!g.game)return;let pending:ReturnType<typeof setTimeout>|undefined;const update=()=>{clearTimeout(pending);pending=setTimeout(()=>void load(),200);};let ch=supabase.channel('federal-budget:'+g.game.id);for(const table of ['budget_simulator_plans','budget_simulator_state','budget_transfer_requests','budget_finance_contracts','budget_simulator_ledger','formal_documents'])ch=ch.on('postgres_changes',{event:'*',schema:'public',table,filter:'game_id=eq.'+g.game.id},update);ch.subscribe();return()=>{clearTimeout(pending);void supabase.removeChannel(ch);};},[g.game?.id,g.me?.user_id]);
 function edit(change:Partial<BudgetDraft>){if(readOnly)return;if(selected&&selected.status!=='draft'){setSelectedId('');setRevision(0);}setDraft(d=>({...d,...change}));setDirty(true);setNotice('');}
 function openPlan(p:Plan){setDraft(p.draft);setSelectedId(p.id);setRevision(p.revision);setDirty(false);setNotice('');setError('');}
 function reset(){const current=plans.find(p=>p.id===state?.last_plan_id);setDraft(current?{...current.draft,title:'Изменения федерального бюджета на 2026 год',note:''}:newBudgetDraft());setSelectedId('');setRevision(0);setDirty(false);setNotice(current?'Расчет поправок на основе действующего игрового бюджета.':'Новый расчет на основе плана 2026 года.');}
 async function save(){
  if(!g.game||busy||readOnly||!canPrepare)return null;setBusy(true);setError('');
  try{const r=await supabase.rpc('save_budget_simulator',{p_game_id:g.game.id,p_plan_id:selected?.status==='draft'?selected.id:null,p_draft:draft,p_revision:selected?.status==='draft'?revision:null});if(r.error){setError(userError(r.error));return null;}setSelectedId(r.data.id);setRevision(r.data.revision);setDirty(false);setNotice('Расчет сохранен для всей группы. Действующий бюджет изменится после опубликования закона.');await load();return r.data.id as string;}catch(e){setError(userError(e));return null;}finally{setBusy(false);}
 }
 async function document(){
  if(busy||readOnly||!canPrepare)return;if(selected?.document_id&&!dirty){onOpenDocument(selected.document_id);return;}
  const id=dirty||!selectedId?await save():selectedId;if(!id)return;setBusy(true);
  try{const r=await supabase.rpc('create_budget_simulator_document',{p_plan_id:id});if(r.error)setError(userError(r.error));else{await Promise.all([load(),g.refresh()]);onOpenDocument(String(r.data));}}catch(e){setError(userError(e));}finally{setBusy(false);}
 }
 async function request(){
  if(!g.game||busy||readOnly||!canRequest)return;if(purpose.trim().length<30){setError('Опишите цель, результат и основание запроса: не менее 30 символов.');return;}
  setBusy(true);setError('');try{const r=await supabase.rpc('create_budget_transfer_request',{p_game_id:g.game.id,p_region:regionCode,p_kind:transferKind,p_amount:Number(transferAmount)*1000,p_cofinancing:transferKind==='subsidy'?Number(cofin)*1000:0,p_purpose:purpose.trim(),p_section:transferKind==='grant'?'14':section});if(r.error)setError(userError(r.error));else{setPurpose('');setNotice('Запрос направлен бюджетной команде. Перечисление происходит после принятия и опубликования проекта, в который включен запрос.');await load();}}catch(e){setError(userError(e));}finally{setBusy(false);}
 }
 async function advance(){if(!g.game||!state||busy||!g.teacher)return;setBusy(true);try{const r=await supabase.rpc('advance_budget_simulator',{p_game_id:g.game.id,p_version:state.version});if(r.error)setError(userError(r.error));else{setNotice('Финансовый месяц завершен. Долговые платежи и наступившие события отражены в журнале.');await Promise.all([load(),onSaved()]);}}catch(e){setError(userError(e));}finally{setBusy(false);}}
 async function repay(id:string){if(busy||readOnly||!canPrepare)return;setBusy(true);try{const r=await supabase.rpc('repay_budget_finance_contract',{p_contract_id:id});if(r.error)setError(userError(r.error));else{setNotice('Основной долг погашен из доступного резерва. Проценты учтены отдельно.');await Promise.all([load(),onSaved()]);}}catch(e){setError(userError(e));}finally{setBusy(false);}}
 async function returnCredit(id:string){if(busy||readOnly||!canRequest)return;setBusy(true);try{const r=await supabase.rpc('repay_budget_transfer',{p_request_id:id});if(r.error)setError(userError(r.error));else{setNotice('Бюджетный кредит возвращен. Региональный долг и доступные средства обновлены.');await Promise.all([load(),onSaved()]);}}catch(e){setError(userError(e));}finally{setBusy(false);}}
 const taxCurrent=tax==='vat'?(rates.find(r=>r.region_code==='00'&&r.tax_key==='vat')?.rate??22):(rates.find(r=>r.region_code==='00'&&r.tax_key==='profit')?.rate??25),taxShare=tax==='profit'?.32:1;
 const taxResult=Number(taxBase)*1000*Number(taxRate)/100*Number(taxCompliance)/100*taxShare,taxDelta=Number(taxBase)*1000*(Number(taxRate)-taxCurrent)/100*Number(taxCompliance)/100*taxShare;
 const validTax=[taxBase,taxRate,taxCompliance].every(s=>s.trim()&&Number.isFinite(Number(s)))&&Number(taxBase)>=0&&Number(taxRate)>=0&&Number(taxRate)<=100&&Number(taxCompliance)>=0&&Number(taxCompliance)<=100;
 return <section className={styles.simulator} aria-label="Федеральный бюджетный симулятор">
  <header className={styles.heading}><div><small>РАСЧЕТ · ОБОСНОВАНИЕ · ПРОЕКТ ЗАКОНА</small><h2>Федеральный бюджет · 2026</h2><p>Распределите расходы, оцените доходы и покройте дефицит. Затем направьте расчет в реестр НПА для бюджетной процедуры.</p></div><button type="button" className="secondary" onClick={()=>void load()} disabled={busy} aria-label="Обновить федеральный бюджет"><RefreshCw size={18}/></button></header>
  {!state||!calc?<div className={styles.loading} role={error?'alert':'status'}>{error||'Загружаем общий бюджет и долговые обязательства…'}</div>:<>
   <div className={styles.kpis}>{[{key:'income',label:'Планируемые доходы',value:calc.revenue,detail:'Налоговые и неналоговые поступления',Icon:Coins},{key:'expense',label:'Планируемые расходы',value:calc.expenditure,detail:'14 разделов и включенные трансферты',Icon:Wallet},{key:'balance',label:calc.balance<0?'Дефицит':'Профицит',value:calc.balance<0?calc.deficit:calc.surplus,detail:calc.balance<0?pct(calc.deficit_pct_gdp)+' ВВП':'Доходы превышают расходы',Icon:ChartNoAxesCombined},{key:'debt',label:'Госдолг на конец периода',value:calc.debt_total,detail:pct(calc.debt_pct_gdp)+' ВВП · прогноз',Icon:Landmark}].map(({key,label,value,detail,Icon})=><article key={key} data-budget-kpi={key}><div><Icon size={20}/><span>{label}</span></div><strong>{billions(value)}</strong><small>{detail}</small></article>)}</div>
   <div className={styles.path}><b>Как работать</b><ol><li>Проверьте доходы</li><li>Распределите расходы</li><li>Выберите финансирование</li><li>Создайте проект закона</li></ol></div>
   <div className={styles.planHead}><label>Название расчета<input value={draft.title} maxLength={160} onChange={e=>edit({title:e.target.value})} disabled={readOnly}/></label><button type="button" className="secondary" onClick={reset} disabled={busy||readOnly}><Plus size={18}/> Новый расчет</button><span>{dirty?'Есть несохраненные изменения':selected?.status==='published'?'Закон опубликован':selected?.status==='document'?'Проект в реестре':selected?'Общий черновик':'Личный расчет'}</span></div>
   <nav className={styles.tabs} aria-label="Разделы бюджетного расчета">{[['revenue','Доходы',Coins],['expense','Расходы',Wallet],['finance','Долг и дефицит',Landmark],['regions','Запросы регионов',Send]].map(([key,label,Icon])=>{const I=Icon as typeof Coins;return <button key={String(key)} type="button" aria-pressed={tab===key} onClick={()=>setTab(String(key))}><I size={18}/><span>{String(label)}</span>{key==='regions'&&requests.filter(r=>r.status==='requested').length>0&&<em>{requests.filter(r=>r.status==='requested').length}</em>}</button>;})}</nav>
   {tab==='revenue'&&<div className={styles.panel}><h3>Из чего складываются доходы</h3><p>Исходные группы — прогноз Минфина на 2026 год. Изменение базы отражает вашу оценку поступлений; налоги вводятся отдельным законом, а не законом о бюджете.</p><div className={styles.tableHead}><span>Источник</span><span>План 2026</span><span>Изменение базы, %</span><span>Ваш прогноз</span></div><div>{baseline.income_lines.map(l=><article className={styles.line} data-budget-income={l.key} key={l.key}><div><b>{l.label}</b><details><summary>Состав доходов</summary><p>{l.explanation}</p></details></div><span>{billions(l.amount)}</span><label><span className={styles.sr}>Изменение базы: {l.label}, %</span><AmountInput min={-80} max={200} step={.5} value={draft.income_changes[l.key]??0} onValue={n=>edit({income_changes:{...draft.income_changes,[l.key]:n}})} disabled={readOnly}/></label><strong>{billions(calc.income_lines.find(r=>r.key===l.key)!.amount)}</strong></article>)}</div><p className={styles.rounding}>Округление доходных групп: +{billions(baseline.income_rounding)}. Отдельный эффект финансовых событий: {billions(state.revenue_adjustment)}. Сумма групп, округления и этого эффекта равна общему итогу.</p>
    <details className={styles.taxCalculator}><summary><Calculator size={19}/> Калькулятор налоговой меры</summary><div className={styles.fields}><StyledSelect label="Налог" value={tax} onChange={v=>{setTax(v);setTaxRate(String(rates.find(r=>r.region_code==='00'&&r.tax_key===v)?.rate??(v==='vat'?22:25)));}} options={[{value:'vat',label:'НДС — общая ставка'},{value:'profit',label:'Налог на прибыль — общая ставка'}]}/><label>База без налога, млрд ₽<input type="number" min="0" value={taxBase} onChange={e=>setTaxBase(e.target.value)}/></label><label>Ставка для сравнения, %<input type="number" min="0" max="100" value={taxRate} onChange={e=>setTaxRate(e.target.value)}/></label><label>Собираемость, %<input type="number" min="0" max="100" value={taxCompliance} onChange={e=>setTaxCompliance(e.target.value)}/></label></div><p>Поступление = база × ставка / 100 × собираемость / 100 × доля федерального бюджета. Доля в учебной схеме: {tax==='profit'?'32 % (8 из 25 процентных пунктов)':'100 %'}. Для специальных ставок, вычетов и отдельных доходов применяется отдельный расчет.</p><div className={styles.comparison}><div><small>Федеральное поступление</small><b>{validTax?billions(taxResult):'Проверьте значения'}</b></div><div><small>Изменение к ставке {pct(taxCurrent)}</small><b>{validTax?billions(taxDelta):'Проверьте значения'}</b></div></div><button type="button" className="secondary" disabled={!validTax||readOnly} onClick={()=>{const key=tax==='vat'?'turnover':'income';edit({revenue_adjustments:{...draft.revenue_adjustments,[key]:taxDelta}});setNotice('Дельта калькулятора учтена в прогнозе. Повторное нажатие заменяет эту дельту, не добавляет ее еще раз. Налоговый акт оформляется отдельно.');}}><Check size={18}/> Учесть дельту в прогнозе</button></details>
   </div>}
   {tab==='expense'&&<div className={styles.panel}><h3>Расходы по отраслям и сферам</h3><p>Меняйте объем каждого раздела относительно исходного плана. Проценты по новым источникам долга рассчитываются в разделе 13 автоматически. Субсидии и субвенции регионам входят в соответствующие отрасли.</p><div className={styles.tableHead}><span>Раздел расходов</span><span>План 2026</span><span>Изменение, %</span><span>Ваш проект</span></div><div>{baseline.expense_lines.map(l=><article className={styles.line} data-budget-expense={l.key} key={l.key}><div><b><i>{l.key}</i>{l.label}</b><details><summary>Что финансируется</summary><p>{l.explanation}</p></details></div><span>{billions(l.amount)}</span><label><span className={styles.sr}>Изменение расходов: {l.label}, %</span><AmountInput min={-80} max={200} step={1} value={draft.spending_changes[l.key]??0} onValue={n=>edit({spending_changes:{...draft.spending_changes,[l.key]:n}})} disabled={readOnly}/></label><div><strong>{billions(calc.expense_lines.find(r=>r.key===l.key)!.amount)}</strong><div className={styles.bar} aria-hidden="true"><span style={{width:Math.min(100,calc.expense_lines.find(r=>r.key===l.key)!.amount/Math.max(1,calc.expenditure)*100)+'%'}}/></div></div></article>)}</div><p className={styles.rounding}>Корректировка округления разделов: {billions(baseline.expense_rounding)}. Отраслевые трансферты не добавляются второй раз к общей сумме.</p><div className={styles.comparison}><div><small>Интервал доходов</small><b>{billions(calc.revenue_low)} — {billions(calc.revenue_high)}</b></div><div><small>Интервал расходов</small><b>{billions(calc.expenditure_low)} — {billions(calc.expenditure_high)}</b></div></div></div>}
   {tab==='finance'&&<div className={styles.panel}><h3>Как покрыть дефицит</h3><div className={styles.debtSplit}><article><span>Внутренний долг</span><b>{billions(calc.internal_debt)}</b><small>Обязательства в рублях</small></article><article><span>Внешний долг</span><b>{billions(calc.external_debt)}</b><small>В рублевом эквиваленте · курс {new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(calc.fx)} ₽ за 1 доллар</small></article><article><span>Доступный резерв после решения</span><b>{billions(calc.reserve_remaining)}</b><small>Учебный предел ликвидных средств ФНБ</small></article></div><div className={styles.fundingBalance} data-budget-funding-gap={calc.funding_gap}><span>Потребность в финансировании <b>{billions(calc.funding_need)}</b></span><span>Источники покрытия <b>{billions(calc.financing)}</b></span><span className={calc.funding_gap>1?styles.bad:styles.good}>{calc.funding_gap>1?'Не покрыто':'Дефицит покрыт'} <b>{billions(calc.funding_gap)}</b></span></div><p>Основной долг и бюджетные кредиты регионам учитываются под чертой расходов. Заемные средства не увеличивают доходы. Избыток источников формирует остаток денежных средств: {billions(calc.cash_excess)}.</p>
    <div className={styles.fundingGrid}>{FINANCING_SOURCES.map(s=><article key={s.key} data-financing-source={s.key}><header><Landmark size={21}/><h4>{s.label}</h4></header><p>{s.lender}</p><label>Объем, млрд ₽<AmountInput step={.1} min={s.key==='other'?undefined:0} value={draft.financing[s.key]/1000} onValue={n=>edit({financing:{...draft.financing,[s.key]:n*1000}})} disabled={readOnly}/></label>{s.debt!=='none'&&<><div className={styles.loanTerms}><span>Новое привлечение: <b>{pct(financingRate(s.key,context?.policy.key_rate??state.anchor.key_rate))} годовых</b></span><label>Срок, месяцев<AmountInput min={1} max={120} value={draft.terms[s.key]??60} onValue={n=>edit({terms:{...draft.terms,[s.key]:n}})} disabled={readOnly}/></label></div><p>Проценты за полный год: <b>{billions(fundingAnnualInterest(s.key,draft,state,context?.policy.key_rate??state.anchor.key_rate))}</b></p></>}<details><summary>Условия и последствия</summary><p>{s.risk}</p></details>{s.key!=='other'&&<button type="button" className="secondary" disabled={readOnly||calc.funding_gap<=1} onClick={()=>edit(coverFundingGap(draft,s.key,state,context,regions,rates,requests))}><Plus size={17}/> Покрыть остаток</button>}</article>)}</div><p className={styles.rounding}>Для новых чистых заимствований принят учебный расчет процентов за половину года. Изменение стоимости обслуживания: {billions(calc.interest_delta)}. Ставки сделок — условия симулятора, не рыночные котировки.</p>
    <details className={styles.contracts}><summary><Clock size={18}/> Долговой календарь · {contracts.length}</summary><p>Учебный финансовый месяц: {state.month}. События риска появляются при синхронизации через 15 минут после опубликования бюджета либо при переходе в следующий финансовый месяц. Если игра закрыта, событие доставляется при следующем входе. Погашение отражается отдельно от процентов.</p>{contracts.map(c=><article key={c.id}><span><b>{FINANCING_SOURCES.find(s=>s.key===c.source_key)?.label}</b><small>{pct(c.annual_rate)} годовых · погашение в месяц {c.maturity_month} · {c.status==='active'?'Действует':c.status==='due'?'Наступил срок погашения':'Погашен'}</small></span><strong>{billions(c.principal*(c.source_key==='external'?calc.fx/state.anchor.fx_rate:1))}</strong>{c.status!=='paid'&&canPrepare&&!readOnly&&<button type="button" className="secondary" disabled={busy} onClick={()=>void repay(c.id)}>Погасить из резерва</button>}</article>)}{g.teacher&&!readOnly&&<button type="button" className="secondary" onClick={()=>void advance()} disabled={busy||!state.last_plan_id}><Clock size={18}/> Следующий финансовый месяц</button>}{eventCount>0&&<button type="button" className="secondary" onClick={onOpenEvents}><ArrowRight size={18}/> Финансовые события · {eventCount}</button>}</details>
   </div>}
   {tab==='regions'&&<div className={styles.panel}><h3>Региональные запросы</h3><p>Регион запрашивает помощь, бюджетная команда включает ее в проект, а после опубликования сумма отражается в региональном бюджете. Дотация поддерживает бюджет без привязки к конкретному расходу; субсидия софинансирует обязательство; субвенция обеспечивает переданное полномочие; бюджетный кредит нужно вернуть.</p><details className={styles.requestForm}><summary><Send size={18}/> Подготовить запрос региона</summary><div className={styles.fields}><StyledSelect label="Регион запроса" value={regionCode} onChange={setRegionCode} options={regions.map(r=>({value:r.region_code,label:r.name}))}/><StyledSelect label="Вид поддержки" value={transferKind} onChange={v=>setTransferKind(v as BudgetTransfer['kind'])} options={Object.entries(transferLabels).map(([value,label])=>({value,label}))}/><label>Запрашиваемая сумма, млрд ₽<input type="number" min={.001} step={.1} value={transferAmount} onChange={e=>setTransferAmount(e.target.value)}/></label>{transferKind==='subsidy'&&<label>Софинансирование региона, млрд ₽<input type="number" min={0} step={.1} value={cofin} onChange={e=>setCofin(e.target.value)}/></label>}{transferKind!=='grant'&&transferKind!=='budget_credit'&&<StyledSelect label="Отрасль финансирования" value={section} onChange={setSection} options={baseline.expense_lines.filter(r=>r.key!=='13'&&r.key!=='14').map(r=>({value:r.key,label:r.label}))}/>}</div><label>Цель, результат и основание<textarea value={purpose} onChange={e=>setPurpose(e.target.value)} rows={3} placeholder="Какие обязательства исполняет регион, на что требуются средства, какой результат и документы подтверждают запрос?"/></label><button type="button" className="primary" onClick={()=>void request()} disabled={busy||readOnly||!canRequest}><Send size={18}/> Направить запрос</button>{!canRequest&&<p>Запрос от региона оформляет действующий представитель исполнительной власти.</p>}</details>
    <div className={styles.requests}>{requests.length?requests.map(r=>{const included=draft.transfer_ids.includes(r.id);return <article key={r.id} data-budget-request={r.id}><header><span><b>{r.region_name}</b><small>{transferLabels[r.kind]} · {r.status==='granted'?'Предоставлено':r.status==='rejected'?'Отклонено':'Ожидает включения в бюджет'}</small></span><strong>{billions(r.amount)}</strong></header><p>{r.purpose}</p>{r.kind==='subsidy'&&<p>Софинансирование: {billions(r.cofinancing)}</p>}<div className={styles.actions}>{r.status!=='granted'&&r.status!=='rejected'&&<button type="button" className={included?'primary':'secondary'} disabled={readOnly||!canPrepare} onClick={()=>edit({transfer_ids:included?draft.transfer_ids.filter(id=>id!==r.id):[...draft.transfer_ids,r.id]})}>{included?<Check size={18}/>:<Plus size={18}/>} {included?'Исключить из проекта':'Включить в проект'}</button>}{r.kind==='budget_credit'&&r.status==='granted'&&canRequest&&!readOnly&&<button type="button" className="secondary" disabled={busy||!!r.repaid_at} onClick={()=>void returnCredit(r.id)}>{r.repaid_at?'Кредит возвращен':'Вернуть бюджетный кредит'}</button>}{r.document_id&&<button type="button" className="secondary" onClick={()=>onOpenDocument(r.document_id!)}><FileText size={18}/> Основание</button>}</div></article>;}):<p>Запросов пока нет. Правовые кейсы по трансфертам доступны на бюджетной карте ниже.</p>}</div></div>}
   <footer className={styles.submission}><label>Обоснование и приоритеты<textarea rows={3} value={draft.note} onChange={e=>edit({note:e.target.value})} disabled={readOnly} placeholder="Почему выбраны эти расходы и источники, какие риски учтены, чем подтверждены изменения доходов?"/></label><div className={styles.actions}><button type="button" className="secondary" onClick={()=>void save()} disabled={busy||readOnly||!canPrepare}><Save size={18}/> Сохранить общий расчет</button><button type="button" className="primary" onClick={()=>void document()} disabled={busy||readOnly||!canPrepare||calc.funding_gap>1||calc.reserve_remaining<0||draft.note.trim().length<30}><FileText size={18}/> {selected?.document_id&&!dirty?'Открыть проект в реестре':'Создать проект бюджета'}</button></div>{!canPrepare?<p>Считать и сравнивать может каждый. Общий проект подготавливают Правительство, Минфин и преподаватель.</p>:<p>{calc.funding_gap>1?'Выберите источники и покройте дефицит перед созданием проекта.':calc.reserve_remaining<0?'Запрос превышает доступный резерв. Измените источники.':draft.note.trim().length<30?'Добавьте обоснование не короче 30 символов.':'Далее: внесение → чтения Государственной Думы → Совет Федерации → подпись Президента → опубликование. До опубликования долг и трансферты не исполняются.'}</p>}</footer>
   <details className={styles.saved}><summary><FileText size={18}/> Общие расчеты и проекты · {plans.length}</summary>{plans.map(p=><article key={p.id}><span><b>{p.title}</b><small>{p.status==='published'?'Опубликован':p.status==='document'?'Проект в реестре':'Черновик'} · версия {p.revision}</small></span><button type="button" className="secondary" onClick={()=>openPlan(p)}>Открыть расчет</button>{p.document_id&&<button type="button" className="secondary" onClick={()=>onOpenDocument(p.document_id!)}><FileText size={18}/> {p.registry_no||'НПА'}</button>}</article>)}</details>
   <details className={styles.sources}><summary><ChevronDown size={18}/> Источники, формулы и границы модели</summary><p><a href={baseline.source_url} target="_blank" rel="noreferrer">{baseline.source_label} ↗</a>. {baseline.baseline_kind}. Проверено 2 октября 2026 года. Это исходный план для обучения, а не онлайн-данные об исполнении.</p><p><a href={baseline.revenue_source_url} target="_blank" rel="noreferrer">Группы доходов: таблица 4.1.2 документа Минфина ↗</a>. Нефтегазовые и ненефтегазовые группы не пересекаются. Страховые взносы внебюджетных фондов не добавляются к федеральным доходам.</p><p>Калибровка игровой модели: ключевая ставка {pct(state.anchor.key_rate)}, курс {state.anchor.fx_rate} ₽/доллар, нефть {state.anchor.oil_price} долларов/баррель, инфляция {pct(state.anchor.inflation)}. Официальный исходный макропрогноз: нефть {baseline.macro_reference.oil_price} долларов/баррель, курс {baseline.macro_reference.fx_rate} ₽/доллар, инфляция {pct(baseline.macro_reference.inflation)}. Различие показывает редукцию параметров в правилах игры.</p><p>Баланс = доходы − расходы. Дефицит = max(0; расходы − доходы). Потребность в финансировании = дефицит + новые бюджетные кредиты регионам. Проценты входят в расходы; основной долг и приватизация акций — в источники финансирования. Валютный долг пересчитывается по курсу.</p><p>Внутренний долг на начало 2026 года: {billions(baseline.internal_debt_start)}; внешний: {billions(baseline.external_debt_start)}. Прочие расчетные движения исходного плана: {billions(baseline.internal_debt_other_movement)} и {billions(baseline.external_debt_other_movement)}. Это позволяет сверить конечный долг с опубликованным прогнозом без приравнивания долга к одному дефициту.</p><ul>{baseline.assumptions.map(s=><li key={s}>{s}</li>)}</ul><p>{baseline.reserve_note}</p></details>
   {ledger.filter(e=>e.kind==='publication_blocked'&&plans.some(p=>p.status!=='published'&&e.source_key==='blocked:'+p.id)).map(e=><p key={e.id} role="alert" className={styles.error}>{e.note} Откройте проект в реестре и подготовьте расчет поправок с учетом действующего бюджета.</p>)}
   <details className={styles.journal}><summary><Clock size={18}/> Финансовый журнал · {ledger.length}</summary>{ledger.length?ledger.map(e=><article key={e.id}><time>{new Date(e.created_at).toLocaleString('ru-RU')}</time><span>{e.note}</span>{e.amount!==null&&<b>{billions(e.amount)}</b>}</article>):<p>Записи появятся после сохранения проекта, опубликования бюджета, перечисления поддержки и финансовых событий.</p>}</details>
  </>}
  {error&&state&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status" className={styles.notice}>{notice}</p>}
 </section>;
}
