'use client';
import {useEffect,useId,useMemo,useRef,useState,type InputHTMLAttributes} from 'react';
import {ArrowRight,Calculator,ChartNoAxesCombined,Check,ChevronDown,Coins,FileText,Landmark,Plus,RefreshCw,Save,Send,Wallet,Clock,ArrowRightLeft} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {useGameTableSync} from './useGameTableSync';
import {userError} from '@/lib/userError';
import {moneyMillions} from '@/lib/formatQuantity';
import {budgetModeLabel} from './useBudgetPulse';
import baseline from '@/data/federal-budget-2026.json';
import type {ReturnTypeRepublic} from './viewTypes';
import type {FiscalContext,FiscalRate,FiscalRegion} from './fiscalMath';
import {billions,budgetDisplay,budgetMoney,calculateFederalBudget,coverFundingGap,financingRate,fundingAnnualInterest,FINANCING_SOURCES,newBudgetDraft,transferLabels,type BudgetDraft,type BudgetTransfer,type FundingKey,type SimulatorState} from './federalBudgetMath';
import StyledSelect from '../ui/StyledSelect';
import BudgetAmendments from './BudgetAmendments';
import BudgetIncomeTable from './BudgetIncomeTable';
import BudgetExpenses,{type SignedBudgetProgram} from './BudgetExpenses';
import BudgetRegionWorkspace,{type BudgetRegionalEvent} from './BudgetRegionWorkspace';
import styles from './FederalBudgetSimulator.module.css';
type Plan={id:string;title:string;draft:BudgetDraft;revision:number;status:'draft'|'document'|'published';document_id:string|null;registry_no:string|null;updated_at:string;calculation:{revenue:number;expenditure:number;funding_gap:number}};
type Contract={id:string;source_key:FundingKey;principal:number;annual_rate:number;maturity_month:number;status:string};
type Entry={id:number;note:string;amount:number|null;created_at:string;kind:string;source_key:string};
type Props={g:ReturnTypeRepublic;context:FiscalContext|null;regions:FiscalRegion[];rates:FiscalRate[];programs?:SignedBudgetProgram[];readOnly:boolean;onOpenDocument:(id:string)=>void;onOpenEvents:()=>void;onOpenVotes?:(id:string)=>void;onOpenStage?:(stageNo:number)=>void;onSaved:()=>Promise<void>};
const pct=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n)+' %';
function AmountInput({value,onValue,...props}:{value:number;onValue:(n:number)=>void}&Omit<InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'>){
 const [text,setText]=useState(String(value));const focused=useRef(false);
 useEffect(()=>{if(!focused.current)setText(String(value));},[value]);
 return <input {...props} type="number" value={text} onFocus={()=>{focused.current=true;}} onChange={e=>{const v=e.target.value;setText(v);if(v.trim()&&Number.isFinite(Number(v)))onValue(Number(v));}} onBlur={()=>{focused.current=false;setText(String(value));}}/>;
}
export default function FederalBudgetSimulator({g,context,regions,rates,programs=[],readOnly,onOpenDocument,onOpenEvents,onOpenVotes,onOpenStage,onSaved}:Props){
 const [state,setState]=useState<SimulatorState|null>(null),[plans,setPlans]=useState<Plan[]>([]),[requests,setRequests]=useState<BudgetTransfer[]>([]),[contracts,setContracts]=useState<Contract[]>([]),[ledger,setLedger]=useState<Entry[]>([]),[canPrepare,setCanPrepare]=useState(false),[canRequest,setCanRequest]=useState(false);
 const [draft,setDraft]=useState<BudgetDraft>(newBudgetDraft),[selectedId,setSelectedId]=useState(''),[revision,setRevision]=useState(0),[dirty,setDirty]=useState(false),[tab,setTab]=useState('revenue'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[eventCount,setEventCount]=useState(0),[regionalEvents,setRegionalEvents]=useState<BudgetRegionalEvent[]>([]);
 const tabId=useId();const tabs=[['revenue','Доходы',Coins],['regions','Регионы',Send],['expense','Расходы',Wallet],['finance','Баланс',Landmark],['law','Проект ФЗ',FileText]] as const;
 const initialized=useRef('');const scope=useRef('');scope.current=(g.game?.id||'')+':'+(g.me?.user_id||'');
 const selected=plans.find(p=>p.id===selectedId);
 const editor=useRef({selectedId,revision,dirty});editor.current={selectedId,revision,dirty};
 const calc=useMemo(()=>state?calculateFederalBudget(draft,state,context,regions,rates,requests):null,[draft,state,context,regions,rates,requests]);
 async function load(){
  if(!g.game)return;const requestedScope=scope.current;
  try{const r=await supabase.rpc('get_budget_simulator',{p_game_id:g.game.id});if(requestedScope!==scope.current)return;if(r.error){setError(userError(r.error));return;}
   const d=r.data;if(!d?.state){setError('Бюджетный симулятор не вернул общие данные. Обновите раздел.');return;}
   setState(d.state);setPlans(d.plans||[]);setRequests(d.requests||[]);setRegionalEvents(d.regional_events||[]);setContracts(d.contracts||[]);setLedger(d.ledger||[]);setCanPrepare(!!d.can_prepare);setCanRequest(!!d.can_request);setEventCount(d.event_count||0);setError('');
   if(initialized.current!==g.game.id){initialized.current=g.game.id;const last=(d.plans||[]).find((p:Plan)=>p.status==='draft');if(last){setDraft(last.draft);setSelectedId(last.id);setRevision(last.revision);}else if(d.plans?.[0]){setDraft(d.plans[0].draft);setSelectedId(d.plans[0].id);setRevision(d.plans[0].revision);}else{setDraft(newBudgetDraft());setSelectedId('');setRevision(0);}setDirty(false);void onSaved();}
   else if(!editor.current.dirty){const remote=(d.plans||[]).find((p:Plan)=>p.id===editor.current.selectedId);if(remote&&remote.revision!==editor.current.revision){setDraft(remote.draft);setRevision(remote.revision);}}
  }catch(e){if(requestedScope===scope.current)setError(userError(e));}
 }
 useEffect(()=>{initialized.current=''},[g.game?.id,g.me?.user_id]);
 useGameTableSync(g.game?.id,['budget_simulator_plans','budget_simulator_state','budget_transfer_requests','budget_finance_contracts','budget_simulator_ledger','formal_documents','budget_faction_amendments','event_cases','event_assignments'],load,g.me?.user_id||'');
 function edit(change:Partial<BudgetDraft>){if(readOnly)return;if(selected&&selected.status!=='draft'){setSelectedId('');setRevision(0);}setDraft(d=>({...d,...change}));setDirty(true);setNotice('');}
 function openPlan(p:Plan){setDraft(p.draft);setSelectedId(p.id);setRevision(p.revision);setDirty(false);setNotice('');setError('');}
 function reset(){const current=plans.find(p=>p.id===state?.last_plan_id);setDraft(current?{...current.draft,title:'Изменения федерального бюджета на 2026 год',note:''}:newBudgetDraft());setSelectedId('');setRevision(0);setDirty(false);setNotice(current?'Расчет поправок на основе действующего игрового бюджета.':'Новый расчет на основе плана 2026 года.');}
 async function save(){
  if(!g.game||busy||readOnly||!canPrepare)return null;setBusy(true);setError('');
  try{const r=await supabase.rpc('save_budget_simulator',{p_game_id:g.game.id,p_plan_id:selected?.status==='draft'?selected.id:null,p_draft:draft,p_revision:selected?.status==='draft'?revision:null});if(r.error){setError(userError(r.error));return null;}setSelectedId(r.data.id);setRevision(r.data.revision);setDirty(false);setNotice('Расчет сохранен для всей группы. Действующий бюджет изменится после опубликования закона.');await Promise.all([load(),onSaved(),g.refreshBudgetPulse?.()]);return r.data.id as string;}catch(e){setError(userError(e));return null;}finally{setBusy(false);}
 }
 async function document(){
  if(busy||readOnly||!canPrepare)return;if(selected?.document_id&&!dirty){onOpenDocument(selected.document_id);return;}
  const id=dirty||!selectedId?await save():selectedId;if(!id)return;setBusy(true);
  try{const r=await supabase.rpc('create_budget_simulator_document',{p_plan_id:id});if(r.error)setError(userError(r.error));else{await Promise.all([load(),g.refresh(),g.refreshBudgetPulse?.()]);onOpenDocument(String(r.data));}}catch(e){setError(userError(e));}finally{setBusy(false);}
 }
 async function advance(){if(!g.game||!state||busy||!g.teacher)return;setBusy(true);try{const r=await supabase.rpc('advance_budget_simulator',{p_game_id:g.game.id,p_version:state.version});if(r.error)setError(userError(r.error));else{setNotice('Финансовый месяц завершен. Долговые платежи и наступившие события отражены в журнале.');await Promise.all([load(),onSaved(),g.refreshBudgetPulse?.()]);}}catch(e){setError(userError(e));}finally{setBusy(false);}}
 async function repay(id:string){if(busy||readOnly||!canPrepare)return;setBusy(true);try{const r=await supabase.rpc('repay_budget_finance_contract',{p_contract_id:id});if(r.error)setError(userError(r.error));else{setNotice('Основной долг погашен из доступного резерва. Проценты учтены отдельно.');await Promise.all([load(),onSaved(),g.refreshBudgetPulse?.()]);}}catch(e){setError(userError(e));}finally{setBusy(false);}}
 async function returnCredit(id:string){if(busy||readOnly||!canRequest)return;setBusy(true);try{const r=await supabase.rpc('repay_budget_transfer',{p_request_id:id});if(r.error)setError(userError(r.error));else{setNotice('Бюджетный кредит возвращен. Региональный долг и доступные средства обновлены.');await Promise.all([load(),onSaved(),g.refreshBudgetPulse?.()]);}}catch(e){setError(userError(e));}finally{setBusy(false);}}
 return <section className={styles.simulator} aria-label="Федеральный бюджетный симулятор">
  <header className={styles.heading}><div><small>РАСЧЕТ · ОБОСНОВАНИЕ · ПРОЕКТ ЗАКОНА</small><h2>Федеральный бюджет · 2026</h2><p>Доходы → регионы → расходы → баланс → проект ФЗ. Один расчёт используется в разделе «Бюджет», на этапе 13 и в числовых приложениях к закону.</p></div><button type="button" className="secondary" onClick={()=>void Promise.all([load(),onSaved(),g.refreshBudgetPulse?.()])} disabled={busy} aria-label="Обновить федеральный бюджет"><RefreshCw size={18}/></button></header>
  {!state||!calc?<div className={styles.loading} role={error?'alert':'status'}>{error||'Загружаем общий бюджет и долговые обязательства…'}</div>:<>
   <div className={styles.shared} aria-label="Текущий бюджетный расчёт"><div><small>Текущий бюджетный расчёт</small><b>{selected?.title||draft.title}</b><p>{dirty?'Есть несохранённые изменения. Данные действующего закона не меняются.':selected?.status==='published'?'Опубликованный закон':selected?.status==='document'?'Проект зарегистрирован в реестре НПА':selected?'Сохранённый черновик · версия '+revision:'Новый расчёт, ещё не сохранён'} · {g.budgetPulse?.plan_id===selectedId&&selectedId?'Совпадает с общим прогнозом':'Для публикации потребуется принятие закона'}.</p>{g.budgetPulseError&&<p role="alert">{g.budgetPulseError}</p>}</div><div className={styles.sharedTotal}><small>Доходы по общему прогнозу</small><strong data-budget-shared="income" data-budget-value={g.budgetPulse?.calculation.revenue}>{g.budgetPulse?moneyMillions(g.budgetPulse.calculation.revenue):'…'}</strong></div></div>
   <p className={styles.workLabel}>{dirty?'Несохраненный расчет — пока виден только вам':selected?.id&&selected.id===g.budgetPulse?.plan_id?'Рабочий расчет общего проекта':'Рабочий расчет выбранного проекта'} · Изменения расчёта сохраняются как общая версия проекта бюджета.</p>
   <div className={styles.kpis}>{[{key:'income',label:'Планируемые доходы',value:calc.revenue,detail:'Налоговые и неналоговые поступления',Icon:Coins},{key:'expense',label:'Планируемые расходы',value:calc.expenditure,detail:'14 разделов и включенные трансферты',Icon:Wallet},{key:'balance',label:calc.balance<0?'Дефицит':'Профицит',value:calc.balance<0?calc.deficit:calc.surplus,detail:calc.balance<0?pct(calc.deficit_pct_gdp)+' ВВП':'Доходы превышают расходы',Icon:ChartNoAxesCombined},{key:'debt',label:'Госдолг на конец периода',value:calc.debt_total,detail:pct(calc.debt_pct_gdp)+' ВВП · прогноз',Icon:Landmark}].map(({key,label,value,detail,Icon})=><article key={key} data-budget-kpi={key}><div><Icon size={20}/><span>{label}</span></div><strong>{billions(value)}</strong><small>{detail}</small></article>)}</div>
   <div className={styles.planHead}><label>Название расчета<input value={draft.title} maxLength={160} onChange={e=>edit({title:e.target.value})} disabled={readOnly}/></label><button type="button" className="secondary" onClick={reset} disabled={busy||readOnly}><Plus size={18}/> Новый расчет</button><span>{dirty?'Есть несохраненные изменения':selected?.status==='published'?'Закон опубликован':selected?.status==='document'?'Проект в реестре':selected?'Общий черновик':'Личный расчет'}</span></div>
   <nav className={styles.tabs} role="tablist" aria-label="Разделы бюджетного расчёта">{tabs.map(([key,label,Icon],i)=><button key={key} type="button" role="tab" id={tabId+'-'+key} aria-controls={tabId+'-panel'} aria-selected={tab===key} tabIndex={tab===key?0:-1} onClick={()=>setTab(key)} onKeyDown={e=>{const index=e.key==='Home'?0:e.key==='End'?tabs.length-1:e.key==='ArrowRight'?(i+1)%tabs.length:e.key==='ArrowLeft'?(i-1+tabs.length)%tabs.length:-1;if(index>=0){e.preventDefault();setTab(tabs[index][0]);window.document.getElementById(tabId+'-'+tabs[index][0])?.focus();}}}><span className={styles.stepNumber}>{i+1}</span><Icon size={18}/><span>{label}</span></button>)}</nav>
   <div role="tabpanel" id={tabId+'-panel'} aria-labelledby={tabId+'-'+tab} tabIndex={0}>
   {tab==='revenue'&&<BudgetIncomeTable calculation={calc} draft={draft} state={state} readOnly={readOnly} onEdit={edit}/>}
   {tab==='regions'&&g.game&&<BudgetRegionWorkspace key={g.game.id} gameId={g.game.id} regions={regions} rates={rates} context={context} events={regionalEvents} requests={requests} draft={draft} readOnly={readOnly} canRequest={canRequest} onSaved={async()=>{await Promise.all([load(),onSaved()]);}} onOpenEvents={onOpenEvents} onOpenExpenses={()=>setTab('expense')} onReturnCredit={returnCredit}/>}
   {tab==='expense'&&<BudgetExpenses draft={draft} calculation={calc} requests={requests} programs={programs} readOnly={readOnly} canPrepare={canPrepare} onEdit={edit} onOpenDocument={onOpenDocument} onOpenPrograms={onOpenStage?()=>onOpenStage(11):undefined}/>}
   {tab==='finance'&&<div className={styles.panel}><h3>4. Сведите баланс и покройте дефицит</h3><div className={styles.debtSplit}><article><span>Внутренний долг</span><b>{billions(calc.internal_debt)}</b><small>Обязательства в рублях</small></article><article><span>Внешний долг</span><b>{billions(calc.external_debt)}</b><small>В рублевом эквиваленте · курс {new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(calc.fx)} ₽ за 1 доллар</small></article><article><span>Доступный резерв после решения</span><b>{billions(calc.reserve_remaining)}</b><small>Ограничение доступного остатка ФНБ по сценарию</small></article></div><div className={styles.fundingBalance} data-budget-funding-gap={calc.funding_gap}><span>Потребность в финансировании <b>{budgetDisplay(calc.funding_need)}</b></span><span>Источники покрытия <b>{budgetDisplay(calc.financing)}</b></span><span className={calc.funding_gap>0?styles.bad:styles.good}>{calc.funding_gap>0?'Не покрыто':'Дефицит покрыт'} <b>{budgetDisplay(calc.funding_gap)}</b></span></div><p>Основной долг и бюджетные кредиты регионам учитываются под чертой расходов. Заемные средства не увеличивают доходы. Избыток источников формирует остаток денежных средств: {billions(calc.cash_excess)}.</p>
    <div className={styles.fundingGrid}>{FINANCING_SOURCES.map(s=><article key={s.key} data-financing-source={s.key}><header><Landmark size={21}/><h4>{s.label}</h4></header><p>{s.lender}</p><label>Объём, трлн ₽<AmountInput step={.0001} min={s.key==='other'?undefined:0} value={Number((draft.financing[s.key]/1000000).toFixed(8))} onValue={n=>edit({financing:{...draft.financing,[s.key]:budgetMoney(n*1000000)}})} disabled={readOnly}/></label>{s.debt!=='none'&&<><div className={styles.loanTerms}><span>Новое привлечение: <b>{pct(financingRate(s.key,context?.policy.key_rate??state.anchor.key_rate))} годовых</b></span><label>Срок, месяцев<AmountInput min={1} max={120} value={draft.terms[s.key]??60} onValue={n=>edit({terms:{...draft.terms,[s.key]:n}})} disabled={readOnly}/></label></div><p>Проценты за полный год: <b>{billions(fundingAnnualInterest(s.key,draft,state,context?.policy.key_rate??state.anchor.key_rate))}</b></p></>}<details><summary>Условия, правовая основа и последствия</summary><p>{s.risk}</p><p><a href={s.key.startsWith('ofz')?'https://www.minfin.gov.ru/ru/perfomance/public_debt/internal/operations/':s.key==='reserves'?'https://www.minfin.gov.ru/ru/perfomance/nationalwealthfund/':'https://www.consultant.ru/document/cons_doc_LAW_19702/'} target="_blank" rel="noreferrer">Правовая основа и справочная информация ↗</a></p><p>Расчёт процентов зависит от суммы, ставки и срока. Привлечение долга не создаёт налоговых доходов; основной долг подлежит погашению.</p></details>{s.key!=='other'&&<button type="button" className="secondary" disabled={readOnly||calc.funding_gap<=0} onClick={()=>edit(coverFundingGap(draft,s.key,state,context,regions,rates,requests))}><Plus size={17}/> Покрыть остаток</button>}</article>)}</div><p className={styles.rounding}>Для новых заимствований применяется расчёт процентов за половину года. Этот срок — допущение модели, а не характеристика каждого выпуска. Изменение стоимости обслуживания: {billions(calc.interest_delta)}. Ставки новых заимствований — расчётные условия; они не являются текущими биржевыми котировками.</p>
    <details className={styles.contracts}><summary><Clock size={18}/> Долговой календарь · {contracts.length}</summary><p>Финансовый период: {state.month}. События риска появляются при синхронизации через 15 минут после опубликования бюджета либо при переходе в следующий финансовый месяц. Если игра закрыта, событие доставляется при следующем входе. Погашение отражается отдельно от процентов.</p>{contracts.map(c=><article key={c.id}><span><b>{FINANCING_SOURCES.find(s=>s.key===c.source_key)?.label}</b><small>{pct(c.annual_rate)} годовых · погашение в месяц {c.maturity_month} · {c.status==='active'?'Действует':c.status==='due'?'Наступил срок погашения':'Погашен'}</small></span><strong>{billions(c.principal*(c.source_key==='external'?calc.fx/state.anchor.fx_rate:1))}</strong>{c.status!=='paid'&&canPrepare&&!readOnly&&<button type="button" className="secondary" disabled={busy} onClick={()=>void repay(c.id)}>Погасить из резерва</button>}</article>)}{g.teacher&&!readOnly&&<button type="button" className="secondary" onClick={()=>void advance()} disabled={busy||!state.last_plan_id}><Clock size={18}/> Следующий финансовый месяц</button>}{eventCount>0&&<button type="button" className="secondary" onClick={onOpenEvents}><ArrowRight size={18}/> Финансовые события · {eventCount}</button>}</details>
   </div>}
   {tab==='law'&&<div className={styles.panel}>
    <h3>5. Подготовьте проект федерального закона</h3><p>В проект и его приложения попадут именно эти расчёты: ставки и базы доходов, расходы по разделам, программы, мероприятия, выбранные региональные заявки и источники финансирования.</p>
    <div className={styles.lawChecklist}><p><b>Доходы:</b> {moneyMillions(calc.revenue)} · {(calc.income_details||[]).length} статей</p><p><b>Расходы:</b> {moneyMillions(calc.expenditure)} · {draft.expense_items?.length||0} программ и мероприятий · {draft.transfer_ids.length} региональных заявок</p><p><b>Непокрытая потребность:</b> {moneyMillions(calc.funding_gap)}</p><p><b>Доступный резерв после решения:</b> {moneyMillions(calc.reserve_remaining)}</p></div>
    <label>Обоснование и приоритеты проекта<textarea rows={4} value={draft.note} maxLength={12000} onChange={e=>edit({note:e.target.value})} disabled={readOnly} placeholder="Обоснуйте прогноз доходов, новые расходы, выбор заявок и источников покрытия дефицита."/></label>
    <div className={styles.actions}><button type="button" className="primary" onClick={()=>void document()} disabled={busy||readOnly||!canPrepare||calc.funding_gap>0||calc.reserve_remaining<0||draft.note.trim().length<30}><FileText size={18}/> {selected?.document_id&&!dirty?'Открыть проект в реестре':'Создать проект ФЗ о бюджете'}</button></div>
    <p>{calc.funding_gap>0?'Вернитесь к балансу и покройте всю потребность в финансировании.':calc.reserve_remaining<0?'Использование резерва превышает доступную сумму.':draft.note.trim().length<30?'Добавьте обоснование от 30 символов.':'Расчёт готов для формирования проекта. Создание документа не перечисляет средства.'}</p>
    <h4>Как закон принимается в игре</h4><ol className={styles.lawSteps}><li><b>Правительство и внесение.</b> Коллегиальное решение, предварительные заключения и регистрация проекта в реестре НПА.</li><li><b>Бюджетный комитет.</b> Проверка пакета документов и заключения комитетов и Счётной палаты.</li><li><b>Первое чтение ГД.</b> Основные характеристики: доходы, расходы, дефицит и источники его покрытия.</li><li><b>Второе чтение ГД.</b> Таблицы поправок, отдельные голосования и распределение ассигнований.</li><li><b>Третье чтение ГД.</b> Голосование за проект в целом на зарегистрированном заседании.</li><li><b>Совет Федерации, Президент и опубликование.</b> После опубликования исполняются утверждённые трансферты и долговые решения.</li></ol>
    <details className={styles.requestForm}><summary>Предложения фракций к распределению расходов</summary><p>Предварительные предложения помогают собрать расчёт. Обязательное второе чтение закона и голосование за его поправки проводятся в реестре НПА на заседании ГД.</p><BudgetAmendments g={g} plans={plans} selectedId={selectedId} state={state} context={context} regions={regions} rates={rates} requests={requests} readOnly={readOnly} onOpenVotes={onOpenVotes} onOpenDocument={onOpenDocument} onOpenCalculator={()=>setTab('expense')} onApplied={async r=>{setDraft(r.draft);setSelectedId(r.id);setRevision(r.revision);setDirty(false);await Promise.all([load(),onSaved(),g.refreshBudgetPulse?.()]);}}/></details>
   </div>}
   </div>
   <footer className={styles.submission}><div className={styles.actions}><button type="button" className="secondary" disabled={tab===tabs[0][0]} onClick={()=>setTab(tabs[Math.max(0,tabs.findIndex(x=>x[0]===tab)-1)][0])}>Предыдущий шаг</button><button type="button" className="secondary" onClick={()=>void save()} disabled={busy||readOnly||!canPrepare}><Save size={18}/> Сохранить общий расчёт</button>{tab!==tabs[tabs.length-1][0]&&<button type="button" className="primary" onClick={()=>setTab(tabs[Math.min(tabs.length-1,tabs.findIndex(x=>x[0]===tab)+1)][0])}>Следующий шаг <ArrowRight size={18}/></button>}</div><p>{!canPrepare?'Рассчитывать и сравнивать может каждый. Общий проект подготавливают уполномоченные участники бюджетного процесса.':'Сохранение фиксирует общий проект для группы. Действующий бюджет меняется после принятия и опубликования закона.'}</p></footer>
    {plans.length===1&&plans[0].id!==selectedId&&<div className={styles.currentProject} aria-label="Текущий проект бюджета"><div><FileText size={18}/><span><b>{plans[0].title}</b><small>{plans[0].status==='published'?'Закон опубликован':plans[0].status==='document'?'Проект в реестре НПА':'Общий черновик'} · версия {plans[0].revision}</small></span></div><div className={styles.actions}><button type="button" className="secondary" onClick={()=>openPlan(plans[0])}>Открыть расчёт</button>{plans[0].document_id&&<button type="button" className="secondary" onClick={()=>onOpenDocument(plans[0].document_id!)}><FileText size={18}/> Открыть документ</button>}</div></div>}
    {plans.length>1&&<details className={styles.saved}><summary><FileText size={18}/> История расчётов и проектов ФЗ · {plans.length}</summary>{plans.map(p=><article key={p.id}><span><b>{p.title}</b><small>{p.status==='published'?'Опубликован':p.status==='document'?'Проект в реестре':'Черновик'} · версия {p.revision}</small></span><button type="button" className="secondary" onClick={()=>openPlan(p)}>Открыть расчёт</button>{p.document_id&&<button type="button" className="secondary" onClick={()=>onOpenDocument(p.document_id!)}><FileText size={18}/> {p.registry_no||'НПА'}</button>}</article>)}</details>}
   <details className={styles.sources}><summary>Методология и источники данных</summary><p><a href={baseline.source_url} target="_blank" rel="noreferrer">{baseline.source_label} ↗</a>. {baseline.baseline_kind}. Проверено 2 октября 2026 года. Это исходный план для обучения, а не онлайн-данные об исполнении.</p><p><a href={baseline.revenue_source_url} target="_blank" rel="noreferrer">Группы доходов: таблица 4.1.2 документа Минфина ↗</a>. Нефтегазовые и ненефтегазовые группы не пересекаются. Страховые взносы внебюджетных фондов не добавляются к федеральным доходам.</p><p>Исходные параметры модели: ключевая ставка {pct(state.anchor.key_rate)}, курс {state.anchor.fx_rate} ₽/доллар, нефть {state.anchor.oil_price} долларов/баррель, инфляция {pct(state.anchor.inflation)}. Официальный исходный макропрогноз: нефть {baseline.macro_reference.oil_price} долларов/баррель, курс {baseline.macro_reference.fx_rate} ₽/доллар, инфляция {pct(baseline.macro_reference.inflation)}. Различия отражают текущие решения и изменения экономического сценария.</p><p>Баланс = доходы − расходы. Дефицит = max(0; расходы − доходы). Потребность в финансировании = дефицит + новые бюджетные кредиты регионам. Проценты входят в расходы; основной долг и приватизация акций — в источники финансирования. Валютный долг пересчитывается по курсу.</p><p>Внутренний долг на начало 2026 года: {billions(baseline.internal_debt_start)}; внешний: {billions(baseline.external_debt_start)}. Прочие расчетные движения исходного плана: {billions(baseline.internal_debt_other_movement)} и {billions(baseline.external_debt_other_movement)}. Это позволяет сверить конечный долг с опубликованным прогнозом без приравнивания долга к одному дефициту.</p><ul>{baseline.assumptions.map(s=><li key={s}>{s}</li>)}</ul><p>{baseline.reserve_note}</p></details>
   {ledger.filter(e=>e.kind==='publication_blocked'&&plans.some(p=>p.status!=='published'&&e.source_key==='blocked:'+p.id)).map(e=><p key={e.id} role="alert" className={styles.error}>{e.note} Откройте проект в реестре и подготовьте расчет поправок с учетом действующего бюджета.</p>)}
   {ledger.length>0&&<details className={styles.journal}><summary><Clock size={18}/> История исполнения бюджета · {ledger.length}</summary>{ledger.length?ledger.map(e=><article key={e.id}><time>{new Date(e.created_at).toLocaleString('ru-RU')}</time><span>{e.note}</span>{e.amount!==null&&<b>{billions(e.amount)}</b>}</article>):<p>Записи появятся после сохранения проекта, опубликования бюджета, перечисления поддержки и финансовых событий.</p>}</details>}
  </>}
  {error&&state&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status" className={styles.notice}>{notice}</p>}
 </section>;
}
