'use client';
import {useState} from 'react';
import {FilePlus2,Search,X} from 'lucide-react';
import {useDialog} from '../ui/useDialog';
import type {FormalDocument} from './types';
export default function FormalDocumentPicker({documents,value,onChange,multiple=true,label='Добавить НПА из реестра'}:{documents:FormalDocument[];value:string[];onChange:(ids:string[])=>void;multiple?:boolean;label?:string}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState('');const dialog=useDialog(open,()=>setOpen(false));
 const visible=documents.filter(d=>[d.registry_no,d.title,d.subject_label,d.status_label].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 return <div className="npaPicker"><button type="button" className="secondary" onClick={()=>setOpen(true)}><FilePlus2 size={18}/>{label}{value.length>0&&<b>{value.length}</b>}</button>{value.map(id=>{const d=documents.find(d=>d.id===id);return d&&<div className="npaPicked" key={id}><span><b>{d.registry_no}</b> {d.title}</span><button type="button" aria-label={'Убрать '+d.title} onClick={()=>onChange(value.filter(x=>x!==id))}><X size={18}/></button></div>})}{open&&<div className="eventCaseBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="eventCaseModal npaPickerDialog" ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Выбрать НПА из реестра"><header className="eventModalHeader"><h3>Документы из реестра НПА</h3><button className="eventModalClose" aria-label="Закрыть выбор документов" onClick={()=>setOpen(false)}><X size={20}/></button></header><div className="eventModalBody"><label className="npaPickerSearch"><Search size={18}/><input autoFocus type="search" aria-label="Поиск НПА" placeholder="Номер, название, орган или статус" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="npaPickerList">{visible.map(d=><button type="button" key={d.id} aria-pressed={value.includes(d.id)} onClick={()=>{onChange(multiple?(value.includes(d.id)?value.filter(x=>x!==d.id):[...value,d.id]):[d.id]);if(!multiple)setOpen(false)}}><span><small>{d.registry_no} · {d.subject_label}</small><b>{d.title}</b><small>{d.status_label}</small></span><span>{value.includes(d.id)?'Выбран':'Выбрать'}</span></button>)}{!visible.length&&<p>Документы не найдены.</p>}</div></div><footer><button className="primary" onClick={()=>setOpen(false)}>Готово · Выбрано {value.length}</button></footer></section></div>}</div>;
}
