'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import type {ReturnTypeRepublic} from './viewTypes';
import StyledSelect from '../ui/StyledSelect';
import {VOTING_BODIES,bodyQuorum,type VotingUnit} from './votingBodies';
import {ClipboardCheck} from 'lucide-react';
import DisclosureSummary from '../ui/DisclosureSummary';
type Entry={user_id:string;institution_key:string;stage_no:number};
type Assignment={unit_id:string;user_id:string};
type Office={user_id:string;role_title:string};
export default function InstitutionRegistrationPanel({g,readOnly=false,onUnitsChange,stageNo,initialBody,allowedBodies}:{g:ReturnTypeRepublic;readOnly?:boolean;onUnitsChange?:(units:VotingUnit[])=>void;stageNo?:number;initialBody?:string;allowedBodies?:string[]}){
 const [rows,setRows]=useState<Entry[]>([]),[units,setUnits]=useState<VotingUnit[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[offices,setOffices]=useState<Office[]>([]);
 const [body,setBody]=useState(initialBody||'gd'),[group,setGroup]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[newTitle,setNewTitle]=useState(''),[users,setUsers]=useState<string[]>([]),[head,setHead]=useState('');
 const [seats,setSeats]=useState('1'),[editing,setEditing]=useState<string|null>(null);
 const stage=stageNo||g.game?.current_round||1,students=g.members.filter(m=>m.kind==='student'),groups=[...new Set(students.map(m=>m.group_name).filter((s):s is string=>!!s))];
 async function load(){if(!g.game)return;const [r,u,a,b,o]=await Promise.all([supabase.from('institution_session_registrations').select('user_id,institution_key,stage_no').eq('game_id',g.game.id).eq('stage_no',stage),supabase.from('institution_units').select('id,title,unit_kind,head_user_id,unit_key,mandate_capacity').eq('game_id',g.game.id),supabase.from('institution_assignments').select('unit_id,user_id').eq('game_id',g.game.id),supabase.from('game_voting_body_members').select('unit_id,user_id').eq('game_id',g.game.id),supabase.from('game_office_assignments').select('user_id,role_title').eq('game_id',g.game.id).eq('status','active')]);
  if(!r.error)setRows(r.data||[]);if(!u.error){setUnits(u.data||[]);onUnitsChange?.(u.data||[])}setAssignments([...(a.data||[]),...(b.data||[])]);if(!o.error)setOffices(o.data||[]);
 }
 useEffect(()=>{if(!g.game)return;void load();const channel=supabase.channel('civic-registration:'+g.game.id).on('postgres_changes',{schema:'public',table:'institution_session_registrations',event:'*',filter:'game_id=eq.'+g.game.id},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[g.game?.id,stage]);
 if(!g.game||!g.me)return null;
 const availableBodies=VOTING_BODIES.filter(item=>!allowedBodies||allowedBodies.includes(item.key));
 const config=VOTING_BODIES.find(b=>b.key===body),unit=units.find(u=>'unit:'+u.id===body);
 function eligible(uid:string){const m=g.members.find(x=>x.user_id===uid);if(!m||m.kind==='observer')return false;if(unit)return assignments.some(a=>a.unit_id===unit.id&&a.user_id===uid);if(body==='ksrf')return g.parties.some(p=>p.leader_user_id===uid);return !!config&&(config.role.test(m.role_title||'')||offices.some(o=>o.user_id===uid&&config.role.test(o.role_title)))}
 const participants=students.filter(m=>(body==='ksrf'||!group||m.group_name===group)&&eligible(m.user_id));
 const registered=rows.filter(r=>r.institution_key===body&&participants.some(m=>m.user_id===r.user_id));
 const mine=rows.some(r=>r.institution_key===body&&r.user_id===g.me?.user_id);
 const factionCount=body==='ksrf'?g.parties.length:0;
 const total=body==='ksrf'?factionCount:body==='gd'?450:['government','municipality'].includes(body)?students.filter(m=>!group||m.group_name===group).length:unit?.mandate_capacity??participants.length;
 const present=body==='ksrf'?new Set(registered.map(r=>g.parties.find(p=>p.leader_user_id===r.user_id)?.id).filter(Boolean)).size:body==='gd'?registered.reduce((n,r)=>n+(g.partyMandates.find(a=>a.user_id===r.user_id)?.effective_mandates||0),0):registered.length;
 const needed=bodyQuorum(body,total);
 async function register(){if(!g.game)return;setBusy(true);const r=await supabase.rpc('register_institution_session_at_stage',{p_game_id:g.game.id,p_institution:body,p_stage_no:stage});if(r.error)g.setError(r.error.message);else{await load();setNotice('Вы зарегистрированы на заседание.')}setBusy(false)}
 async function createBody(){if(!g.game)return;setBusy(true);const r=await supabase.rpc('save_civic_voting_body',{p_game_id:g.game.id,p_title:newTitle.trim(),p_seats:Number(seats),p_users:users,p_head:head||null,p_unit:editing});if(r.error)g.setError(r.error.message);else{await load();setBody('unit:'+r.data);setNewTitle('');setUsers([]);setHead('');setSeats('1');setEditing(null);setNotice('Состав органа сохранён. Его можно выбрать при открытии голосования.')}setBusy(false)}
 return <details className="institutionRegistrationPanel civicRegistration civicDisclosure projectDisclosure" aria-label="Регистрация на заседания"><DisclosureSummary icon={ClipboardCheck} title="Регистрация на заседание" description={'Этап '+stage+' · Орган власти и учебная группа'}/><div className="civicDisclosureBody"><p>Присутствие и поданные голоса учитываются отдельно. Выберите орган и учебную группу.</p>
  <div className="civicRegistrationSelectors"><StyledSelect label="Орган" value={body} onChange={setBody} options={[...availableBodies.map(b=>({value:b.key,label:b.title})),...units.filter(u=>!allowedBodies||allowedBodies.includes('unit:'+u.id)).map(u=>({value:'unit:'+u.id,label:u.title}))]}/>{body!=='ksrf'&&<StyledSelect label="Учебная группа" value={group} onChange={setGroup} options={[{value:'',label:'Все группы'},...groups.map(s=>({value:s,label:s}))]}/>}</div>
  <div className="civicAttendance"><div><h3>{config?.title||unit?.title}</h3><p>{config?.basis||'Состав зарегистрированного в игре органа. Порог задаётся в голосовании.'}</p></div><div className="civicAttendanceNumbers"><span>Присутствует <b>{present} / {total}</b></span><span>Для кворума <b>{needed}</b></span><span>{present>=needed&&total>0?'Кворум есть':'Ожидаем участников'}</span></div><ul className="civicAttendees">{registered.map(r=>{const faction=body==='ksrf'?g.parties.find(p=>p.leader_user_id===r.user_id):null;return <li key={r.user_id}>{body==='ksrf'?(faction?.name||'Фракция')+' · '+(g.names[r.user_id]||'Представитель'):g.names[r.user_id]||'Участник'}<b>{body==='gd'?(g.partyMandates.find(a=>a.user_id===r.user_id)?.effective_mandates||0)+' голосов':body==='ksrf'?'1 голос':'1 голос'}</b></li>})}</ul><button type="button" className="primary" disabled={mine||!eligible(g.me.user_id)||busy||readOnly} onClick={()=>void register()}>{mine?'Вы зарегистрированы':eligible(g.me.user_id)?'Зарегистрироваться':'Нет назначения в этот орган'}</button></div>
  {g.teacher&&unit?.unit_kind==='public_body'&&<button className="secondary" onClick={()=>{setEditing(unit.id);setNewTitle(unit.title);setSeats(String(unit.mandate_capacity||1));setUsers(assignments.filter(a=>a.unit_id===unit.id).map(a=>a.user_id));setHead(unit.head_user_id||'');document.getElementById('civic-body-editor')?.setAttribute('open','')}}>Изменить состав выбранного органа</button>}
  {g.teacher&&<details id="civic-body-editor" className="civicCustomBody"><summary>Добавить другой орган или комиссию</summary><div className="civicBodyEditor"><label>Название органа<input value={newTitle} onChange={e=>setNewTitle(e.target.value)}/></label><label>Установленный состав органа, мест<input type="number" aria-label="Установленный состав органа" min={1} max={10000} step={1} inputMode="numeric" value={seats} onChange={e=>setSeats(e.target.value)}/></label><p>Назначено {users.length} из {seats||0} мест. Свободные места учитываются в общем составе при расчёте кворума.</p><fieldset><legend>Назначенные участники · {users.length}</legend>{students.map(m=><label className="civicCheckbox" key={m.user_id}><input type="checkbox" checked={users.includes(m.user_id)} onChange={e=>{setUsers(old=>e.target.checked?[...old,m.user_id]:old.filter(id=>id!==m.user_id));if(head===m.user_id&&!e.target.checked)setHead('')}}/>{m.full_name}</label>)}</fieldset><StyledSelect label="Председатель" value={head} onChange={setHead} options={[{value:'',label:'Не назначен'},...students.filter(m=>users.includes(m.user_id)).map(m=>({value:m.user_id,label:m.full_name}))]}/><button type="button" className="primary" disabled={busy||readOnly||newTitle.trim().length<3||!Number.isInteger(Number(seats))||Number(seats)<Math.max(1,users.length)||Number(seats)>10000} onClick={()=>void createBody()}>{editing?'Сохранить состав':'Создать орган'}</button></div></details>}
  {notice&&<p role="status">{notice}</p>}
 </div></details>;
}
