'use client';
import {useState} from 'react';
import StyledSelect from '../ui/StyledSelect';
import JusticeDocuments from './JusticeDocuments';
import InstitutionEmblemImage from './InstitutionEmblemImage';
import {institutionEmblem} from './institutionEmblems';
import type {Party} from './types';
import type {ReturnTypeRepublic} from './viewTypes';
export default function PartyJusticeReview({g,party}:{g:ReturnTypeRepublic;party:Party}){
 const [decision,setDecision]=useState<'registered'|'revision'|'rejected'>('registered'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const docs=g.partyDocuments.filter(d=>d.party_id===party.id),leader=g.members.find(m=>m.user_id===party.leader_user_id);
 const ready=['application','charter','program','fee','symbol','congress_minutes'].every(k=>docs.some(d=>d.doc_kind===k&&d.status==='accepted'));
 function draft(){setNote('Уважаемый(ая) '+(leader?.full_name||'председатель партии')+'!\n\nМинистерство юстиции Российской Федерации рассмотрело документы политической партии «'+party.name+'».\n\n'+(decision==='registered'?'Принято решение о регистрации партии в деловой игре. Свидетельство о регистрации направляется автоматически.':decision==='revision'?'Регистрационный пакет возвращается на доработку. Необходимо устранить следующие замечания:\n[Укажите документ, нарушение и требуемое исправление]':'Принято решение об отказе в регистрации. Основания отказа:\n[Укажите установленные нарушения и соответствующие нормы]')+'\n\nПредставленные документы:\n'+docs.map(d=>'• '+d.title+' — '+d.file_name).join('\n')+'\n\nИдеология: '+(party.ideology||'Не указана')+'.\nРегиональные отделения: '+party.regions+'.')}
 async function send(){setBusy(true);setNotice('');try{if(await g.reviewPartyRegistration(party.id,decision,note))setNotice('Ответ подписан и направлен партии. Публикация добавлена в политические процессы.')}finally{setBusy(false)}}
 return <section className="justiceReview"><header><InstitutionEmblemImage src={institutionEmblem('minjust','Министерство юстиции Российской Федерации')} width={48} height={48} alt="Эмблема Минюста"/><div><h4>Министерство юстиции</h4><p>Ответ по регистрационному пакету «{party.name}»</p></div></header><StyledSelect label="Решение по заявлению" value={decision} onChange={v=>setDecision(v as typeof decision)} options={[{value:'registered',label:'Зарегистрировать партию'},{value:'revision',label:'Вернуть на доработку'},{value:'rejected',label:'Отказать в регистрации'}]}/><button type="button" className="secondary" onClick={draft}>Подготовить ответ по данным партии</button><label>Текст официального ответа<textarea rows={8} value={note} onChange={e=>setNote(e.target.value)} placeholder="Подготовьте ответ и укажите основания принятого решения"/></label>{decision==='registered'&&!ready&&<p>Для регистрации примите каждый обязательный документ в списке выше.</p>}<button type="button" className="primary" disabled={busy||note.trim().length<10||note.includes('[Укажите')||(decision==='registered'&&!ready)} onClick={()=>void send()}>{busy?'Направляется…':'Подписать и направить от имени Минюста'}</button>{notice&&<p role="status">{notice}</p>}<JusticeDocuments g={g} partyId={party.id}/></section>;
}
