'use client';
import {useState} from 'react';
import type {ReturnTypeRepublic} from './viewTypes';

export default function PartiesView({g}:{g:ReturnTypeRepublic}){
 const {parties,members,teacher,createParty,updateParty,assignParty}=g;
 const [name,setName]=useState(''),[ideology,setIdeology]=useState('');
 async function create(){if(await createParty(name,ideology)){setName('');setIdeology('')}}
 return <><section className="pageHeader"><div><small>ПАРТИИ И ФРАКЦИИ</small><h1>Политическая карта</h1><p>Электоральная поддержка, мандаты, контроль регионов, партийный бюджет, председатели и закрытые фракционные каналы.</p></div></section>
 {teacher&&<section className="surface compactForm"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Название новой партии"/><input value={ideology} onChange={e=>setIdeology(e.target.value)} placeholder="Идеология"/><button className="primary" onClick={create}>Создать партию</button></section>}
 <section className="partyGrid">{parties.length===0?<div className="emptyState">Партии ещё не созданы. Начните с учредительного этапа.</div>:parties.map(p=><article className="partyCard" key={p.id} style={{borderTopColor:p.color}}><div className="partyTitle"><span style={{background:p.color}}/><div><small>{p.ideology||'Идеология не указана'}</small><h3>{p.name}</h3></div></div><div className="partyStats"><div><span>Поддержка</span><b>{p.support}%</b></div><div><span>Мандаты</span><b>{p.mandates}</b></div><div><span>Регионы</span><b>{p.regions}</b></div><div><span>Бюджет</span><b>{p.budget}</b></div></div><div className="supportBar"><i style={{width:`${p.support}%`,background:p.color}}/></div>{teacher&&<div className="partyControls"><label>Поддержка<input type="number" min="0" max="100" value={p.support} onChange={e=>updateParty(p.id,{support:+e.target.value})}/></label><label>Мандаты<input type="number" min="0" value={p.mandates} onChange={e=>updateParty(p.id,{mandates:+e.target.value})}/></label><label>Регионы<input type="number" min="0" value={p.regions} onChange={e=>updateParty(p.id,{regions:+e.target.value})}/></label><label>Бюджет<input type="number" value={p.budget} onChange={e=>updateParty(p.id,{budget:+e.target.value})}/></label><label className="partyLeader">Председатель<select value={p.leader_user_id||''} onChange={e=>updateParty(p.id,{leader_user_id:e.target.value||null})}><option value="">Не назначен</option>{members.filter(m=>m.kind!=='teacher'&&m.team===p.name).map(m=><option key={m.user_id} value={m.user_id}>{m.full_name}</option>)}</select></label></div>}</article>)}</section>
 {teacher&&<section className="surface"><div className="surfaceHead"><div><small>СОСТАВ</small><h2>Распределение участников</h2></div></div><div className="memberRows">{members.filter(m=>m.kind!=='teacher').map(m=><div key={m.user_id}><b>{m.full_name}</b><span>{m.role_title||'Участник'}</span><select value={m.team||''} onChange={e=>assignParty(m.user_id,e.target.value)}><option value="">Без партии</option>{parties.map(p=><option key={p.id} value={p.name}>{p.name}</option>)}</select></div>)}</div></section>}</>
}