'use client';
import JusticeDocuments from './JusticeDocuments';
import {useMemo,useState,type ComponentType} from 'react';
import {IconAction} from '../ui/IconAction';
import {ChevronDown,FileText,PencilLine,Plus,UserPlus,UsersRound} from 'lucide-react';
import StyledSelect from '../ui/StyledSelect';
import ProfileAvatar from './ProfileAvatar';
import type {PartyDocument} from './types';
import type {ReturnTypeRepublic} from './viewTypes';
const DOCS:{kind:PartyDocument['doc_kind'];title:string;template:string}[]=[{kind:'application',title:'Заявление о регистрации',template:'party_application'},{kind:'charter',title:'Устав',template:'party_charter'},{kind:'program',title:'Программа',template:'party_program'},{kind:'fee',title:'Сведения об уплате госпошлины',template:'party_fee'},{kind:'symbol',title:'Символика',template:'party_symbol'},{kind:'congress_minutes',title:'Учредительный съезд',template:'party_congress'}];
const statusLabel:Record<string,string>={registered:'Зарегистрирована',submitted:'На регистрации',draft:'Пакет готовится',revision:'На доработке',rejected:'Регистрация отклонена'};
function PartyDisclosureSummary({icon:Icon,title,meta}:{icon:ComponentType<{size?:number}>;title:string;meta?:string}){
 return <summary className="civicPartyDisclosureSummary"><span className="civicPartyDisclosureIcon" aria-hidden="true"><Icon size={20}/></span><span className="civicPartyDisclosureText"><b>{title}</b>{meta&&<small>{meta}</small>}</span><span className="civicPartyDisclosureChevron" aria-hidden="true"><ChevronDown size={19}/></span></summary>;
}
export default function PartiesView({g}:{g:ReturnTypeRepublic}){
 const {parties,members,profiles,partyDocuments,partyInvitations,partyMandates,me,teacher}=g;
 const [selectedId,setSelectedId]=useState(''),[query,setQuery]=useState(''),[description,setDescription]=useState(''),[logo,setLogo]=useState<File|null>(null),[busy,setBusy]=useState(false),[docKind,setDocKind]=useState<PartyDocument['doc_kind']>('application'),[docFile,setDocFile]=useState<File|null>(null),[docTitle,setDocTitle]=useState(''),[inviteUser,setInviteUser]=useState(''),[name,setName]=useState(''),[ideology,setIdeology]=useState('');
 const ranked=useMemo(()=>[...parties].filter(p=>!query.trim()||[p.name,p.ideology,p.description].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.support-a.support),[parties,query]);
 const selected=parties.find(p=>p.id===selectedId)||parties.find(p=>p.name===me?.team)||ranked[0],own=!!selected&&(teacher||selected.name===me?.team),editable=!!selected&&(teacher||selected.leader_user_id===me?.user_id),staff=members.filter(m=>m.kind==='student'&&m.team===selected?.name),leader=members.find(m=>m.user_id===selected?.leader_user_id),docs=partyDocuments.filter(d=>d.party_id===selected?.id),publicDocs=docs.filter(d=>['charter','program','symbol','congress_minutes'].includes(d.doc_kind)&&d.status!=='revision'),free=members.filter(m=>m.kind==='student'&&!m.team),pending=partyInvitations.filter(i=>i.party_id===selected?.id&&i.status==='pending'),inbox=partyInvitations.filter(i=>i.invited_user_id===me?.user_id&&i.status==='pending');
 async function saveIdentity(){if(!selected)return;setBusy(true);await g.savePartyIdentity(selected.id,description,logo||undefined);setLogo(null);setBusy(false)}
 async function upload(){if(!selected||!docFile)return;setBusy(true);const ok=await g.uploadPartyDocument(selected.id,docKind,docTitle.trim()||DOCS.find(d=>d.kind===docKind)?.title||docFile.name,docFile);if(ok){setDocFile(null);setDocTitle('')}setBusy(false)}

 return <div className="partyPage civicParties"><header className="pageHeader"><div><h1>Партии и фракции</h1><p>Публичные программы, партийные документы, руководство и состав.</p></div></header>
  {inbox.length>0&&<section className="civicPartyInbox"><h2>Приглашения в партии</h2>{inbox.map(i=><article key={i.id}><b>{parties.find(p=>p.id===i.party_id)?.name||'Партия'}</b><button className="primary" onClick={()=>void g.respondPartyInvitation(i.id,true)}>Принять</button><button className="secondary" onClick={()=>void g.respondPartyInvitation(i.id,false)}>Отклонить</button></article>)}</section>}
  <input className="civicPartySearch" aria-label="Поиск партий" placeholder="Название, идеология или программа" value={query} onChange={e=>setQuery(e.target.value)}/>
  <section className="civicPartyTiles" aria-label="Публичные партии">{ranked.map(p=><button type="button" className={selected?.id===p.id?'civicPartyTile active':'civicPartyTile'} key={p.id} onClick={()=>{setSelectedId(p.id);setDescription(p.description||'')}}><span className="civicPartyLogo" style={{background:p.color}}>{p.logo_url?<img src={p.logo_url} alt=""/>:p.name.slice(0,1)}</span><span><b>{p.name}</b><small>{p.ideology||'Идеология не указана'}</small><small>{statusLabel[p.registration_status]}</small></span><span className="civicPartyTileStats"><b>{p.support}%</b> поддержка · <b>{p.mandates}</b> мандатов</span></button>)}{!ranked.length&&<p>Партии не найдены.</p>}</section>
  {selected&&<section className="civicPartyPublic"><header><span className="civicPartyLogo" style={{background:selected.color}}>{selected.logo_url?<img src={selected.logo_url} alt={'Эмблема: '+selected.name}/>:selected.name.slice(0,1)}</span><div><h2>{selected.name}</h2><p>{selected.ideology||'Идеология не указана'}</p></div><span>{statusLabel[selected.registration_status]}</span></header><p className="civicPartyDescription">{selected.description||'Публичное описание пока не опубликовано.'}</p><div className="civicPartyFacts"><span><b>{selected.support}%</b> поддержка</span><span><b>{selected.mandates}</b> мандатов</span><span><b>{selected.regions}</b> регионов</span><span><b>{staff.length}</b> участников</span></div>
   <div className="civicPartyLeader"><span className="eventVoter"><ProfileAvatar name={leader?.full_name||'Не назначен'} src={profiles.find(p=>p.user_id===leader?.user_id)?.avatar_url}/></span><div><small>Председатель партии</small><b>{leader?.full_name||'Не назначен'}</b></div></div>
   <section className="civicPublicDocs"><h3>Публичные документы</h3>{publicDocs.length?publicDocs.map(d=><a key={d.id} href={d.url||undefined} target="_blank" rel="noreferrer"><div><b>{DOCS.find(x=>x.kind===d.doc_kind)?.title||d.title}</b><span>{d.title}</span><small>{d.file_name}</small></div><span>Открыть</span></a>):<p>Устав, программа и решения съезда появятся после загрузки партийного пакета.</p>}</section>
   <details className="civicPartyRoster"><PartyDisclosureSummary icon={UsersRound} title="Состав партии" meta={staff.length+' участников'}/><ul>{staff.map(m=><li key={m.user_id}><span className="eventVoter"><ProfileAvatar name={m.full_name} src={profiles.find(p=>p.user_id===m.user_id)?.avatar_url}/></span><div><b>{m.full_name}</b><small>{m.role_title||'Студент'}</small></div><span>{partyMandates.find(a=>a.user_id===m.user_id)?.base_mandates||0} мандатов</span></li>)}</ul></details>
   {editable&&<details className="civicPartyEditor"><PartyDisclosureSummary icon={PencilLine} title="Редактировать публичное описание" meta="Публичная карточка партии"/><label>Описание<textarea rows={4} value={description||selected.description||''} onChange={e=>setDescription(e.target.value)}/></label><label>Эмблема<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setLogo(e.target.files?.[0]||null)}/></label><button className="primary" disabled={busy} onClick={()=>void saveIdentity()}>Сохранить</button></details>}
   <JusticeDocuments g={g} partyId={selected.id}/>
   {own&&<details className="civicPartyPackage"><PartyDisclosureSummary icon={FileText} title="Документы и регистрация партии" meta={docs.length+' файлов'}/><p>{selected.registration_note||'Подготовьте документы. Преподаватель увидит загруженные файлы в управлении фракциями.'}</p><div className="civicPartyFiles">{docs.map(d=><article key={d.id}><a href={d.url||undefined} target="_blank" rel="noreferrer">{d.title}<small>{d.file_name} · {d.status==='accepted'?'Принят':d.status==='revision'?'На доработке':'Загружен'}</small></a>{d.note&&<p>{d.note}</p>}</article>)}</div>{editable&&<div className="civicPartyUpload"><StyledSelect label="Вид документа" value={docKind} onChange={v=>setDocKind(v as PartyDocument['doc_kind'])} options={DOCS.map(d=>({value:d.kind,label:d.title}))}/><div className="partyLegalRequirements"><a className="secondary" href="https://pravo.gov.ru/proxy/ips/?docbody=&nd=102071991" target="_blank" rel="noreferrer">Требования к документу · Закон № 95-ФЗ</a><a href="https://minjust.gov.ru/ru/documents/7719/" target="_blank" rel="noreferrer">Официальные формы Минюста · Приказ № 333</a><small>{docKind==='charter'?'Статья 21: содержание устава.':docKind==='program'?'Статья 22: программа партии.':docKind==='symbol'?'Статья 7: символика партии.':docKind==='fee'?'Статья 16: документ об уплате госпошлины. Размер и льготы — статья 333.33 НК РФ.':docKind==='congress_minutes'?'Статьи 11 и 16: учредительный съезд и протокол.':'Статья 16: заявление и регистрационный пакет. Формы утверждены приказом Минюста от 12.11.2024 № 333.'}</small></div><label>Название<input value={docTitle} onChange={e=>setDocTitle(e.target.value)}/></label><label>Файл<input type="file" accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg,.webp" onChange={e=>setDocFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={busy||!docFile} onClick={()=>void upload()}>Загрузить документ</button><button className="secondary" disabled={busy||!DOCS.every(req=>docs.some(d=>d.doc_kind===req.kind))} onClick={()=>void g.submitPartyRegistration(selected.id)}>Направить на регистрацию</button></div>}</details>}
   {editable&&<details className="civicPartyEditor"><PartyDisclosureSummary icon={UserPlus} title="Пригласить участника" meta="Управление составом"/><StyledSelect label="Студент" value={inviteUser} onChange={setInviteUser} options={[{value:'',label:'Выберите участника'},...free.map(m=>({value:m.user_id,label:m.full_name}))]}/><button className="primary" disabled={!inviteUser||busy} onClick={async()=>{setBusy(true);if(await g.inviteToParty(selected.id,inviteUser))setInviteUser('');setBusy(false)}}>Пригласить</button>{pending.map(i=><div className="civicPendingInvite" key={i.id}><span>{g.names[i.invited_user_id]}</span><IconAction variant="remove" label="Отменить приглашение" onClick={()=>void g.cancelPartyInvitation(i.id)}/></div>)}</details>}
  </section>}
  {teacher&&<details className="civicPartyEditor"><PartyDisclosureSummary icon={Plus} title="Создать партию" meta="Новая политическая организация"/><label>Название<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Идеология<input value={ideology} onChange={e=>setIdeology(e.target.value)}/></label><button className="primary" disabled={!name.trim()} onClick={async()=>{if(await g.createParty(name,ideology)){setName('');setIdeology('')}}}>Создать</button></details>}
 </div>;
}
