'use client';
import {useEffect,useState} from 'react';
import type {Party} from './types';
import type {ReturnTypeRepublic} from './viewTypes';
import StyledSelect from '../ui/StyledSelect';
export default function PartyMandateEditor({g,party}:{g:ReturnTypeRepublic;party:Party}){
 const staff=g.members.filter(m=>m.kind==='student'&&m.team===party.name),[draft,setDraft]=useState<Record<string,number>>({}),[total,setTotal]=useState(party.mandates),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{setTotal(party.mandates);setDraft(Object.fromEntries(staff.map(m=>[m.user_id,g.partyMandates.find(a=>a.party_id===party.id&&a.user_id===m.user_id)?.base_mandates||0])))},[party.mandates,party.id,g.partyMandates,g.members]);
 const sum=Object.values(draft).reduce((n,v)=>n+v,0),valid=Object.values(draft).every(v=>Number.isInteger(v)&&v>=0)&&sum===party.mandates,frozen=g.votes.some(v=>v.status==='open'&&v.institution_key==='gd');
 async function save(reset=false){setBusy(true);if(await g.setStudentMandates(party.id,reset?null:draft))setNotice(reset?'Мандаты распределены поровну.':'Персональное распределение сохранено.');setBusy(false)}
 return <details className="partyMandateEditor"><summary>Мандаты и руководство</summary><StyledSelect label="Председатель партии" value={party.leader_user_id||''} onChange={v=>void g.setPartyLeader(party.id,v)} options={[{value:'',label:'Не назначен'},...staff.map(m=>({value:m.user_id,label:m.full_name}))]}/><label>Мандаты фракции<input type="number" min={0} max={450} step={1} value={total} onChange={e=>setTotal(e.target.valueAsNumber)}/></label><button className="secondary" disabled={frozen||busy||!Number.isInteger(total)||total<0||total>450} onClick={()=>void g.setPartyMandates(party.id,total)}>Сохранить число мандатов</button><p>Персональное распределение: <b>{Number.isFinite(sum)?sum:0} / {party.mandates}</b>. Потери GV распределяются пропорционально пакету каждого студента.</p><div className="partyMandateRows">{staff.map(m=>{const allocation=g.partyMandates.find(a=>a.party_id===party.id&&a.user_id===m.user_id);return <label key={m.user_id}><span>{m.full_name}<small>Доступно {allocation?.effective_mandates||0} голосов · GV −{allocation?.ghost_loss||0}</small></span><input aria-label={'Мандаты: '+m.full_name} type="number" min={0} max={party.mandates} step={1} value={draft[m.user_id]??0} onChange={e=>setDraft(v=>({...v,[m.user_id]:e.target.valueAsNumber}))}/></label>})}</div><div className="civicMandateActions"><button className="primary" disabled={frozen||busy||!valid||!staff.length} onClick={()=>void save()}>Сохранить распределение</button><button className="secondary" disabled={frozen||busy||!staff.length} onClick={()=>void save(true)}>Распределить поровну</button></div>{frozen&&<p>Распределение зафиксировано до завершения открытого голосования ГД.</p>}{notice&&<p role="status">{notice}</p>}</details>;
}
