'use client';
import {useEffect,useState} from 'react';
import {Landmark,ShieldCheck,Clock3} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import type {ReturnTypeRepublic} from './viewTypes';
type Office={id:string;user_id:string;role_title:string;status:string;legal_basis:string;educational_exception:boolean;created_at:string};
const ROLES=['Депутат Государственной Думы','Председатель Государственной Думы','Председатель комитета Государственной Думы','Сенатор Совета Федерации','Президент Российской Федерации','Председатель Правительства Российской Федерации','Министр финансов','Министр экономики','Министр здравоохранения','Министр образования','Министр науки','Министр культуры','Министр транспорта','Министр труда','Министр энергетики','Министр цифрового развития','Министр иностранных дел','Министр внутренних дел','Министр чрезвычайных ситуаций','Министр природных ресурсов','Председатель Банка России','Глава муниципального образования','Глава городской администрации','Редактор СМИ'];
export default function ProfileOffices({g,userId}:{g:ReturnTypeRepublic;userId:string}){
 const [offices,setOffices]=useState<Office[]>([]),[role,setRole]=useState(ROLES[0]),[basis,setBasis]=useState(''),[exception,setException]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){if(!g.game)return;const r=await supabase.from('game_office_assignments').select('*').eq('game_id',g.game.id).eq('user_id',userId).neq('status','ended').order('created_at');if(r.error)setNotice(r.error.message);else setOffices((r.data||[]) as Office[])}
 useEffect(()=>{void load()},[g.game?.id,userId,g.members]);
 const existingRoles=(g.members.find(m=>m.user_id===userId)?.role_title||'').split(' · ').filter(r=>r&&r!=='Участник'&&g.members.find(m=>m.user_id===userId)?.kind==='student'&&!offices.some(o=>o.role_title===r&&o.status==='active'));
 const canInitiate=g.teacher||/президент|председатель.*правительств|глава/i.test(g.me?.role_title||'');
 async function appoint(){if(!g.game||busy)return;setBusy(true);const r=await supabase.rpc('appoint_game_office',{p_game:g.game.id,p_user:userId,p_role:role,p_basis:basis,p_exception:exception});setNotice(r.error?r.error.message:g.teacher?'Должность назначена.':'Представление направлено преподавателю для проверки процедуры.');if(!r.error){setBasis('');await Promise.all([load(),g.refresh()])}setBusy(false)}
 async function review(id:string,approve:boolean){setBusy(true);const r=await supabase.rpc('review_game_office',{p_id:id,p_approve:approve});setNotice(r.error?r.error.message:approve?'Назначение утверждено.':'Должность снята.');if(!r.error)await Promise.all([load(),g.refresh()]);setBusy(false)}
 return <section className="profileOffices"><header><div><small>Игровые полномочия</small><h2>Должности и назначения</h2></div><Landmark size={24}/></header>
 <div className="officeCards">{existingRoles.map(r=><article key={r}><span className="officeIcon"><ShieldCheck/></span><div><h3>{r}</h3><p>Действующая должность текущего этапа</p></div></article>)}{offices.length?offices.map(o=><article key={o.id} className={o.status==='pending'?'pending':''}><span className="officeIcon">{o.status==='active'?<ShieldCheck/>:<Clock3/>}</span><div><h3>{o.role_title}</h3><p>{o.status==='active'?'Действующая должность':'Представление на назначение'}</p><small>{o.legal_basis}</small>{o.educational_exception&&<b>Учебное исключение из правил совместимости</b>}</div>{g.teacher&&<div className="officeActions">{o.status==='pending'&&<button disabled={busy} onClick={()=>void review(o.id,true)}>Утвердить</button>}<button disabled={busy} onClick={()=>void review(o.id,false)}>{o.status==='pending'?'Отклонить':'Снять должность'}</button></div>}</article>):<p>{g.members.find(m=>m.user_id===userId)?.kind==='teacher'?'Преподаватель: полный административный доступ.':existingRoles.length?'Дополнительных назначений пока нет.':'Должности пока не назначены.'}</p>}</div>
 {canInitiate&&<div className="officeAssignmentForm"><label>Должность<select value={role} onChange={e=>setRole(e.target.value)}>{ROLES.map(r=><option key={r}>{r}</option>)}</select></label><label>Основание назначения<textarea value={basis} onChange={e=>setBasis(e.target.value)} rows={2} maxLength={2000} placeholder="Решение, голосование или учебное назначение"/></label>{g.teacher&&<label className="officeException"><input type="checkbox" checked={exception} onChange={e=>setException(e.target.checked)}/>Учебное исключение: разрешить несовместимые должности</label>}<button disabled={busy||basis.trim().length<10} onClick={()=>void appoint()}>{g.teacher?'Назначить должность':'Внести представление'}</button><small>Совместимые статусы сохраняются одновременно. Назначение вышестоящим лицом вступает в силу после проверки процедуры преподавателем. Основа: статьи 83, 97, 111–112 Конституции РФ.</small></div>}
 {notice&&<p role="status">{notice}</p>}</section>;
}
