'use client';
import {useState} from 'react';
import type {ReturnTypeRepublic} from './viewTypes';
import {VSN_LABEL} from './constants';

export default function TeacherView({g}:{g:ReturnTypeRepublic}){
 const {game,currentStage,members,metrics,evaluations,actions,nextStage,setTurn,setTurnMinutes,publishEvent,triggerCrisis,ghostVoting,setEvaluation,updateMember,updateMetric}=g;
 const [eventTitle,setEventTitle]=useState(''),[eventBody,setEventBody]=useState('');
 if(!game)return null;
 async function publish(){if(await publishEvent(eventTitle,eventBody)){setEventTitle('');setEventBody('')}}
 return <><section className="pageHeader"><div><small>РЕЖИССЁРСКАЯ</small><h1>Управление симуляцией</h1><p>Этапы, игровое время, события, роли, KPI, оценивание ВСН и кризисные механики.</p></div><div className="teacherTopButtons"><button className="primary" onClick={nextStage}>Следующий этап</button><button className="secondary" onClick={()=>setTurn(!game.turn_open)}>{game.turn_open?'Поставить на паузу':'Открыть ход'}</button></div></section>
 <section className="teacherPanels"><article className="surface"><div className="surfaceHead"><div><small>ИГРОВОЕ ВРЕМЯ</small><h2>Таймер хода</h2></div></div><div className="timerPresets"><button onClick={()=>setTurnMinutes(10)}>10 мин</button><button onClick={()=>setTurnMinutes(20)}>20 мин</button><button onClick={()=>setTurnMinutes(30)}>30 мин</button><button onClick={()=>setTurnMinutes(60)}>60 мин</button></div><div className="directorFacts"><div><span>Этап</span><b>{currentStage?.stage_no}/16</b></div><div><span>Решений ждут оценки</span><b>{actions.filter(a=>a.status==='submitted').length}</b></div></div></article>
 <article className="surface"><div className="surfaceHead"><div><small>СОБЫТИЕ</small><h2>Публикация в ленту</h2></div></div><input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Заголовок"/><textarea rows={4} value={eventBody} onChange={e=>setEventBody(e.target.value)} placeholder="Описание события"/><button className="primary" onClick={publish}>Опубликовать</button></article>
 <article className="surface dangerSurface"><div className="surfaceHead"><div><small>НЕОПРЕДЕЛЁННОСТЬ</small><h2>Кризисный движок</h2></div></div><p>Случайный выбор кризиса и интенсивности из этапа 15 правил.</p><div className="buttonStack"><button className="primary" onClick={triggerCrisis}>⚠ Разыграть кризис</button><button className="secondary" onClick={ghostVoting}>⚡ Ghost voting: 25–50 депутатов</button></div></article>
 <article className="surface"><div className="surfaceHead"><div><small>ПОКАЗАТЕЛИ</small><h2>Состояние государства</h2></div></div><div className="metricEditor">{metrics.map(m=><label key={m.id}><span>{m.label}</span><input type="number" value={m.value} onChange={e=>updateMetric(m.id,+e.target.value)}/><em>{m.unit||''}</em></label>)}</div></article></section>
 <section className="surface"><div className="surfaceHead"><div><small>ВСН · ЭТАП {currentStage?.stage_no}</small><h2>Индивидуальная оценка вклада</h2></div><span>0 · Н · С · В</span></div><div className="evaluationRows">{members.filter(m=>m.kind!=='teacher').map(m=>{const ev=evaluations.find(x=>x.user_id===m.user_id&&x.stage_no===(currentStage?.stage_no||1));return <div key={m.user_id}><div className="studentIdentity"><b>{m.full_name}</b><span>{m.team||m.group_name||'Без команды'}</span><input value={m.role_title||''} onChange={e=>updateMember(m.user_id,{role_title:e.target.value})} placeholder="Игровая роль"/></div><div className="vsnButtons">{[0,1,2,3].map(s=><button key={s} className={ev?.score===s?'active':''} onClick={()=>setEvaluation(m.user_id,s)}><b>{VSN_LABEL[s]}</b><small>{s}</small></button>)}</div></div>})}</div></section></>
}