'use client';
import {useEffect,useState} from 'react';
import type {Vote,Ballot} from './types';
export default function VoteBallotControls({vote,maxWeight,canCast,ballot,onSubmit}:{vote:Vote;maxWeight:number;canCast:boolean;ballot?:Ballot;onSubmit:(yes:number,no:number,abstain:number)=>Promise<boolean>}){
 const [partial,setPartial]=useState(false),[split,setSplit]=useState(false),[quantity,setQuantity]=useState(maxWeight),[yes,setYes]=useState(0),[no,setNo]=useState(0),[abstain,setAbstain]=useState(0),[busy,setBusy]=useState(false);
 useEffect(()=>setQuantity(maxWeight),[maxWeight]);
 const integer=(v:number)=>Number.isInteger(v)&&v>=0,amount=partial?quantity:maxWeight,total=yes+no+abstain,valid=split?[yes,no,abstain].every(integer)&&total>0&&total<=maxWeight&&(!abstain||vote.allow_abstain):integer(amount)&&amount>0&&amount<=maxWeight;
 async function send(y:number,n:number,a:number){if(!valid||!canCast||busy)return;setBusy(true);try{await onSubmit(y,n,a)}finally{setBusy(false)}}
 const submitted=ballot?{yes:ballot.yes_weight??(ballot.choice==='yes'?ballot.weight:0),no:ballot.no_weight??(ballot.choice==='no'?ballot.weight:0),abstain:ballot.abstain_weight??(ballot.choice==='abstain'?ballot.weight:0)}:null;
 return <section className="civicBallot" aria-label="Подать голоса"><p>{vote.voting_mode==='mandate'?'Доступные депутатские голоса':'Доступные голоса'}: <b>{maxWeight}</b>.</p>
  {vote.voting_mode==='mandate'&&<><label className="civicCheckbox"><input type="checkbox" checked={partial} onChange={e=>{setPartial(e.target.checked);setSplit(false)}}/>Указать количество голосов</label>{partial&&<label className="civicQuantity">Количество<input type="number" min={1} max={maxWeight} step={1} value={Number.isFinite(quantity)?quantity:''} onChange={e=>setQuantity(e.target.valueAsNumber)}/></label>}<label className="civicCheckbox"><input type="checkbox" checked={split} onChange={e=>{setSplit(e.target.checked);if(e.target.checked)setPartial(false)}}/>Распределить голоса между вариантами</label></>}
  {split?<><div className="civicSplitInputs">{(['yes','no',...(vote.allow_abstain?['abstain']:[])] as const).map(key=><label key={key}>{key==='yes'?'За':key==='no'?'Против':'Воздержаться'}<input type="number" min={0} max={maxWeight} step={1} value={Number.isFinite(key==='yes'?yes:key==='no'?no:abstain)?(key==='yes'?yes:key==='no'?no:abstain):''} onChange={e=>(key==='yes'?setYes:key==='no'?setNo:setAbstain)(e.target.valueAsNumber)}/></label>)}</div><p role="status">Распределено: <b>{Number.isFinite(total)?total:0}</b> из {maxWeight}. Осталось: {Math.max(0,maxWeight-(Number.isFinite(total)?total:0))}.</p><button type="button" className="primary" disabled={!canCast||!valid||busy} onClick={()=>void send(yes,no,abstain)}>Подать голоса · {Number.isFinite(total)?total:0}</button></>:<div className="voteChoiceButtons"><button type="button" disabled={!canCast||!valid||busy} onClick={()=>void send(amount,0,0)}>За · {Number.isFinite(amount)?amount:0}</button><button type="button" disabled={!canCast||!valid||busy} onClick={()=>void send(0,amount,0)}>Против · {Number.isFinite(amount)?amount:0}</button>{vote.allow_abstain&&<button type="button" disabled={!canCast||!valid||busy} onClick={()=>void send(0,0,amount)}>Воздержаться · {Number.isFinite(amount)?amount:0}</button>}</div>}
  {!valid&&maxWeight>0&&<p className="civicBallotError" role="alert">Укажите целые числа. Сумма должна быть от 1 до {maxWeight}.</p>}
  {submitted&&<p className="civicMyBallot">Ваши голоса: за {submitted.yes}, против {submitted.no}, воздержались {submitted.abstain}. Всего {ballot?.weight}.</p>}
 </section>;
}
