'use client';
import {useState} from 'react';
import type {ReturnTypeRepublic} from './viewTypes';

export default function VotesView({g}:{g:ReturnTypeRepublic}){
 const {votes,ballots,me,teacher,createVote,canVote,castVote,closeVote,tally,quorum}=g;
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[mode,setMode]=useState<'member'|'faction'|'mandate'>('faction');
 async function create(){if(await createVote({title,body,mode})){setTitle('');setBody('')}}
 return <><section className="pageHeader"><div><small>ПРОЦЕДУРЫ</small><h1>Голосования и кворум</h1><p>Поддерживаются персональное голосование, принцип «одна фракция — один голос» и голосование с весом мандатов. Кворум автоматически считается как 2/3.</p></div></section>
 {teacher&&<section className="surface voteBuilder"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Вопрос голосования"/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Проект решения / пояснение"/><select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="faction">Одна фракция — один голос</option><option value="mandate">Вес = число мандатов</option><option value="member">Один участник — один голос</option></select><button className="primary" onClick={create}>Открыть голосование</button></section>}
 <div className="voteList">{votes.length===0?<div className="emptyState">Голосований пока нет.</div>:votes.map(v=>{const t=tally(v),q=quorum(v),my=ballots.find(b=>b.vote_id===v.id&&b.voter_id===me?.user_id);return <article className={`voteCard ${v.status}`} key={v.id}><div className="voteHead"><div><small>Этап {v.stage_no} · {v.voting_mode==='faction'?'фракции':v.voting_mode==='mandate'?'мандаты':'участники'}</small><h3>{v.title}</h3></div><span>{v.status==='open'?'Открыто':'Закрыто'}</span></div>{v.body&&<p>{v.body}</p>}<div className="quorumLine"><span>Кворум: {q.cast}/{q.needed} из {q.eligible}</span><b className={q.met?'ok':'wait'}>{q.met?'ЕСТЬ КВОРУМ':'НЕТ КВОРУМА'}</b></div><div className="voteScore"><div className="yes"><b>{t.yes}</b><span>ЗА</span></div><div className="bar"><i style={{width:`${t.total?t.yes/t.total*100:50}%`}}/></div><div className="no"><b>{t.no}</b><span>ПРОТИВ</span></div></div>{v.status==='open'&&<div className="voteButtons"><button disabled={!canVote(v)} className={my?.choice==='yes'?'selected yes':''} onClick={()=>castVote(v,'yes')}>За</button><button disabled={!canVote(v)} className={my?.choice==='no'?'selected no':''} onClick={()=>castVote(v,'no')}>Против</button>{!canVote(v)&&<small>В этом режиме голосует председатель вашей фракции.</small>}{teacher&&<button className="secondary" onClick={()=>closeVote(v.id)}>Закрыть</button>}</div>}</article>})}</div></>
}