-- Isolated game, real authenticated RPCs, complete rollback. No student data persists.
begin;
do $$ declare g uuid:=gen_random_uuid();p uuid:=gen_random_uuid();admin uuid:='9fdf732c-1a84-4435-979d-e0272c2b81db';a uuid:='89de1d45-8973-4f38-980d-26042af9e53e';b uuid:='a4795eef-fbf3-4584-bc0b-f7bfee68b783';begin
 perform set_config('request.jwt.claim.sub',admin::text,true);
 insert into public.games(id,title,game_code,owner_id,status,current_round,turn_open) values(g,'QA civic procedures','QA'||substr(replace(g::text,'-',''),1,10),admin,'running',11,true);
 insert into public.game_members(game_id,user_id,full_name,kind,role_title,group_name) values(g,admin,'Проверка преподавателя','teacher','Преподаватель',null);
 insert into public.game_parties(id,game_id,name,mandates,leader_user_id) values(p,g,'QA civic party',450,a);
 insert into public.game_members(game_id,user_id,full_name,kind,role_title,group_name,team) values(g,a,'Проверка А','student','Депутат Государственной Думы','QA','QA civic party'),(g,b,'Проверка Б','student','Депутат Государственной Думы','QA','QA civic party');
 perform set_config('qa.civic_game',g::text,true);perform set_config('qa.civic_party',p::text,true);
end;$$;
set local role authenticated;
do $$ declare g uuid:=current_setting('qa.civic_game')::uuid;p uuid:=current_setting('qa.civic_party')::uuid;admin uuid:='9fdf732c-1a84-4435-979d-e0272c2b81db';a uuid:='89de1d45-8973-4f38-980d-26042af9e53e';b uuid:='a4795eef-fbf3-4584-bc0b-f7bfee68b783';v uuid;result jsonb;blocked boolean;office uuid;d1 uuid;d2 uuid;c uuid;assignment uuid;step integer;body uuid;begin
 perform public.set_student_mandates(p,jsonb_build_object(a::text,240,b::text,210));
 if (select base_mandates from public.party_member_mandates where party_id=p and user_id=a)<>240 then raise exception 'FAIL custom mandate allocation';end if;
 blocked:=false;begin perform public.set_student_mandates(p,jsonb_build_object(a::text,240.5,b::text,209.5));exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL fractional mandates accepted';end if;
 perform public.apply_party_ghost_loss(p,45);
 if (select effective_mandates from public.party_member_mandates where party_id=p and user_id=a)<>216 or (select effective_mandates from public.party_member_mandates where party_id=p and user_id=b)<>189 then raise exception 'FAIL proportional GV';end if;
 v:=public.create_civic_vote(g,'QA no quorum',null,'mandate','gd','registered_session','fraction',.5,'eligible_majority',.5,true,false,null,'none','none','QA');
 perform set_config('request.jwt.claim.sub',a::text,true);blocked:=false;begin perform public.cast_vote_allocation(v,100,0,0);exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL attendance gate';end if;
 perform public.register_institution_session(g,'gd');perform public.cast_vote_allocation(v,180,20,10);
 perform set_config('request.jwt.claim.sub',admin::text,true);result:=public.close_procedural_vote(v);
 if result->>'result'<>'no_quorum' or (result->>'needed')::numeric<>226 or (result->>'eligible')::numeric<>450 or (result->>'present')::numeric<>216 then raise exception 'FAIL fixed GD quorum: %',result;end if;
 perform set_config('request.jwt.claim.sub',b::text,true);perform public.register_institution_session(g,'gd');
 perform set_config('request.jwt.claim.sub',admin::text,true);v:=public.create_civic_vote(g,'QA split ballots',null,'mandate','gd','registered_session','fraction',.5,'eligible_majority',.5,true,false,null,'none','none','QA');
 blocked:=false;begin perform public.set_student_mandates(p,jsonb_build_object(a::text,225,b::text,225));exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL open vote allocation freeze';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.cast_vote_allocation(v,180,20,10);
 perform set_config('request.jwt.claim.sub',b::text,true);blocked:=false;begin perform public.cast_vote_allocation(v,190,0,0);exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL excess votes accepted';end if;
 perform public.cast_vote_allocation(v,100,0,0);perform set_config('request.jwt.claim.sub',admin::text,true);result:=public.close_procedural_vote(v);
 if result->>'result'<>'passed' or (result->>'yes')::numeric<>280 or (result->>'no')::numeric<>20 or (result->>'abstain')::numeric<>10 or (result->>'present')::numeric<>405 or (result->>'cast')::numeric<>310 then raise exception 'FAIL split result / registered presence: %',result;end if;
 office:=public.appoint_game_office(g,a,'Министр здравоохранения','Проверка назначения в тестовой игре',true);perform public.appoint_game_office(g,b,'Министр культуры','Проверка совмещения должностей в тестовой игре',true);
 v:=public.create_civic_vote(g,'QA government group',null,'member','government','registered_session','fraction',.5,'present_majority',.5,true,true,null,'none','none','QA');
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.select_game_office(office);perform public.register_institution_session(g,'government');perform public.cast_vote_allocation(v,1,0,0);
 perform set_config('request.jwt.claim.sub',admin::text,true);result:=public.close_procedural_vote(v);if result->>'result'<>'passed' or (result->>'eligible')::numeric<>2 or (result->>'needed')::numeric<>1 then raise exception 'FAIL group government denominator: %',result;end if;
 body:=public.create_voting_body(g,'QA other public body',array[a,b],a);
 v:=public.create_civic_vote(g,'QA custom body',null,'member','unit:'||body::text,'registered_session','fraction',.5,'present_majority',.5,true,false,null,'none','none','QA');
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.register_institution_session(g,'unit:'||body::text);perform public.cast_vote_allocation(v,1,0,0);result:=public.close_procedural_vote(v);if result->>'result'<>'passed' then raise exception 'FAIL custom chair authority: %',result;end if;
 blocked:=false;begin perform public.create_voting_body(g,'Student-created body',array[a],a);exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL student created an authority';end if;
 perform set_config('request.jwt.claim.sub',admin::text,true);
 d1:=public.create_formal_document(g,11,'QA first decree','president_decree','president','Президент Российской Федерации','1. Тестовый текст акта.',null,null,null,'president_act','{"issuer":"Президент Российской Федерации","signed_name":"Подложное имя","signed_role":"Подложная должность"}');
 d2:=public.create_formal_document(g,11,'QA second decree','president_decree','president','Президент Российской Федерации','1. Второй текст акта.',null,null,null,'president_act','{"issuer":"Президент Российской Федерации"}');
 if (select metadata->>'act_number' from public.formal_documents where id=d1)=(select metadata->>'act_number' from public.formal_documents where id=d2) or (select metadata->>'registered_on' from public.formal_documents where id=d1) is null then raise exception 'FAIL automatic number/date';end if;
 if coalesce((select metadata->>'signed_name' from public.formal_documents where id=d1),'')<>'' then raise exception 'FAIL forged signer on creation';end if;
 for step in 1..4 loop exit when (select status_code from public.formal_documents where id=d1) in ('signed','published');perform public.advance_formal_document(d1,'advance','QA signing');end loop;
 if coalesce((select metadata->>'signed_by' from public.formal_documents where id=d1),'')<>admin::text then raise exception 'FAIL actual signer snapshot';end if;
 c:=public.create_assigned_event(g,'QA legal feedback','Учебная ситуация для проверки открытия правового разбора только после принятого ответа.','Здравоохранение','serious','single','[{"label":"Проверить лекарства","trust":2,"description":"Качество проверено"},{"label":"Отказаться от проверки","trust":-2,"description":"Контроль качества не проведён"}]',array[a],array['министр здравоохранения']);
 perform set_config('request.jwt.claim.sub',a::text,true);blocked:=false;begin perform public.get_event_decision_feedback(c);exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL feedback revealed before answer';end if;
 select id into assignment from public.event_assignments where case_id=c and recipient_id=a;perform public.submit_event_decision(assignment,'option_1',null);result:=public.get_event_decision_feedback(c);if result->>'role'<>'Министр здравоохранения' then raise exception 'FAIL decision role snapshot: %',result;end if;
end;$$;
reset role;
select jsonb_build_object('manual_mandates','PASS','proportional_gv','PASS','fixed_450_quorum','PASS','attendance_gate','PASS','excess_guard','PASS','split_ballot','PASS','open_vote_freeze','PASS','group_denominator','PASS','custom_authority_and_chair','PASS','automatic_numbers_dates','PASS','actual_signer','PASS','post_decision_feedback','PASS') as checks;
rollback;
