-- Live classroom observability: student activity and current presence.
create table if not exists public.game_activity(
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  label text not null,
  view_key text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists game_activity_game_created_idx on public.game_activity(game_id,created_at desc);
create index if not exists game_activity_actor_idx on public.game_activity(actor_id,created_at desc);
alter table public.game_activity enable row level security;
grant select,insert on public.game_activity to authenticated;
drop policy if exists game_activity_teacher_read on public.game_activity;
create policy game_activity_teacher_read on public.game_activity for select to authenticated using(private.is_game_teacher(game_id));
drop policy if exists game_activity_own_insert on public.game_activity;
create policy game_activity_own_insert on public.game_activity for insert to authenticated
with check(actor_id=(select auth.uid()) and private.is_game_member(game_id));

create table if not exists public.game_presence(
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  current_view text not null default 'dashboard',
  last_seen_at timestamptz not null default now(),
  primary key(game_id,user_id)
);
create index if not exists game_presence_seen_idx on public.game_presence(game_id,last_seen_at desc);
alter table public.game_presence enable row level security;
grant select,insert,update on public.game_presence to authenticated;
drop policy if exists game_presence_teacher_read on public.game_presence;
create policy game_presence_teacher_read on public.game_presence for select to authenticated using(private.is_game_teacher(game_id));
drop policy if exists game_presence_own_write on public.game_presence;
create policy game_presence_own_write on public.game_presence for all to authenticated
using(user_id=(select auth.uid()) and private.is_game_member(game_id))
with check(user_id=(select auth.uid()) and private.is_game_member(game_id));

do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='game_activity') then
    alter publication supabase_realtime add table public.game_activity;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='game_presence') then
    alter publication supabase_realtime add table public.game_presence;
  end if;
end $$;
