-- Formal institutions / NPA registry.
create sequence if not exists public.formal_registry_seq;

create table if not exists public.formal_documents(
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  stage_no integer not null default 12 check(stage_no between 1 and 16),
  registry_no text not null unique,
  title text not null,
  doc_type text not null,
  subject_key text not null,
  subject_label text not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  body_text text,
  source_file_path text,
  source_file_name text,
  source_mime_type text,
  workflow_key text not null,
  workflow_steps jsonb not null,
  current_step integer not null default 0,
  status_code text not null default 'draft',
  status_label text not null default 'Черновик',
  current_owner_key text not null default 'author',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists formal_documents_game_idx on public.formal_documents(game_id,updated_at desc);
create index if not exists formal_documents_author_idx on public.formal_documents(author_id);
create index if not exists formal_documents_stage_idx on public.formal_documents(game_id,stage_no,status_code);
alter table public.formal_documents enable row level security;
grant select on public.formal_documents to authenticated;
drop policy if exists formal_documents_read on public.formal_documents;
create policy formal_documents_read on public.formal_documents for select to authenticated using(private.is_game_member(game_id));

create table if not exists public.formal_document_history(
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.formal_documents(id) on delete cascade,
  game_id uuid not null references public.games(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  from_status text,
  to_status text,
  from_owner text,
  to_owner text,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists formal_history_doc_idx on public.formal_document_history(document_id,created_at);
create index if not exists formal_history_game_idx on public.formal_document_history(game_id,created_at desc);
alter table public.formal_document_history enable row level security;
grant select on public.formal_document_history to authenticated;
drop policy if exists formal_history_read on public.formal_document_history;
create policy formal_history_read on public.formal_document_history for select to authenticated using(private.is_game_member(game_id));

create or replace function private.formal_workflow(p_key text)
returns jsonb language sql immutable as $$
select case p_key
when 'bill' then '[
 {"code":"draft","label":"Черновик","owner":"author","action":"Внести в Государственную Думу"},
 {"code":"registered","label":"Зарегистрирован в ГД","owner":"gd_staff","action":"Направить в профильный комитет"},
 {"code":"committee","label":"Профильный комитет","owner":"committee","action":"Передать в Совет ГД"},
 {"code":"council","label":"Совет Государственной Думы","owner":"gd_council","action":"Назначить I чтение"},
 {"code":"reading1","label":"I чтение","owner":"gd","action":"Принять в I чтении"},
 {"code":"amendments","label":"Поправки и подготовка ко II чтению","owner":"committee","action":"Передать на II чтение"},
 {"code":"reading2","label":"II чтение","owner":"gd","action":"Принять во II чтении"},
 {"code":"reading3","label":"III чтение","owner":"gd","action":"Принять закон"},
 {"code":"sf","label":"Совет Федерации","owner":"sf","action":"Одобрить"},
 {"code":"president","label":"Президент Российской Федерации","owner":"president","action":"Подписать"},
 {"code":"published","label":"Подписан и опубликован","owner":"system","action":null}
]'::jsonb
when 'president_act' then '[
 {"code":"draft","label":"Проект акта Президента","owner":"author","action":"Передать на правовую подготовку"},
 {"code":"review","label":"Правовая подготовка","owner":"president","action":"Подписать Президентом"},
 {"code":"signed","label":"Подписан Президентом","owner":"president","action":"Направить на опубликование"},
 {"code":"published","label":"Официально опубликован","owner":"system","action":null}
]'::jsonb
when 'government_act' then '[
 {"code":"draft","label":"Проект акта Правительства","owner":"author","action":"Внести в Правительство"},
 {"code":"agenda","label":"В повестке Правительства","owner":"government","action":"Рассмотреть на заседании"},
 {"code":"adopted","label":"Принят Правительством","owner":"government","action":"Подписать и опубликовать"},
 {"code":"published","label":"Подписан и опубликован","owner":"system","action":null}
]'::jsonb
when 'gd_resolution' then '[
 {"code":"draft","label":"Проект постановления ГД","owner":"author","action":"Внести в Совет ГД"},
 {"code":"agenda","label":"В повестке Государственной Думы","owner":"gd_council","action":"Поставить на голосование"},
 {"code":"adopted","label":"Принято Государственной Думой","owner":"gd_staff","action":"Оформить и опубликовать"},
 {"code":"published","label":"Оформлено","owner":"system","action":null}
]'::jsonb
when 'sf_resolution' then '[
 {"code":"draft","label":"Проект постановления СФ","owner":"author","action":"Внести в Совет Федерации"},
 {"code":"agenda","label":"На рассмотрении Совета Федерации","owner":"sf","action":"Поставить на голосование"},
 {"code":"adopted","label":"Принято Советом Федерации","owner":"sf","action":"Оформить"},
 {"code":"published","label":"Оформлено","owner":"system","action":null}
]'::jsonb
when 'ministry_act' then '[
 {"code":"draft","label":"Проект ведомственного акта","owner":"author","action":"Передать на согласование"},
 {"code":"review","label":"Ведомственное согласование","owner":"ministry","action":"Подписать"},
 {"code":"signed","label":"Подписан министром","owner":"ministry","action":"Опубликовать"},
 {"code":"published","label":"Опубликован","owner":"system","action":null}
]'::jsonb
when 'municipal_act' then '[
 {"code":"draft","label":"Проект муниципального акта","owner":"author","action":"Внести на рассмотрение"},
 {"code":"meeting","label":"Рассмотрение муниципальным органом","owner":"municipality","action":"Принять"},
 {"code":"adopted","label":"Принят","owner":"municipality","action":"Оформить"},
 {"code":"published","label":"Оформлен","owner":"system","action":null}
]'::jsonb
else '[
 {"code":"draft","label":"Черновик","owner":"author","action":"Передать на рассмотрение"},
 {"code":"review","label":"На рассмотрении","owner":"teacher","action":"Принять"},
 {"code":"published","label":"Принят","owner":"system","action":null}
]'::jsonb end;
$$;

drop policy if exists game_assets_formal_insert on storage.objects;
create policy game_assets_formal_insert on storage.objects for insert to authenticated
with check(bucket_id='game-assets' and split_part(name,'/',2)='formal' and private.is_game_member((split_part(name,'/',1))::uuid));

do $$
begin
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='formal_documents') then
  alter publication supabase_realtime add table public.formal_documents;
 end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='formal_document_history') then
  alter publication supabase_realtime add table public.formal_document_history;
 end if;
end $$;
